### PR TITLE
KMCNG-953

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-953

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/430)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6z3sj1_96voUcFOL3n:-L6z3sj1_96voUcFOL3o:b-fdibw6) (no related file):*

seems out of the metadata area

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6z3sj1_96voUcFOL3n:-L6zNUIa9WeEhisDjn7L:b-c3zauf) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>


seems out of the metadata area
</blockquote></details>

+@amirch1 could you please take a look how can I stick `kSticky` to the right of section border and not the window? It's set to `position: fixed` by component itself

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6z3sj1_96voUcFOL3n:-L6zT-5Sy5wAFvXQHFw3:b-gix1if) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@amirch1 could you please take a look how can I stick `kSticky` to the right of section border and not the window? It's set to `position: fixed` by component itself
</blockquote></details>

seems problematic. I suggest discussing with Shlomit regarding this feature, we might decide do remove it or make the Jump To button scroll up with the metadata content area. I will check and let you know. Lets keep this bug open for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6z3sj1_96voUcFOL3n:-L6zTTRG04k2msDUeGKp:bb7m07t) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

seems problematic. I suggest discussing with Shlomit regarding this feature, we might decide do remove it or make the Jump To button scroll up with the metadata content area. I will check and let you know. Lets keep this bug open for now.
</blockquote></details>

okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-:-L6zTuGaeiHtqALUDLqh:bnfp4nl)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-:-L6zkUw02cwvhrTlLjG6:bnfp4nl)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6zm1tn2WcO9y3tv9Iv:-L6zm1tn2WcO9y3tv9Iw:b-uten7t) (no related file):*
following a discussion with +@amirch1 we will postpone this bug for now and will wait to additional feedback from Shlomit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/430#-L6zm1tn2WcO9y3tv9Iv:-L7-9HM2i6ItvnaiEdMD:bb7m07t) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

following a discussion with +@amirch1 we will postpone this bug for now and will wait to additional feedback from Shlomit
</blockquote></details>

okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/430)*

**Comment by amirch1** [comment]
After discussion with Shlomit - redundant.

**Pull request closed without merging**
