### PR TITLE
Replace video

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/376799276/Replace+Video+Widget

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)

### CODE REVIEW

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEmn4GDd5NOzfJVDtX:-LEEmn4GDd5NOzfJVDtY:bb0znk6) (no related file):*
Minor UI fixes required:
1. Gap between buttons should be 24px (currently 28px)
2. Gap between the buttons bottom border and the table should be 2px larger
3. Refresh button should be vertical aligned with the buttons (move up about 6px or so)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEolEr-tqGs8NHOTw0:-LEEolEr-tqGs8NHOTw1:bzczp5w) (no related file):*
when selected file for replacement, the "Update Video" panel opens with the default transcoding profile selected but the "transcoding flavor" dropdown stays disabled until selecting another transcoding profile. We should set the dropdown content and enable/disable upon selecting the default transcoding profile:



---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEpUc8386KuERCI17O:-LEEpUc8386KuERCI17P:bih5dlq) (no related file):*
When starting replacement, the auto approved is already selected the the button is disabled. The button should be enabled according to the design here: https://projects.invisionapp.com/d/main#/console/12328412/290541215/preview until clicked.



---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEqavDC5ySvmN9mL0B:-LEEqavDC5ySvmN9mL0C:b-6cs8x5) (no related file):*
When trying to replace with the "Default" transcoding profile - getting an error that the profile is not found and then when trying to cancel the replacement another error that the entry cannot be deleted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEtp1PCDJZQqW4nDcR:-LEEuW6rD4yZS8yhKF5n:bkplirq) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

missing helpTip in both "Remote Storage" views:
1. For "Replace Video": https://projects.invisionapp.com/d/main#/console/12328412/297177904/preview
2. For link of a single flavor: https://projects.invisionapp.com/d/main#/console/12328412/297192749/preview (same helpTip text as in replace video)
</blockquote></details>

Seems my mistake, missing only for single flavor of a video asset (exists in audio)

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEmn4GDd5NOzfJVDtX:-LEExnX5BcvwtL82x3yS:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Minor UI fixes required:
1. Gap between buttons should be 24px (currently 28px)
2. Gap between the buttons bottom border and the table should be 2px larger
3. Refresh button should be vertical aligned with the buttons (move up about 6px or so)
</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEolEr-tqGs8NHOTw0:-LEF2fnV7kvYNOaaVff8:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

when selected file for replacement, the "Update Video" panel opens with the default transcoding profile selected but the "transcoding flavor" dropdown stays disabled until selecting another transcoding profile. We should set the dropdown content and enable/disable upon selecting the default transcoding profile:



</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEpUc8386KuERCI17O:-LEF4SNoEV7KrIHpJVuW:b27rai7) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

When starting replacement, the auto approved is already selected the the button is disabled. The button should be enabled according to the design here: https://projects.invisionapp.com/d/main#/console/12328412/290541215/preview until clicked.



</blockquote></details>

I couldn't reproduce this one, the button behaves and looks expected

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEqavDC5ySvmN9mL0B:-LEF5VyZDBOwIL4P3Noe:b7j7zfs) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

When trying to replace with the "Default" transcoding profile - getting an error that the profile is not found and then when trying to cancel the replacement another error that the entry cannot be deleted.
</blockquote></details>

Couldn't reproduce as well

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEEtp1PCDJZQqW4nDcR:-LEF8Bqg5fzapePyJwzw:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Seems my mistake, missing only for single flavor of a video asset (exists in audio)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts, line 179 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEJinB83KxiY146KAFb:-LEJinB83KxiY146KAFc:bo9sj0g) ([raw file](https://github.com/kaltura/kmc-ng/blob/468af8932c1ba18521f2a04aae5f652835449981/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts#L179)):*
> ```XML
>             .map(responses => {
>                 if (responses.hasErrors()) {
>                     const message = responses.reduce((acc, val) => `${acc}\n${val.error ? val.error.message : ''}`, '');
> ```

check the permissions first and decide if need to show this option and send request. It is ok to throw errors here for other scenarios.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts, line 329 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEJm07m7Wz4o_it36Qu:-LEJm07m7Wz4o_it36Qv:bg0jwvc) ([raw file](https://github.com/kaltura/kmc-ng/blob/5357b0712414d09dcbff5494d04fd3467feb3a53/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts#L329)):*
> ```XML
> 
>                         case TrackedFileStatuses.uploadCompleted:
>                             this._refresh(false, false);
> ```

after the change you will show loading in area blocker here. Is it the desired behavior 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEJeL4H1xdjp1zLAFIa:-LEK0-fy8--GAnyTebgu:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

URL validation is not requires when linking to remote storage as the input is not a URL
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts, line 179 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEJinB83KxiY146KAFb:-LEJvJ9X0RQ5NuJZ8hkn:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/468af8932c1ba18521f2a04aae5f652835449981/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts#L179)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

check the permissions first and decide if need to show this option and send request. It is ok to throw errors here for other scenarios.
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts, line 329 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/634#-LEJm07m7Wz4o_it36Qu:-LEJvy0O6nsVmpjwnei8:bo7jxiv) ([raw file](https://github.com/kaltura/kmc-ng/blob/5357b0712414d09dcbff5494d04fd3467feb3a53/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts#L329)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

after the change you will show loading in area blocker here. Is it the desired behavior 
</blockquote></details>

I think so, I didn't change this behavior

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Comment by esakal** [comment]
Dismissed @amirch1 and @diamond-darrell from a discussion.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/634)*

**Pull request merged**
