### PR TITLE
feat: Categories status polling - display locked or updating categories status

### PR DESCRIPTION
**Pull request by amirch1**
to be tested with [the following PR](https://github.com/kaltura/kaltura-ng/pull/73)

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/347)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 13 of 25 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bCzbLRsjzTPYuwHn5:-L3bCzbLRsjzTPYuwHn6:b-h6zq5a) (no related file):*
shouldn't we prevent fetching of categories when entering the categories view?



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bDKbFknhbPk-uH6g3:-L3bDKbFknhbPk-uH6g4:bsa0p5k) (no related file):*
there are layout issues but I think you should not open the popup at all. Obviously we need make think how the application should behave when lock down mode was detected and you are already inside the popup/category details/move etc...



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bDkwLxPVSNENjMTVz:-L3bDkwLxPVSNENjMTW-:bmb26tq) (no related file):*
some general questions: 
- should remove from category works during lock mode?
- what about auto complete of categories (like in entries>metadata) is it allowed during lock mode?
- according to prd if error occurred should ignore it silently, is this how the legacy works? Regardless I think an 'anigma' mode should be added to handle uncertainties. 
- when you are in categories view and the categories lock mode is removed, shouldn't you force list reload?

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bFYhWDewYGJvKBNOT:-L3bFYhWDewYGJvKBNOU:b3xzcqd) (no related file):*
- should this be visible only when the popup is closed? shouldn't it be only if the popup is open?
- was the content of the tooltip taken from the legacy?



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bGGPKDPMg92m4CRme:-L3bGGPKDPMg92m4CRmf:bmm9shb) (no related file):*
layout issue


---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bGQGfx2JBTa5-O4Yc:-L3bGQGfx2JBTa5-O4Yd:bh9peme) (no related file):*
the position is misleading





---

*[src/app/app.module.ts, line 178 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bHkmXj-FjhxwxPU8l:-L3bHkmXj-FjhxwxPU8m:b-n5lzit) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/app/app.module.ts#L178)):*
> ```XML
>     },
>     ConfirmationService,
>     CategoriesStatusMonitorService
> ```

you should have a dedicated module in `content-shared/categories-status` with`.forRoot()`. see in other places

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 175 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bIHKF2ckmITtPby3k:-L3bIHKF2ckmITtPby3l:b3kre) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L175)):*
> ```XML
>         if (result.confirmed) {
>           setTimeout(() => {
>             this.executeService(this._bulkDeleteService, {}, true, false, () => {this._categoriesStatusMonitorService.updateCategoriesStatus();});
> ```

?

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.html, line 6 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bIS2RHzh9ChMgKEgS:-L3bIS2RHzh9ChMgKEgT:b-ncykvy) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/applications/content-categories-app/categories/categories-list/categories-list.component.html#L6)):*
> ```HTML
>       <span>{{'applications.content.categories.categoriesLockMsg' | translate}}</span>
>     </div>
>     <div class="kContent kSeparator" *ngIf="_categoriesLocked"></div>
> ```

what is the purpose of this class? is it here on purpose? both the kContent and kSeperator

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 64 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bK2-JjW5CQL9sZYps:-L3bK2-JjW5CQL9sZYpt:bhsiw5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L64)):*
> ```XML
>                 private _categoriesStatusMonitorService: CategoriesStatusMonitorService) {
> 
>         this._categoriesStatusMonitorService.$categoriesStatus
> ```

move to `onInit'

---

*[src/applications/content-categories-app/categories/move-category/move-category.component.ts, line 33 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bJy-Z-2sGrpHtLlqy:-L3bJy-Z-2sGrpHtLlqz:bhsiw5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/move-category/move-category.component.ts#L33)):*
> ```XML
>               private _categoriesStatusMonitorService: CategoriesStatusMonitorService) {
> 
>     this._categoriesStatusMonitorService.$categoriesStatus
> ```

move to `onInit'

---

*[src/applications/content-categories-app/categories/new-category/new-category.component.ts, line 35 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKFlnHbbiysFveyLI:-L3bKFlnHbbiysFveyLJ:bhsiw5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/new-category/new-category.component.ts#L35)):*
> ```XML
>               private _categoriesStatusMonitorService: CategoriesStatusMonitorService) {
> 
>     this._categoriesStatusMonitorService.$categoriesStatus
> ```

move to `onInit'

---

*[src/applications/content-categories-app/category/category.component.ts, line 60 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKU-cZ1B2GYStKf8c:-L3bKU-cZ1B2GYStKf8d:b-8396ck) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/category/category.component.ts#L60)):*
> ```XML
> 	    .subscribe((status: CategoriesStatus) => {
>           if (status.lock){
>             this._router.navigate(['content/categories']);
> ```

I don't think this handle the requirement 

---

*[src/applications/content-categories-app/category/category.component.ts, line 63 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKQclI_MNMY6flWI-:-L3bKQclI_MNMY6flWI0:but8n38) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/category/category.component.ts#L63)):*
> ```XML
>           }
>         });
>     this._categoriesStatusMonitorService.updateCategoriesStatus();
> ```

I think it shouldn't be here.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts, line 79 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKvf83iZGAVa-v5GU:-L3bKvf83iZGAVa-v5GV:bhsiw5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts#L79)):*
> ```XML
>     private _categoriesStatusMonitorService: CategoriesStatusMonitorService) {
> 
>     this._categoriesStatusMonitorService.$categoriesStatus
> ```

move to `onInit'

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.html, line 11 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bLuqrYFcMAb4Nlg1s:-L3bLuqrYFcMAb4Nlg1t:bgos3xc) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.html#L11)):*
> ```HTML
> 			<div class="k-spinner-animation kSpinnerAnim"></div>
> 		</div>
> 		<span *ngIf="!_selectedCategories.length && !_categoriesLocked">{{'applications.content.entryDetails.metadata.catSelect' | translate}}</span>
> ```

what should it do? can you show me?

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 26 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bMzjhSQyiDrgoctRu:-L3bMzjhSQyiDrgoctRv:b-hlyngy) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L26)):*
> ```XML
> 
>     private _status = new BehaviorSubject<CategoriesStatus>({ lock: false, update: false });
>     public readonly $categoriesStatus = this._status.asObservable();
> ```

the dollar sign should be the suffix -> `categoriesStatus$`
consider shorten it to `status$`

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 72 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bPNeonWz2jyUGHLFs:-L3bPNeonWz2jyUGHLFt:b-5k4xh4) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L72)):*
> ```XML
>                     case KalturaFeatureStatusType.lockCategory:
>                         lockFlagFound = true;
>                         updateFlagFound = true;
> ```

is this on purpose?  isn't it either lock or update?

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 80 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bP_hYkBuGz5qKAmYC:-L3bP_hYkBuGz5qKAmYD:bujy8gt) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L80)):*
> ```XML
>             });
>         }
>         this._logger.info(`got categories status: locked: ${lockFlagFound}, update: ${updateFlagFound}`);
> ```

write logger and update status only if changes occurred. otherwise the whole application will respond every 30 seconds with the same status



---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 87 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bQ0ttM5XdipxZIaOH:-L3bQ0ttM5XdipxZIaOI:b4btpav) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L87)):*
> ```XML
>     // API to invoke immediate categories status update
>     public updateCategoriesStatus():void{
>         this._kalturaClient.request(new PartnerListFeatureStatusAction({})).cancelOnDestroy(this)
> ```

consider using the factory function to build the request. but this DRY is minor

---

*[src/shared/content-shared/entries/entries-list/entries-list.component.ts, line 59 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bOxvoTkJ5pHug5KDs:-L3bOxvoTkJ5pHug5KDt:bhsiw5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/entries/entries-list/entries-list.component.ts#L59)):*
> ```XML
>                 private _appLocalization: AppLocalization,
>                 private _browserService: BrowserService, private _categoriesStatusMonitorService: CategoriesStatusMonitorService) {
>         this._categoriesStatusMonitorService.$categoriesStatus
> ```

move to `onInit'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bCzbLRsjzTPYuwHn5:-L3bVEaJsXFvky4dJHQV:bq8w3pr) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

shouldn't we prevent fetching of categories when entering the categories view?



</blockquote></details>

not relevant

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 175 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bIHKF2ckmITtPby3k:-L3bXYHqgMwo2UODP_sT:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L175)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.html, line 11 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bLuqrYFcMAb4Nlg1s:-L3bYbnQFUpj80yoxIdc:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.html#L11)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

what should it do? can you show me?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bDkwLxPVSNENjMTVz:-L3c5MiKdhLL5oHIcEZm:b-dffylv) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

some general questions: 
- should remove from category works during lock mode?
- what about auto complete of categories (like in entries>metadata) is it allowed during lock mode?
- according to prd if error occurred should ignore it silently, is this how the legacy works? Regardless I think an 'anigma' mode should be added to handle uncertainties. 
- when you are in categories view and the categories lock mode is removed, shouldn't you force list reload?
</blockquote></details>

reloading categories when lock is removed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bFYhWDewYGJvKBNOT:-L3c5Tz0p6iXSM-RCchb:b7xofjh) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- should this be visible only when the popup is closed? shouldn't it be only if the popup is open?
- was the content of the tooltip taken from the legacy?



</blockquote></details>

tooltip content from legacy approved by UX

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bGGPKDPMg92m4CRme:-L3c5XvTUh6o-kdboz-C:b-7ql1td) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

layout issue


</blockquote></details>

fixed

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bGQGfx2JBTa5-O4Yc:-L3c5_OOT_0XoWTj3Zdx:b-2jkj85) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the position is misleading





</blockquote></details>

fixed according to updated design: https://projects.invisionapp.com/d/main#/console/12328412/269223006/preview 

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.html, line 6 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bIS2RHzh9ChMgKEgS:-L3cB5Z77a-pCwYdJd-G:b-6jgv0g) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/applications/content-categories-app/categories/categories-list/categories-list.component.html#L6)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

what is the purpose of this class? is it here on purpose? both the kContent and kSeperator
</blockquote></details>

Done. Changes to class binding.

---

*[src/applications/content-categories-app/category/category.component.ts, line 63 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKQclI_MNMY6flWI-:-L3cGaaIUgE9R0BQ2_NB:bigy5t1) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/category/category.component.ts#L63)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I think it shouldn't be here.
</blockquote></details>

its there to handle deep-linking: when user navigates directly to a category, we want to check the status immediately and redirect him to the locked screen if categories are locked. Logic moved to onInit

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 26 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bMzjhSQyiDrgoctRu:-L3cIpGMXdwKJZtOqDfi:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L26)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the dollar sign should be the suffix -> `categoriesStatus$`
consider shorten it to `status$`
</blockquote></details>

Done.

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 72 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bPNeonWz2jyUGHLFs:-L3cIrBT_d-h75ADmGLr:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L72)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is this on purpose?  isn't it either lock or update?
</blockquote></details>

Done.

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 87 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bQ0ttM5XdipxZIaOH:-L3cMYhDxXNujZ_xAQKk:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L87)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider using the factory function to build the request. but this DRY is minor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[src/app/app.module.ts, line 178 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bHkmXj-FjhxwxPU8l:-L3cNlTqVtnxFO6ChOMm:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/4d4bf862b2822a75039088eee725c51d47c0ee0f/src/app/app.module.ts#L178)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should have a dedicated module in `content-shared/categories-status` with`.forRoot()`. see in other places
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 64 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bK2-JjW5CQL9sZYps:-L3cNn0iYIpNhnM0oA4G:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L64)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move to `onInit'
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/move-category/move-category.component.ts, line 33 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bJy-Z-2sGrpHtLlqy:-L3cNncHYX_lojcwsG2l:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/move-category/move-category.component.ts#L33)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move to `onInit'
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/new-category/new-category.component.ts, line 35 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKFlnHbbiysFveyLI:-L3cNoKB6tPXO-Ee5jeo:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/categories/new-category/new-category.component.ts#L35)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move to `onInit'
</blockquote></details>

Done.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts, line 79 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKvf83iZGAVa-v5GU:-L3cNrsUYSZGNdSIdz-m:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts#L79)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move to `onInit'
</blockquote></details>

Done.

---

*[src/shared/content-shared/categories-status/categories-status-monitor.service.ts, line 80 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bP_hYkBuGz5qKAmYC:-L3cNtddGgj773qCzFH3:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/categories-status/categories-status-monitor.service.ts#L80)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

write logger and update status only if changes occurred. otherwise the whole application will respond every 30 seconds with the same status



</blockquote></details>

Done.

---

*[src/shared/content-shared/entries/entries-list/entries-list.component.ts, line 59 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bOxvoTkJ5pHug5KDs:-L3cNixM3ypAAafJ67mM:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/shared/content-shared/entries/entries-list/entries-list.component.ts#L59)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move to `onInit'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[src/applications/content-categories-app/category/category.component.ts, line 60 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKU-cZ1B2GYStKf8c:-L3cO6wwtcOkqpLJtWLJ:bdxoc5i) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/category/category.component.ts#L60)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I don't think this handle the requirement 
</blockquote></details>

will verify against legacy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bDKbFknhbPk-uH6g3:-L3cORlISVdWMdPXMzSG:b-7ql1td) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

there are layout issues but I think you should not open the popup at all. Obviously we need make think how the application should behave when lock down mode was detected and you are already inside the popup/category details/move etc...



</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by esakal** [comment]
Reviewed 20 of 20 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-categories-app/category/category.component.ts, line 63 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3bKQclI_MNMY6flWI-:-L3va-p7wDlTd3ZG0rWw:b7tiwxu) ([raw file](https://github.com/kaltura/kmc-ng/blob/0f16c5570c263f926dea63d0b1d222d650af4857/src/applications/content-categories-app/category/category.component.ts#L63)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

its there to handle deep-linking: when user navigates directly to a category, we want to check the status immediately and redirect him to the locked screen if categories are locked. Logic moved to onInit
</blockquote></details>

Let's discuss

---

*[src/applications/content-categories-app/category/category.component.ts, line 66 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-L3va2zKALmDQY9qpxyK:-L3va2zKALmDQY9qpxyL:b-6by84j) ([raw file](https://github.com/kaltura/kmc-ng/blob/2bdd36ef2d80eed77d52494c556d516b9abf3049/src/applications/content-categories-app/category/category.component.ts#L66)):*
> ```XML
>   ngOnInit() {
>     this._categoriesStatusMonitorService.status$
> 	    .cancelOnDestroy(this)
> ```

if you want to handle it only once you should use the `.first()` operator.
leaving the code as-is is problematic because the user will be kicked to categories even if he has changes. 

let's discuss

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r4, 7 of 7 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347#-:-L3xHBi7LgLL6F3JJ70f:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/347)*

**Pull request merged**
