### PR TITLE
KMCNG-453 KMC-ng confirmation should replace breakline symbol \n with…

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
… <br/>

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/179)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 76 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/179#-Kqq8Gyrz45lGxpuHei-:-Kqq8GysUikvJKrkyW5F:b-uv9so4) ([raw file](https://github.com/kaltura/kmc-ng/blob/1063fab9cfaae940a7457d1121ed3545ace30bce/src/shared/kmc-shell/providers/browser.service.ts#L76)):*
> ```XML
> 	public confirm(confirmation : Confirmation) {
> 		confirmation.key = "confirm";
> 		confirmation.message = confirmation.message.replace(/(?:\r\n|\r|\n)/g, '<br />');
> ```

Please follow the design provided. By design, you shouldn't change this function.  The link I provided refer to the following [function](https://github.com/kaltura/kmc-ng/blob/master/src/app/app.component.ts#L28)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/179)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/179)*

**Comment by esakal** [comment]
modify it in the `app.component`

```
this._browserService.registerOnShowConfirmation((message) =>
    {
      // do whatever needed
      let htmlMessageContent = message.message.replace('\n','<br/>');
      
      const newMessage = Object.assign({},message, { message : htmlMessageContent });
      this._confirmationService.confirm(newMessage);
    });
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/179#-:-KqwrfBdyFH1Wi7vn265:bjrin23)*

**Comment by konstantin-stepanets** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 76 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/179#-Kqq8Gyrz45lGxpuHei-:-Kqx0b6KdvJbEeUU9KiY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/1063fab9cfaae940a7457d1121ed3545ace30bce/src/shared/kmc-shell/providers/browser.service.ts#L76)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Please follow the design provided. By design, you shouldn't change this function.  The link I provided refer to the following [function](https://github.com/kaltura/kmc-ng/blob/master/src/app/app.component.ts#L28)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/179)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/179)*

**Pull request merged**
