### PR TITLE
KMCNG-1588

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1588

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/663)

### CODE REVIEW

**Comment by esakal** [comment]
-reviewer:@esakal +@amirch1 please review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/663#-:-LD6OsWhChy4BNXPxdF1:b6t303o)*

**Comment by amirch1** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/663#-LD6QI6S4cfm9B3DNMiw:-LD6QI6S4cfm9B3DNMix:b-ofjhcr) (no related file):*
Stas - were you able to reproduce this issue and saw that "text-overflow: ellipsis;" solves this? I couldn't reproduce until I changes the view zoom to 110% and then the "text-overflow: ellipsis;" did not solve the issue. I was able to solve this by using "overflow: hidden;"

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/663)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/663#-LD6QI6S4cfm9B3DNMiw:-LDeTg1z61Qei6yKqqJv:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Stas - were you able to reproduce this issue and saw that "text-overflow: ellipsis;" solves this? I couldn't reproduce until I changes the view zoom to 110% and then the "text-overflow: ellipsis;" did not solve the issue. I was able to solve this by using "overflow: hidden;"
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/663)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/663#-:-LDfSQuk-6jQ_kNP9MHB:bnfp4nl)*

**Pull request merged**
