### PR TITLE
KMCNG-1280

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1280

**What is the new behavior?**
Update parent category when removing child

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/379)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/379#-L4VkbttB6VKwHF6bLu7:-L4VkbttB6VKwHF6bLu8:b-8j9cbb) (no related file):*
I think this PR doesn't address the original issue

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/379)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/379#-L4VkbttB6VKwHF6bLu7:-L4esEnWSMRXaU95PKGk:b-xsstvh) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I think this PR doesn't address the original issue
</blockquote></details>

This parameter is sent in the legacy system in delete category request, I don't know when it's not (there's no mention of it in the PRD), but it affects `directSubCategoriesCount` in the get category response. So, I assume that categories were deleted not properly before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/379)*

**Comment by amirch1** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/379#-L4VkbttB6VKwHF6bLu7:-L4f1JXNIJwAD87wxJlW:b57catd) (no related file):*
>  KMCNG-1280
What is missing is this: After you delete all sub-categories and clicks "Save", the category stays in Sub-categories view while the left side navigation don't have this section (see screen capture). In such case - please navigate back to the metadata section of the category. 


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/379)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/379#-L4VkbttB6VKwHF6bLu7:-L4f3rdPU_J7Iw38RppT:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

>  KMCNG-1280
What is missing is this: After you delete all sub-categories and clicks "Save", the category stays in Sub-categories view while the left side navigation don't have this section (see screen capture). In such case - please navigate back to the metadata section of the category. 


</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/379)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/379#-:-L4f45dVovgp6qFJEj_D:bnfp4nl)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/379#-:-L4kgtrbvREUfK0fnlzL:bnfp4nl)*

**Pull request merged**
