### PR TITLE
Bulk upload

### PR DESCRIPTION
**Pull request by diamond-darrell**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/213)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 74 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KuyTmTcnUZORO35zj5e:-Kv7UF7HgXc5TCHrrt3t:b-5ddv9a) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5714c3874da36f4ca766344092385d6f0145f59/src/shared/kmc-shell/providers/browser.service.ts#L74)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

it seems there's no other way to download a file from a URL. I tried to just pass the URL to `a.href` attribute, but it works strangely: for safari and ff - opens file content in a new tab, for chrome - downloads the file, but with a name that contains the URL to the file with txt extension. 
This way works fine, except I can't test it in IE, since I don't have one
</blockquote></details>

Tested on Edge and IE. Edge works fine, IE11 throws an error and fails. We need to handle IE all the way back to IE11 unfortunately.
You can use browserstack to check IE11: https://www.browserstack.com user: itay.kinnrot@kaltura.com pass: Aa12345

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 74 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KuyTmTcnUZORO35zj5e:-Kv7VmsVskq6qfTmVOJV:b2xqejb) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5714c3874da36f4ca766344092385d6f0145f59/src/shared/kmc-shell/providers/browser.service.ts#L74)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Tested on Edge and IE. Edge works fine, IE11 throws an error and fails. We need to handle IE all the way back to IE11 unfortunately.
You can use browserstack to check IE11: https://www.browserstack.com user: itay.kinnrot@kaltura.com pass: Aa12345
</blockquote></details>

You can check this link: http://www.muazkhan.com/2012/10/save-files-on-disk-using-javascript-or.html for IE11 support

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 74 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KuyTmTcnUZORO35zj5e:-Kv7VxSmGu9C5u7KxTZg:bfbeajw) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5714c3874da36f4ca766344092385d6f0145f59/src/shared/kmc-shell/providers/browser.service.ts#L74)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

You can check this link: http://www.muazkhan.com/2012/10/save-files-on-disk-using-javascript-or.html for IE11 support
</blockquote></details>

Thanks! I will try to fix it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: 39 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 74 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KuyTmTcnUZORO35zj5e:-Kv7xH3-Cu6S0DNtHBR6:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5714c3874da36f4ca766344092385d6f0145f59/src/shared/kmc-shell/providers/browser.service.ts#L74)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Thanks! I will try to fix it
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by amirch1** [comment]
Reviewed 39 of 40 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 189 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KvM-WkCiGHV8fb7Y5Iz:-KvM-WkCiGHV8fb7Y5J-:b-dunyg6) ([raw file](https://github.com/kaltura/kmc-ng/blob/0908957de36b94c52cf957703d4e568829971f5f/src/shared/kmc-shell/providers/browser.service.ts#L189)):*
> ```XML
>     let file;
>     if (typeof data === 'string' && /^(?:\w+:)?\/\/([^\s\.]+\.\S{2}|localhost[\:?\d]*)\S*$/.test(data)) { // if data is url
>       file = this._downloadContent(data);
> ```

after additional discussion - we decided not to invoke direct download in IE11 but to simply open the file 
URL in a new tab and let the browser decide if to download or display the file: https://github.com/kaltura/kmc-ng/blob/c9b8d825f2ae0c4e6a2fb593e3272c87aa1642d9/src/shared/kmc-shell/providers/browser.service.ts#L189-L192

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 189 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KvM-WkCiGHV8fb7Y5Iz:-KvQuWQNTD5aBDnWNiij:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0908957de36b94c52cf957703d4e568829971f5f/src/shared/kmc-shell/providers/browser.service.ts#L189)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

after additional discussion - we decided not to invoke direct download in IE11 but to simply open the file 
URL in a new tab and let the browser decide if to download or display the file: https://github.com/kaltura/kmc-ng/blob/c9b8d825f2ae0c4e6a2fb593e3272c87aa1642d9/src/shared/kmc-shell/providers/browser.service.ts#L189-L192
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 35 of 40 files at r1, 4 of 5 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwiVIp_X-E1iJe9scrd:-KwiVIp_X-E1iJe9scre:b7zzfdq) (no related file):*
We had a glitch in the chunk upload which caused infinite upload as shown below. I fixed it on master.



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwigDSd1vvfpZlEaYYS:-KwigDSd1vvfpZlEaYYT:boo368e) (no related file):*
ui glitch



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx2CxEkbP0n9I_nKznk:-Kx2CxEkbP0n9I_nKznl:b-3ngqao) (no related file):*
when uploading a bulk file while you are already in the bulk upload table, the table doesn't reflect the added item.

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KwifqAezn1PMc_Pcuq5:brsb4ax) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
> ```XML
>   ],
>   exports: [],
>   providers: [BulkLogStoreService, BulkLogRefineFiltersProviderService]
> ```

is `BulkLogRefineFiltersProviderService` service singleton on purpose?

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 18 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24eAy05kYkMXmFedO:-Kx24eAy05kYkMXmFedP:bo83ug3) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L18)):*
> ```HTML
>           <div #refineBtn class="kRefine">
>             <i class="kIconfilter"></i>
>             <span>{{'applications.content.entries.refine' | translate}}</span>
> ```

wrong namespace of the token `content.entries`

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 29 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24i4aN-cMaTukrsGP:-Kx24i4aN-cMaTukrsGQ:b-kamme7) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L29)):*
> ```HTML
>                 (click)="_reload()"></button>
>       </div>
>       <kTags [title]="'applications.content.filters.activeFilters' | translate"
> ```

wrong namespace of the token `content.filters`... fix other places as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwigDSd1vvfpZlEaYYS:-Kx7tJvzMLgQG_RMkWVV:bw40bhr) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

ui glitch



</blockquote></details>

According to latest design, there're no filters, so I will remove it at all 

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-Kx80BHfUPiqq5OE-ktp:bnxmase) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is `BulkLogRefineFiltersProviderService` service singleton on purpose?
</blockquote></details>

I think it was copy-paste from somewhere else, but since we don't have filters here I'll remove it
OK

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 18 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24eAy05kYkMXmFedO:-Kx808jTAPq5C4d-z4q7:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L18)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

wrong namespace of the token `content.entries`
</blockquote></details>

OK

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 29 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24i4aN-cMaTukrsGP:-Kx80WFYt-uFf0287tZp:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

wrong namespace of the token `content.filters`... fix other places as well.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwiVIp_X-E1iJe9scrd:-Kx80eDSFJKo_dl0O_hJ:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

We had a glitch in the chunk upload which caused infinite upload as shown below. I fixed it on master.





</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: 23 of 31 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx2CxEkbP0n9I_nKznk:-Kx8rOWfdrQJDFuylGfy:b-bzykgy) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

when uploading a bulk file while you are already in the bulk upload table, the table doesn't reflect the added item.
</blockquote></details>

How can I force to update the bulk log list from bulk-upload-menu or bulk-upload.service? I don't think it's a good idea to put dependency of bulk-log-store in them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: 23 of 31 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KxC_LBxBfPBRNT8ESt9:b-9dd3j8) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I think it was copy-paste from somewhere else, but since we don't have filters here I'll remove it
OK
</blockquote></details>

+@esakal Now it's relevant again - I made it a singleton because refine filters in entries also provided in the module, I thought it's the right approach

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 18 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24eAy05kYkMXmFedO:-KxC_hMrthF3G_BnWCkg:b-pzrx9p) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L18)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

+@esakal it's the same text as in the entries, I considered using the same translation keys to prevent duplication of the translation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 5 files at r3, 4 of 12 files at r4, 3 of 17 files at r5, 14 of 14 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwigDSd1vvfpZlEaYYS:-KxCl8vkW0zXWsnUyc8j:b-4agnn1) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

According to latest design, there're no filters, so I will remove it at all 
</blockquote></details>

hmm... I can't reproduce it, is it still there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 1 of 17 files at r5, 14 of 14 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx2CxEkbP0n9I_nKznk:-KxBmN6LmhUkMhzui57u:b-abruun) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

How can I force to update the bulk log list from bulk-upload-menu or bulk-upload.service? I don't think it's a good idea to put dependency of bulk-log-store in them.
</blockquote></details>

let's use the new app events system

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KxBmwfKuVrBrOvNgLAA:bwe1hos) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal Now it's relevant again - I made it a singleton because refine filters in entries also provided in the module, I thought it's the right approach
</blockquote></details>

I just understood that `BulkLogStoreService` purpose is to provide information to the log table but since it query information from the server it should be provided by the component and not singleton as-well. what do you think?

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html, line 18 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx24eAy05kYkMXmFedO:-KxH7XDum4mEKwRW6ZmC:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.html#L18)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal it's the same text as in the entries, I considered using the same translation keys to prevent duplication of the translation
</blockquote></details>

OK

---

*[src/applications/content-bulk-log-app/pipes/bulk-log-status-icon.pipe.ts, line 1 at r7](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KxH6sIqkmH9PQhFFtok:-KxH6sIqkmH9PQhFFtol:bnxtokw) ([raw file](https://github.com/kaltura/kmc-ng/blob/9ec4db84ac9ad92caacbabfa5f28aea44f4e09cd/src/applications/content-bulk-log-app/pipes/bulk-log-status-icon.pipe.ts#L1)):*
> ```XML
> import { Pipe, PipeTransform } from '@angular/core';
> ```

I'm confused, just checking, didnt you and Amir said that they removed the icon?

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 189 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KvM-WkCiGHV8fb7Y5Iz:-KxH70HhNCXzuTRSzok9:bo9yzpa) ([raw file](https://github.com/kaltura/kmc-ng/blob/0908957de36b94c52cf957703d4e568829971f5f/src/shared/kmc-shell/providers/browser.service.ts#L189)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

was it resolved? where was it fixed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-Kx2CxEkbP0n9I_nKznk:-KxH7xUNZuEFSB6CMdWd:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

let's use the new app events system
</blockquote></details>

OK

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KxH9SV-Ia-2himnYAy1:b-qkbccr) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
> BulkLogStoreService
It also has to be injected to the list and the filter components

---

*[src/applications/content-bulk-log-app/pipes/bulk-log-status-icon.pipe.ts, line 1 at r7](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KxH6sIqkmH9PQhFFtok:-KxH8EOX7x_TU5I5qWfI:bcdq7ud) ([raw file](https://github.com/kaltura/kmc-ng/blob/9ec4db84ac9ad92caacbabfa5f28aea44f4e09cd/src/applications/content-bulk-log-app/pipes/bulk-log-status-icon.pipe.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm confused, just checking, didnt you and Amir said that they removed the icon?
</blockquote></details>

This is status icon, they have removed type icons


---

*[src/shared/kmc-shell/providers/browser.service.ts, line 189 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KvM-WkCiGHV8fb7Y5Iz:-KxH8rood5YT-5V9uuBm:b5ri1zc) ([raw file](https://github.com/kaltura/kmc-ng/blob/0908957de36b94c52cf957703d4e568829971f5f/src/shared/kmc-shell/providers/browser.service.ts#L189)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

was it resolved? where was it fixed?
</blockquote></details>

Probably reviewable glitch, this fix is [here](https://github.com/kaltura/kmc-ng/blob/bulk-upload/src/shared/kmc-shell/providers/browser.service.ts#L193-L195)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Reviewed 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts, line 44 at r8](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KxHEP5_Z_j8SupaPqiJ:-KxHEP5_Z_j8SupaPqiK:b-8cvl5v) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c9547177e270519c5a4c2f2ca817c830ec4e711/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts#L44)):*
> ```XML
>     appEvents.event(BulkLogUploadingStartedEvent)
>       .cancelOnDestroy(this)
>       .delay(2000) // TODO [kmcng] Clean up after tests
> ```

+@esakal please check this on your machine. It seems that after bulk file was uploaded, need to wait some time to update the list because if I do it immediately - the server doesn't return newly added item

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KxI5bBMBD-QxWJ4FPpN:b-lclzgr) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

> BulkLogStoreService
It also has to be injected to the list and the filter components
</blockquote></details>

as discussed please move it to the relevant component provider

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by diamond-darrell** [comment]
Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/applications/content-bulk-log-app/content-bulk-log-app.module.ts, line 74 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/213#-KwifqAezn1PMc_Pcuq4:-KxI8xoJPExAG5ck6t0M:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/d280838e5ab509047864c2a5c16193219b17c416/src/applications/content-bulk-log-app/content-bulk-log-app.module.ts#L74)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

as discussed please move it to the relevant component provider
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/213)*

**Pull request merged**
