### PR TITLE
KMCNG-568 - Entry Details - General- any field cannot be saved with t…

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
…he '<' or '>' characters

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/251)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/251#-Kylp4Y3ENWnMTxvOxTO:-Kylp4Y3ENWnMTxvOxTP:bbwf4a8) (no related file):*
We should better understand when it happens and provide more comprehensive solution. Let's close this PR for now and handle it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/251)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/251)*

**Comment by konstantin-stepanets** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/251#-Kylp4Y3ENWnMTxvOxTO:-KyoqWD72WqzL4c2yaXs:begspad) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

We should better understand when it happens and provide more comprehensive solution. Let's close this PR for now and handle it later.
</blockquote></details>

I agree (I have checked a set of the fileds and errors in responses and just tried to combine them semantically)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/251)*

**Comment by esakal** [comment]
cannot reproduce original bug

**Pull request closed without merging**
