### PR TITLE
fix: KMCNG-982 - Related Files- Preview option downloads the file rat…

### PR DESCRIPTION
**Pull request by benstov**
…her than providing a preview

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/452)

### CODE REVIEW

**Comment by benstov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-related/entry-related.component.ts, line 101 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/452#-L7J-xRBnFgi7A1xZ-mJ:-L7J-xRCZIPFW5k5kDpY:bjpatx7) ([raw file](https://github.com/kaltura/kmc-ng/blob/4b35912178df98eedf85494050a7d8ed7cd4f6b9/src/applications/content-entries-app/entry/entry-related/entry-related.component.ts#L101)):*
> ```XML
> 				break;
> 			case "preview":
> 				this._widgetService.previewFile(this._currentFile);
> ```

@amirch1 asked me not to remove the function, only to hide the menu item.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/452)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/452)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/452#-:-L7JZNjO7IaA148H-pUX:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/452)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/452#-:-L7ObAzIhe72yQLy0_TL:bnfp4nl)*

**Pull request merged**
