### PR TITLE
KMCNG-941

### PR DESCRIPTION
**Pull request by diamond-darrell**
> review along with [this](https://github.com/kaltura/kaltura-ng/pull/82) branch in kaltura-ng
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-941

**What is the new behavior?**
hide menu on scroll

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/382)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-L4WT4a9tZDLoFW9ggoK:-L4WT4a9tZDLoFW9ggoL:beccliu) (no related file):*
+@amirch1 please provide your insights

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html, line 3 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-L4eWsKr6iiyaIWV9-6X:-L4eWsKr6iiyaIWV9-6Y:b-p7gx9q) ([raw file](https://github.com/kaltura/kmc-ng/blob/33c271bdb92f2ecfeb3644562c87214138c5fdcb/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html#L3)):*
> ```HTML
> <div class="kBulkActions">
>   <button pButton icon="kIcontrash" class="kButtonDanger kBulkDeleteBtn" (click)="deleteEntries()"></button>
>   <button #menuToggle class="kButtonDefault kBulkActionsBtn" icon="kIcondropdown_arrow_bottom" iconPos="right" pButton label="{{'applications.content.entries.bulkActions' | translate}}" (click)="menu.toggle($event)"></button>
> ```

seems redundant - is it used anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html, line 3 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-L4eWsKr6iiyaIWV9-6X:-L4eXK3Wi4fIBTjwVxOU:b-c43n1e) ([raw file](https://github.com/kaltura/kmc-ng/blob/33c271bdb92f2ecfeb3644562c87214138c5fdcb/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html#L3)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

seems redundant - is it used anywhere?
</blockquote></details>

sorry, I don't get it,  what is redundant here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html, line 3 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-L4eWsKr6iiyaIWV9-6X:-L4eYleF2vlKVfSgVqpk:b-rcvoc2) ([raw file](https://github.com/kaltura/kmc-ng/blob/33c271bdb92f2ecfeb3644562c87214138c5fdcb/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html#L3)):*
>   <button #menuToggle class="kButtonDefault kBulkActionsBtn" icon="kIcond
the #menuToggle  identifier. Is it used anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html, line 3 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-L4eWsKr6iiyaIWV9-6X:-L4eZ6pt_pNLBTYvMvfv:b-ud0sa4) ([raw file](https://github.com/kaltura/kmc-ng/blob/33c271bdb92f2ecfeb3644562c87214138c5fdcb/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html#L3)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

>   <button #menuToggle class="kButtonDefault kBulkActionsBtn" icon="kIcond
the #menuToggle  identifier. Is it used anywhere?
</blockquote></details>

oh, that one, you are right, it's redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-:-L4eZhBQ5vhI_uT6jjpN:bnfp4nl)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/382#-:-L4koMZEjcsSjLiM_p2H:bnfp4nl)*

**Pull request merged**
