### PR TITLE
KMCNG-752

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-752

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell and @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFqVvgM-cglWhIcvbSX:bmtfm1z) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
> ```XML
>       .subscribe(
>         () => {
>             const selectedEntries = this._entriesList.selectedEntries || [];
> ```

I see that you filter our the deleted record instead of clearing all selections but I think you should call `this._entriesList.clearSelection();` as we usually clear selection before the reload, does it conflict with the business requirements?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell and @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFqWfYpBhk-Pam_SyCE:bs488bm) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I see that you filter our the deleted record instead of clearing all selections but I think you should call `this._entriesList.clearSelection();` as we usually clear selection before the reload, does it conflict with the business requirements?
</blockquote></details>

Nope, please read the comments to the ticket, Lior wants the selection to remain and update the selected entries accordingly

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by esakal** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @esakal and @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFqZTClDOtwCJygToBM:bqi6h8w) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

Nope, please read the comments to the ticket, Lior wants the selection to remain and update the selected entries accordingly
</blockquote></details>

I see, please review my comment in the ticket.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell and @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFq_zxO5jzWPIdTx7Zs:bb1qf5u) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I see, please review my comment in the ticket.
</blockquote></details>

so, just clear the selection, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by esakal** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @esakal and @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFqj0g77FmgV7hNAZZp:b-jp377f) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

so, just clear the selection, right?
</blockquote></details>

correct

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amirch1)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Comment by diamond-darrell** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amirch1)

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 151 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/677#-LFqVvgM-cglWhIcvbSW:-LFqlGD_B54twaLdxngd:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/1f56cc334db196f6e4b5d0f04585218e3531be13/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L151)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

correct
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/677)*

**Pull request merged**
