### PR TITLE
prevent reset of sort filters

### PR DESCRIPTION
**Pull request by esakal**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/352)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/352#-L3XDZMsBxh7dmrI36S6:-L3XDZMtaF-6FkD3rixq:b-rbyi15) (no related file):*
+@diamond-darrell does drop folder have server sorting support?

because I don't see it in the drop folders filters struct. Is it ok?

Ignore the following code for now:
```
protected _preFiltersReset(updates: Partial<DropFoldersFilters>): Partial<DropFoldersFilters> {
    delete updates.sortBy;
    delete updates.sortDirection;
    return updates;
}```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/352)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/352#-L3XDZMsBxh7dmrI36S6:-L3XIJO612bIrIT6kIeX:b-1xh4bf) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@diamond-darrell does drop folder have server sorting support?

because I don't see it in the drop folders filters struct. Is it ok?

Ignore the following code for now:
```
protected _preFiltersReset(updates: Partial<DropFoldersFilters>): Partial<DropFoldersFilters> {
    delete updates.sortBy;
    delete updates.sortDirection;
    return updates;
}```
</blockquote></details>

It is OK, according to the PRD and the legacy itself, the sorting should be local
![✂-1](https://files.reviewableusercontent.io/images/reviewable/4395889/LARa6wSscBQ8sLwJJRujv72O.png)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/352)*
<!-- Sent from Reviewable.io -->

**Comment by diamond-darrell** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/352#-:-L3XIebshI2XFcbQs3U1:bnfp4nl)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/352#-:-L3XMKSZUt7KgaOPXnx5:bnfp4nl)*

**Pull request merged**
