### PR TITLE
KMCNG-1796

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1796

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/727#-LFkhuO91Wp7EQbHFIsE:-LFkhuOA3kVhpnt66sd-:boctn5a) (no related file):*
Once the user checks the checkbox - the author name field becomes mandatory and should be marked with a "*" and pass a "required" validation before submitting the form. So we have a conditional validation here that should be handled.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @amirch1 and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/727#-LFkhuO91Wp7EQbHFIsE:-LFkkGjZBF14T34rIx23:b-896fix) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Once the user checks the checkbox - the author name field becomes mandatory and should be marked with a "*" and pass a "required" validation before submitting the form. So we have a conditional validation here that should be handled.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)*

**Comment by esakal** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @amirch1 and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/727#-LFlSv9KC58zObkwhiFi:-LFlSv9KC58zObkwhiFj:bstofgx) (no related file):*
:lgtm: 
code confirmed, 

+@amirch1  please check at runtime and merge if possible.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @amirch1 and @diamond-darrell)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)*

**Comment by esakal** [comment]
Dismissed @amirch1 and @diamond-darrell from a discussion.
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/727#-LFkhuO91Wp7EQbHFIsE:-LFlTjS39-rKov6hOktW:bq8w3pr) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not relevant

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/727)*

**Pull request merged**
