### PR TITLE
Drop folders refactoring

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/300)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 36 files at r1, 1 of 35 files at r3, 38 of 47 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 22 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tEIodoIAZp2R0aGva:-L0tEIodoIAZp2R0aGvb:bv3yyb2) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L22)):*
> ```XML
>   templateUrl: './drop-folders-list.component.html',
>   styleUrls: ['./drop-folders-list.component.scss'],
>   providers: [FolderFileStatusPipe]
> ```

you already provide it from the module which is where it should be. Is this a cleanup



---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 45 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tFUZSTts6w4Fi3kXZ:-L0tFUZSTts6w4Fi3kX_:b-llrjck) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L45)):*
> ```XML
>     this._prepare();
> 
>     this._dropFoldersStore.dropFolders.state$
> ```

1. you are missing `cancelOnDestroy`
2. also in other views we don't show this status in the list, we show it in the table component if I remember correctly

---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 83 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tFuKYqPrCnKcNDFvz:-L0tFuKYqPrCnKcNDFw-:b-kipcwj) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L83)):*
> ```XML
>         'pageSize',
>         'pageIndex',
>         'freeText'
> ```

you are missing handling of sort (by/order) 

---

*[src/applications/content-drop-folders-app/statuses-filter/statuses-filter.component.ts, line 1 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tMuE_MfUOcjhqdkTp:-L0tMuE_MfUOcjhqdkTq:b-sksbhc) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/statuses-filter/statuses-filter.component.ts#L1)):*
> ```XML
> import { AfterViewInit, Component, EventEmitter, OnDestroy, OnInit, Output } from '@angular/core';
> ```

where are we using this component?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by diamond-darrell** [comment]
Review status: 29 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 22 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tEIodoIAZp2R0aGva:-L0tP0ulwmPxxf8JLBlg:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L22)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you already provide it from the module which is where it should be. Is this a cleanup



</blockquote></details>

OK

---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 45 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tFUZSTts6w4Fi3kXZ:-L0tQhnNm-xSs3ySdQjZ:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L45)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

1. you are missing `cancelOnDestroy`
2. also in other views we don't show this status in the list, we show it in the table component if I remember correctly
</blockquote></details>

OK

---

*[src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts, line 83 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tFuKYqPrCnKcNDFvz:-L0tOSaJBdGTPuR50sq0:b-rjn3gu) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts#L83)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you are missing handling of sort (by/order) 
</blockquote></details>

It's by design, the PRD says that sorting should be done locally


---

*[src/applications/content-drop-folders-app/statuses-filter/statuses-filter.component.ts, line 1 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L0tMuE_MfUOcjhqdkTp:-L0tOrfcAFijhy6rXUcI:b-mv7rrp) ([raw file](https://github.com/kaltura/kmc-ng/blob/2b3e7210fac9d4194d317897b374466d491d940f/src/applications/content-drop-folders-app/statuses-filter/statuses-filter.component.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

where are we using this component?
</blockquote></details>

it's a leftover, will remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by esakal** [comment]
Reviewed 1 of 47 files at r4, 2 of 3 files at r5, 5 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-:-L0tUJjqnRyoWO9DzIu1:bnfp4nl)*

**Comment by amirch1** [comment]
> drop-folders-refactoring
seems that we are missing the bulk actions interface for delete operation (described in the PRD). Also, when deleting a single file using the actions menu - the confirmation message is a bulk delete confirmation message. 
PRD is here: https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/234162917/Drop+Folders. Please check specs under: "bulk actions - delete"

---

Reviewed 3 of 36 files at r1, 1 of 35 files at r3, 28 of 47 files at r4, 2 of 3 files at r5, 4 of 7 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-:-L16AtnWvIWHRI26KXnk:buk82hy)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L16BYWoqvL-Qc1neVW7:-L16BYWoqvL-Qc1neVW8:b-y45drs) (no related file):*
drop-folders-refactoring
seems that we are missing the bulk actions interface for delete operation (described in the PRD). Also, when deleting a single file using the actions menu - the confirmation message is a bulk delete confirmation message.
PRD is here: https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/234162917/Drop+Folders. Please check specs under: "bulk actions - delete"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by diamond-darrell** [comment]
Review status: 31 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L16BYWoqvL-Qc1neVW7:-L1BnlVmHddGWhRVj-JQ:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

drop-folders-refactoring
seems that we are missing the bulk actions interface for delete operation (described in the PRD). Also, when deleting a single file using the actions menu - the confirmation message is a bulk delete confirmation message.
PRD is here: https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/234162917/Drop+Folders. Please check specs under: "bulk actions - delete"
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by esakal** [comment]
Reviewed 1 of 47 files at r4, 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-L16BYWoqvL-Qc1neVW7:-L1GgByedFzEE3vCcnIR:b32wtd) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/300#-:-L1GkzMyFsZdV4zMAmZS:bnfp4nl)*

**Pull request merged**
