### PR TITLE
feat: add Change-log

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/218)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/changelog/changelog.component.ts, line 21 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/218#-KvRyF4RVA9DMKWYhv5P:-KvRyF4RVA9DMKWYhv5Q:b-d5gwj3) ([raw file](https://github.com/kaltura/kmc-ng/blob/e905dd5e022a7e1a7d2c4f32336e3e9a76564693/src/app/components/changelog/changelog.component.ts#L21)):*
> ```XML
> 
>   ngOnInit() {
>     this._changelogSeen = !!this._browserService.getFromLocalStorage(this._changelogCacheToken);
> ```

you need to use the current app version (we added it to the `app-config`) and compare it with the value from the local storage

---

*[src/app/components/changelog/changelog.component.ts, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/218#-KvRyRWzZAyK3UN6ACdc:-KvRyRWzZAyK3UN6ACdd:b-iilukz) ([raw file](https://github.com/kaltura/kmc-ng/blob/e905dd5e022a7e1a7d2c4f32336e3e9a76564693/src/app/components/changelog/changelog.component.ts#L29)):*
> ```XML
>   public _openChangelog(): void {
>     this._changelogSeen = true;
>     this._browserService.setInLocalStorage(this._changelogCacheToken, this._changelogSeen);
> ```

you need to store the current app version here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/218)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/changelog/changelog.component.ts, line 21 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/218#-KvRyF4RVA9DMKWYhv5P:-KvS-h1yix8Dq3BUde8b:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e905dd5e022a7e1a7d2c4f32336e3e9a76564693/src/app/components/changelog/changelog.component.ts#L21)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you need to use the current app version (we added it to the `app-config`) and compare it with the value from the local storage
</blockquote></details>

OK

---

*[src/app/components/changelog/changelog.component.ts, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/218#-KvRyRWzZAyK3UN6ACdc:-KvS-u2Fx_5uDkrReynh:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e905dd5e022a7e1a7d2c4f32336e3e9a76564693/src/app/components/changelog/changelog.component.ts#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you need to store the current app version here
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/218)*

**Comment by esakal** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/218)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/218)*

**Pull request merged**
