### PR TITLE
KMCNG-892

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/321)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/321#-L1fkmhHMo6rnkLkGjHk:-L1fkmhHMo6rnkLkGjHl:b-64r0fj) (no related file):*
Pending to product feedback about this bug [jira ticket](https://kaltura.atlassian.net/browse/KMCNG-892)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/321)*

**Comment by esakal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 127 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/321#-L1g4ib9xxJlkz0YwaxV:-L1g4ib9xxJlkz0YwaxW:blz5bbd) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7896401c4bb87c19a3a21c25ae8f9009da9ef9d/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L127)):*
> ```XML
>             id: trackedFile.id,
>             entryId: fileData.entryId,
>             fileName: (<NewEntryUploadFile>fileData).entryName || fileData.getFileName(),
> ```

do you remember upload list tracks also flavor uploads? does your code handle it as-well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/321)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 127 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/321#-L1g4ib9xxJlkz0YwaxV:-L1puw0sk857kziFjNn6:bnmt34o) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7896401c4bb87c19a3a21c25ae8f9009da9ef9d/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L127)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

do you remember upload list tracks also flavor uploads? does your code handle it as-well?
</blockquote></details>

We can't rename a flavor name during upload, so I think it's not relevant for the flavors upload

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/321)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/321#-L1fkmhHMo6rnkLkGjHk:-L1pv74xGJ6430LzgA-6:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Pending to product feedback about this bug [jira ticket](https://kaltura.atlassian.net/browse/KMCNG-892)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/321)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 127 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/321#-L1g4ib9xxJlkz0YwaxV:-L2P3f_yGfh6ISBDbUOv:bc42tco) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7896401c4bb87c19a3a21c25ae8f9009da9ef9d/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L127)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

We can't rename a flavor name during upload, so I think it's not relevant for the flavors upload
</blockquote></details>

you are right but this file handles both of them so you cannot assume fileData is of type `NewEntryUploadFile`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/321)*

**Comment by esakal** [comment]
this change is not needed. the application behave as expected

**Pull request closed without merging**
