### PR TITLE
Fix categories bulk actions relied on entitlement settings

### PR DESCRIPTION
**Pull request by diamond-darrell**
* add privacyContext to categories response profile
* add validation step for privacy settings, listing settings and contribution policy settings bulk actions
* set none selected radio-buttons as default and disable button until user selects some option

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1407
If a user selects categories without entitlement to update privacy settings, listing settings, and contribution policy settings the server returns an error. There's missing validation step

**What is the new behavior?**

- add privacyContext to categories response profile
- add validation step for privacy settings, listing settings, and contribution policy settings bulk actions
- set none selected radio-buttons as default and disable the button until a user selects some option

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/411)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 75 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6jlu0_dOQk2OI1ayR5:-L6jlu0_dOQk2OI1ayR6:b-fj5cn) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L75)):*
> ```XML
>         accept: () => acceptCallback()
>       });
>     }
> ```

+@amirch1 I think he is missing here the else part if all selected categories has privacy context, something like:
```
else {
   acceptCallback();
}
```

Can you check this out?

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 168 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6jmKPL9x80MlBfej9R:-L6jmKPL9x80MlBfej9S:bu2o08k) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L168)):*
> ```XML
> 
>     this._mapPrivacyContext(() => {
>       if (this.selectedCategories.length) {
> ```

we should consider moving the selectedCategories existence check outside because there is not point executing `_mapPrivacyContext`  in such a scenario

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 184 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6jmXnRYRxWjg2-eYEM:-L6jmXnRYRxWjg2-eYEN:b-2guby3) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L184)):*
> ```XML
> 
>     this._mapPrivacyContext(() => {
>       if (this.selectedCategories.length) {
> ```

same here

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 193 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6jmZMcDx4V6DnVHbLM:-L6jmZMcDx4V6DnVHbLN:b-2guby3) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L193)):*
> ```XML
>   onChangeContributionPolicyChanged(policyType: KalturaContributionPolicyType): void {
>     this._mapPrivacyContext(() => {
>       if (this.selectedCategories.length) {
> ```

same here

---

*[src/i18n/en.json, line 472 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6jnSJcgVOLRt0VwY9_:-L6jnSJcgVOLRt0VwY9a:b3yq6g) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/i18n/en.json#L472)):*
> ```JSON
>           "changeOwnerLabel": "Set a new owner for the selected categories",
>           "error": "Categories update failed",
>           "noPrivacyContext": "Some of the selected categories don't have entitlement settings and therefore will not be updated by this action.\n\nTo add entitlements to categories, go to the Integration Settings page under the Settings tab."
> ```

+@amirch1 just to verify (since I hope Stas is resting today and not monitoring his work email :) ) - according to the code it seems that we still send those categories. Can you confirm with the legacy that it sends also all the selected categories and that the filtering is done on the server?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/411)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 68 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/411#-L6kBV82VP9q1v-NC-Jo:-L6kBV82VP9q1v-NC-Jp:b6nccz9) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L68)):*
> ```XML
>   private _mapPrivacyContext(acceptCallback: () => void): void {
>     const selectedCategoriesLength = this.selectedCategories.length;
>     this.selectedCategories = [...this.selectedCategories.filter(category => !!category.privacyContext)];
> ```

the name of the method and its content are misleading. It looks like a method that 'decide' wether to warn the user but it actually changes the `this.selectedCategories` - please split it into two functions, something like `fixSelectedCategories` and `beforeExecute`.... feel free to choose your own names :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/411)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 68 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6kBV82VP9q1v-NC-Jo:-L6pAJjN7OS1e3_r7Nnl:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L68)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the name of the method and its content are misleading. It looks like a method that 'decide' wether to warn the user but it actually changes the `this.selectedCategories` - please split it into two functions, something like `fixSelectedCategories` and `beforeExecute`.... feel free to choose your own names :)
</blockquote></details>

OK

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 75 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6jlu0_dOQk2OI1ayR5:-L6pAJ3V7lBnVzZyzKBB:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L75)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 I think he is missing here the else part if all selected categories has privacy context, something like:
```
else {
   acceptCallback();
}
```

Can you check this out?
</blockquote></details>

OK

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 168 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6jmKPL9x80MlBfej9R:-L6pAUIYB1WBlEP1avWp:b-c5z94c) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L168)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we should consider moving the selectedCategories existence check outside because there is not point executing `_mapPrivacyContext`  in such a scenario
</blockquote></details>

I think it's relevant here because we can filter out all of the selected entries, but we still need to show the warning, so instead making several checkouts on the selected categories length I'm making it only here

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 184 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6jmXnRYRxWjg2-eYEM:-L6pArwI3qfbrI9OR1Am:b-xxgvm3) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L184)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

same here
</blockquote></details>

see reply above

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 193 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6jmZMcDx4V6DnVHbLM:-L6pAtiS2Ah72sEMjw27:bpyh5w7) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L193)):*
> see reply above

---

*[src/i18n/en.json, line 472 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411#-L6jnSJcgVOLRt0VwY9_:-L6pAvuW2QSNZKnmaPMb:b-wqg0ck) ([raw file](https://github.com/kaltura/kmc-ng/blob/be42e2949a844d2eb4032bab15e47e0fd93eddf6/src/i18n/en.json#L472)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 just to verify (since I hope Stas is resting today and not monitoring his work email :) ) - according to the code it seems that we still send those categories. Can you confirm with the legacy that it sends also all the selected categories and that the filtering is done on the server?
</blockquote></details>

we send categories that have privacyContext, if we pass categories without privacyContext the server return error

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/411)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/411)*

**Comment by amirch1** [comment]
Reviewed 5 of 9 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/411)*

**Pull request merged**
