### PR TITLE
feat: Change account

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/203)

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @benstov,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by esakal** [comment]
Reviewed 2 of 8 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/app-menu/app-menu.component.html, line 60 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtPsaPPNU7hnD13Mtvr:-KtPsaPPNU7hnD13Mtvs:b-feadum) ([raw file](https://github.com/kaltura/kmc-ng/blob/4cbc20128e4a09016d0f6a913ec7b3ef62c04ce3/src/app/components/app-menu/app-menu.component.html#L60)):*
> ```HTML
> </kPopupWidget>
> 
> <kPopupWidget #changeAccountPopup [popupWidth]="500" [popupHeight]="370" [modal]="true">
> ```

i think the popup is part of `kKMCUserSettings` so you can move it there and then you don't need to expose `onChangeAccount` event and encapsulate all the logic in one place.

---

*[src/app/components/changeAccount/change-account.component.ts, line 46 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtNkJhmlUclw6nxLZzU:-KtNkJhmlUclw6nxLZzV:bu20h1w) ([raw file](https://github.com/kaltura/kmc-ng/blob/4cbc20128e4a09016d0f6a913ec7b3ef62c04ce3/src/app/components/changeAccount/change-account.component.ts#L46)):*
> ```XML
>       .subscribe(partners => {
>           this.partners = partners;
>           console.log(partners);
> ```

minor cleanup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/203)*

**Comment by benstov** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/app-menu/app-menu.component.html, line 60 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtPsaPPNU7hnD13Mtvr:-KtQ6AwS3daywe5xUi8I:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/4cbc20128e4a09016d0f6a913ec7b3ef62c04ce3/src/app/components/app-menu/app-menu.component.html#L60)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

i think the popup is part of `kKMCUserSettings` so you can move it there and then you don't need to expose `onChangeAccount` event and encapsulate all the logic in one place.
</blockquote></details>

Done.

---

*[src/app/components/changeAccount/change-account.component.ts, line 46 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtNkJhmlUclw6nxLZzU:-KtQ6GpQSPPO7zQ5FK5S:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/4cbc20128e4a09016d0f6a913ec7b3ef62c04ce3/src/app/components/changeAccount/change-account.component.ts#L46)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

minor cleanup
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/203)*

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtuGIvm5PSEopD4KWgF:-KtuGIvm5PSEopD4KWgG:bz4cazu) (no related file):*
Let's handle the force reload page as part of this task :)

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 292 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtuF3HqQXC4Dg7tKL9T:-KtuF3HriOx2phgMAwQ-:bo5b115) ([raw file](https://github.com/kaltura/kmc-ng/blob/49c1db16f5be27baa94700599fd21b7e6a7c3fa9/src/shared/kmc-shell/auth/app-authentication.service.ts#L292)):*
> ```XML
>             const ks = result.ks;
>             this.appUser.ks = ks;
>             this.appStorage.setInSessionStorage('auth.login.ks', ks.toString());
> ```

you don't need the `toString`. we use it only with enum as string

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 294 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/203#-KtuF8suJ0F1UeZ0jO2e:-KtuF8suJ0F1UeZ0jO2f:b2vmq5l) ([raw file](https://github.com/kaltura/kmc-ng/blob/49c1db16f5be27baa94700599fd21b7e6a7c3fa9/src/shared/kmc-shell/auth/app-authentication.service.ts#L294)):*
> ```XML
>             this.appStorage.setInSessionStorage('auth.login.ks', ks.toString());
>             location.reload();
>             observer.next();
> ```

we are pulling the developer legs here and tricking them by forcing a reload. remove the observer.next() and observer.complete() from here....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/203)*

**Comment by esakal** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/203)*

**Pull request merged**
