### PR TITLE
KMCNG-456 initialise view upon navigation

### PR DESCRIPTION
**Pull request by Anat123**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/182)

### CODE REVIEW

**Comment by esakal** [comment]
Great Job :)
You did very well and the code seems solid.

Please use reviewable to reply to my review. Ping me tomorrow morning and I will do a quick intro for you and Amishai and Ben. 

For now you can explore it on your own. You can register using your github account. 

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14BYM3fwWRgzs8GlY:-Kr14BYM3fwWRgzs8GlZ:b-syljn6) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L29)):*
> ```HTML
>         <button pButton class="kButtonDefault kRefreshBtn small" type="text" icon="kIconrefresh" [kTooltip]="'applications.content.categories.refresh' | translate"></button>
>       </div>
>       <kCategoriesTable class="kEntriesTable" [categories]="(_categoriesService.categories$ | async)?.items"></kCategoriesTable>
> ```

everytime you use `async` pipe you register to observbale to handle changes.
If you are binding to the same observable multiple times it indicates that you should consider registering to it once in the component.ts and use regular properties for the binding. 

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14cewFnwtztlfvhep:-Kr14cexgKUINbwZUv6y:bm8z0ik) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L37)):*
> ```HTML
>       </div>
>     </div>
>     <p-growl [value]="_msgs"></p-growl>
> ```

+@konstantin-stepanets is working on a growl global infrastructure. you can [review his work here](https://github.com/kaltura/kmc-ng/pull/180). 

Please track this PR (you can add your self as a watcher to that PR) and once it complete use the new infrastructure instead.

For now you can remove the growl and the _msgs from your code

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 18 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr15FNrTRkuNyqnXQMH:-Kr15FNs_lKxRzOKcG_5:b-gjum0r) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.ts#L18)):*
> ```XML
> export class CategoriesListComponent implements OnInit, OnDestroy {
> 
>     public isBusy = false
> ```

use the `_` prefix to indicate as private api (yet available to the template)

---

*[src/applications/content-categories-app/categories/categories-table.component.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr15m7nrzyKsnEFMALm:-Kr15m7nrzyKsnEFMALn:bzd9lvp) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-table.component.ts#L1)):*
> ```XML
> import { Component, Input, Output, EventEmitter, ViewChild, AfterViewInit, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
> ```

I assume you will handle the sorting/pagination and other table actions in the table dedicated PRD so for now I will not review this file.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 24 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16-KEsrlzbr8a_r4l:-Kr16-KEsrlzbr8a_r4m:b-pp3i7a) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L24)):*
> ```XML
> 
> export interface Categories {
>     items: KalturaMediaEntry[],
> ```

you are using the entry type. you should expose the categories type. 

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 31 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16AncPc_o4JRbD7P1:-Kr16AncPc_o4JRbD7P2:b78afo5) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L31)):*
> ```XML
> export class CategoriesService implements OnDestroy {
> 
>     private _categories = new BehaviorSubject({ items: [], totalCount: 0 });
> ```

well you didn't set the generic type to `Categories` in the signature thus it interpreted the array as any[].... 
just declared the generic type as you did for `_state`

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 60 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16VPXMkKaqmyab6RV:-Kr16VPXMkKaqmyab6RW:b7mncc0) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L60)):*
> ```XML
>         }
> 
>         this._categories.next({
> ```

this is actually not needed. I only did it in the training :) the right UX behavior is that we only update the list once we fetch new categories.
You can remove this assignment from here.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 75 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16hJh7au84vWn8mcX:-Kr16hJh7au84vWn8mcY:b-llaqrk) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L75)):*
> ```XML
> 
>                 this._categories.next({
>                     items: <any[]>response.objects,
> ```

avoid using any. Actually you will not need casting here once you will fix the property _categories signature

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 81 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16tQ42V0lUHT-Fj5a:-Kr16tQ42V0lUHT-Fj5b:b4ely3h) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L81)):*
> ```XML
>             error => {
>                 this._categoriesExecuteSubscription = null;
>                 this._state.next({ loading: false, errorMessage: (<Error>error).message || <string>error });
> ```

Can you please reply what you are trying to assign to the errorMessage.

In general, you shouldn't use explicit casting in almost 90% scenarios. If you do use explicit casting it usually indicate on wrong typescript declarations....

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr17Tp-wBrMNX8mCMVa:-Kr17Tp-wBrMNX8mCMVb:bo5qbfo) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L16)):*
> ```XML
>   @Output() onBulkChange = new EventEmitter<{reload: boolean}>();
> 
>   @ViewChild('bulkActionsPopup') public bulkActionsPopup: PopupWidgetComponent;
> ```

do you actually have 'bulkActionsPopup' component? 
If not remove this

In general when you copy from other module, try to copy only things relevant to your active tasks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-:-Kr17j2Cm0cPVkvhHb40:b-k0i6p2)*

**Comment by amirch1** [comment]
Review status: 9 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr5gFD-cIFEKwT_v3CA:-Kr5gFD-cIFEKwT_v3CB:b8suome) (no related file):*
the "Add Category" button is missing margin-left. It should be aligned to the checkboxes.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by Anat123** [comment]
Review status: 9 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14cewFnwtztlfvhep:-Kr5oFiMzqMy5G1mzWz3:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L37)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@konstantin-stepanets is working on a growl global infrastructure. you can [review his work here](https://github.com/kaltura/kmc-ng/pull/180). 

Please track this PR (you can add your self as a watcher to that PR) and once it complete use the new infrastructure instead.

For now you can remove the growl and the _msgs from your code
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 18 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr15FNrTRkuNyqnXQMH:-Kr5a8ip2H5NyLlblU5u:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.ts#L18)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

use the `_` prefix to indicate as private api (yet available to the template)
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-table.component.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr15m7nrzyKsnEFMALm:-Kr5nQ3GchnfCM9oTQvB:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-table.component.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I assume you will handle the sorting/pagination and other table actions in the table dedicated PRD so for now I will not review this file.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 24 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16-KEsrlzbr8a_r4l:-Kr5bN2sYHN8LzxBM4dc:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L24)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you are using the entry type. you should expose the categories type. 
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 31 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16AncPc_o4JRbD7P1:-Kr5bQl8BFdAFdeOq4_C:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L31)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

well you didn't set the generic type to `Categories` in the signature thus it interpreted the array as any[].... 
just declared the generic type as you did for `_state`
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 60 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16VPXMkKaqmyab6RV:-Kr5nmI-KnyfqYTuWLdm:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L60)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is actually not needed. I only did it in the training :) the right UX behavior is that we only update the list once we fetch new categories.
You can remove this assignment from here.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 75 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16hJh7au84vWn8mcX:-Kr5dRa2yRR6UjvihylW:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L75)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

avoid using any. Actually you will not need casting here once you will fix the property _categories signature
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 81 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr16tQ42V0lUHT-Fj5a:-Kr5oQNylIBeZxW2IDBW:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories.service.ts#L81)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Can you please reply what you are trying to assign to the errorMessage.

In general, you shouldn't use explicit casting in almost 90% scenarios. If you do use explicit casting it usually indicate on wrong typescript declarations....
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr17Tp-wBrMNX8mCMVa:-Kr5eMFTJnbGh_gJbcqu:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L16)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

do you actually have 'bulkActionsPopup' component? 
If not remove this

In general when you copy from other module, try to copy only things relevant to your active tasks :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by Anat123** [comment]
Review status: 8 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr5gFD-cIFEKwT_v3CA:-Kr5pIRc3c4fkqEO0edU:b-896fix) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

the "Add Category" button is missing margin-left. It should be aligned to the checkboxes.


</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14BYM3fwWRgzs8GlY:-Kr5vuIV_LlVnU8ou2iB:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

everytime you use `async` pipe you register to observbale to handle changes.
If you are binding to the same observable multiple times it indicates that you should consider registering to it once in the component.ts and use regular properties for the binding. 

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by esakal** [comment]
Reviewed 1 of 5 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14BYM3fwWRgzs8GlY:-Kr6CooIuCptBMTXgJsX:bdqkp4f) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L29)):*
<details><summary><i>Previously, Anat123 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI :) almost there... see my comment below

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 7 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6D3NCuOOCh_vRCZSY:-Kr6D3NCuOOCh_vRCZSZ:b-mjmgih) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L7)):*
> ```HTML
>         <button pButton type="button" label="{{'applications.content.categories.addCategory' | translate}}" class="kButtonBranded kAddCategoryBtn"></button>
>         <span class="kSelectedEntriesNum" *ngIf="_categories?.totalCount">
>           {{_categories?.totalCount}} {{'applications.content.categories.categories' | translate}}
> ```

since you are inside a span that has ngIf you can safely remove the ? sign inside the span

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 21 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6DWzAVQfa8XiYYTVI:-Kr6DWzAVQfa8XiYYTVJ:b-gqb5hx) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.ts#L21)):*
> ```XML
>     public _blockerMessage: AreaBlockerMessage = null;
>     public _selectedCategories: KalturaCategory[] = [];
>     public _categories: Categories;
> ```

You don't need to persist the structure of the categories$. it is an over kill.
usually in component each type of data has its own property:
```
_categories : KalturaCategory[] = [];
_categoriesTotalCount : number? = null;
```

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 29 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6DoUfYrBEeFQ7Ryza:-Kr6DoUfYrBEeFQ7Ryzb:b-x3zbsu) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.ts#L29)):*
> ```XML
>     ngOnInit() {
>         this.categoriesSubscription = this._categoriesService.categories$.subscribe(
>             (x) => {
> ```

try not using vague argument names. use `data` instead for example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6IV8tSDLtRH1tKzjX:-Kr6IV8tSDLtRH1tKzjY:b-xhi505) (no related file):*
+@amirch1 did you reviewed and approved this review? if so don't forget to mark it as LGTM.... thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by amirch1** [comment]
Reviewed 6 of 14 files at r1, 1 of 5 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 16 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr9s6j5fToCgSVmOaR8:-Kr9s6j5fToCgSVmOaR9:b-cgcqjb) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L16)):*
> ```HTML
>         </div> 
>         <div [class.kHidden]="_selectedCategories.length" class="kFilters">
>           <input type="text" pInputText class="kSearchInput" placeholder="{{'applications.content.categories.search' | translate}}">
> ```

Seems that the search input field is missing the magnifying glass icon causing the text to appear too far to the right. Please add the icon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by Anat123** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 7 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6D3NCuOOCh_vRCZSY:-Kr9ojNTYBj3SJc3PvgG:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L7)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

since you are inside a span that has ngIf you can safely remove the ? sign inside the span
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 16 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr9s6j5fToCgSVmOaR8:-Kr9thfbdFPP8Lq3VHS6:bfj8yr1) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L16)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Seems that the search input field is missing the magnifying glass icon causing the text to appear too far to the right. Please add the icon
</blockquote></details>

I think we should consider moving the file location magnifier.png.
the current position is under content-entries-app/styles

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 21 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6DWzAVQfa8XiYYTVI:-Kr9rteoKTmBS1KSI6Wc:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.ts#L21)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

You don't need to persist the structure of the categories$. it is an over kill.
usually in component each type of data has its own property:
```
_categories : KalturaCategory[] = [];
_categoriesTotalCount : number? = null;
```
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list.component.ts, line 29 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr6DoUfYrBEeFQ7Ryza:-Kr9s1IM6p5qhDKRlEOt:b-glmvjs) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.ts#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

try not using vague argument names. use `data` instead for example
</blockquote></details>

:) ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by Anat123** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr14BYM3fwWRgzs8GlY:-Kr9uS_ORpvM6GFfGYfM:b-uh2u6k) ([raw file](https://github.com/kaltura/kmc-ng/blob/817b7afb77ec6322817c4aea7aa0b07cc1df781e/src/applications/content-categories-app/categories/categories-list.component.html#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

FYI :) almost there... see my comment below
</blockquote></details>

.. see my comment below
?
which comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by amirch1** [comment]
Review status: 15 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 16 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr9s6j5fToCgSVmOaR8:-Kr9zWMvS88tl9TUrmHt:bfrg8co) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L16)):*
<details><summary><i>Previously, Anat123 wrote…</i></summary><blockquote>

I think we should consider moving the file location magnifier.png.
the current position is under content-entries-app/styles
</blockquote></details>

correct - lets move it to the shared style (we have one in the project)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by Anat123** [comment]
Review status: 14 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-categories-app/categories/categories-list.component.html, line 16 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-Kr9s6j5fToCgSVmOaR8:-KrA-vN0WBb2Vko-0p2J:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/633e79585093ac796bb8e46ccfb79894a3192f55/src/applications/content-categories-app/categories/categories-list.component.html#L16)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

correct - lets move it to the shared style (we have one in the project)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/182#-:-KrA8OMiD0VRSECETzHe:bnfp4nl)*

**Pull request merged**
