### PR TITLE
KMCNG-797, KMCNG-823, KMCNG-1406

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-797
https://kaltura.atlassian.net/browse/KMCNG-823
https://kaltura.atlassian.net/browse/KMCNG-1406

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/436)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTp_hpJtTPkd2r9wx:-L7JTp_hpJtTPkd2r9wy:b-7ino3s) (no related file):*
Unfortunately I think Meirav is wrong since the legacy KMC allow adding a user not listed in Kaltura. It seems that the legacy only prevent pressing the button when no user is selected.

Also, it seems that following her guidance you changes entry details/users/change owner? if so this one should also allow changing to a user not listed in kaltura.

+@amirch1 please verify

 


---

*[src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts, line 195 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTX-bqFB78Z_ggQm9:-L7JTX-bqFB78Z_ggQmA:bv58bfp) ([raw file](https://github.com/kaltura/kmc-ng/blob/367b3648d9f9020ba11751c93d013956de421d34/src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts#L195)):*
> ```XML
>   // owner changed
>   onOwnerChanged(owner: KalturaUser): void {
>     if (owner instanceof KalturaUser) {
> ```

see my general comment

---

*[src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts, line 142 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTS37_pd3MCdpNaNq:-L7JTS37_pd3MCdpNaNr:bv58bfp) ([raw file](https://github.com/kaltura/kmc-ng/blob/367b3648d9f9020ba11751c93d013956de421d34/src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts#L142)):*
> ```XML
> 	public _apply() {
>     const [owner] = this._owner;
>     if (owner instanceof KalturaUser) {
> ```

see my general comment

---

*[src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts, line 155 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JT_LnLcACa20t7Nv_:-L7JT_LnLcACa20t7Nva:bv58bfp) ([raw file](https://github.com/kaltura/kmc-ng/blob/367b3648d9f9020ba11751c93d013956de421d34/src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts#L155)):*
> ```XML
>   public _updateApplyButtonState(): void {
>     const [owner] = this._owner;
>     this._disableApplyButton = !(owner instanceof KalturaUser);
> ```

see my general comment

---

*[src/i18n/en.json, line 1424 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTjzVWeZ52zE8PvkQ:-L7JTjzVWeZ52zE8PvkR:bv58bfp) ([raw file](https://github.com/kaltura/kmc-ng/blob/4b35912178df98eedf85494050a7d8ed7cd4f6b9/src/i18n/en.json#L1424)):*
> ```JSON
>           "co-editors": "Co-Editors",
>           "co-publishers": "Co-Publishers",
>           "tooltip": "User is not yet listed in Kaltura. {{0}} will be considered as user's identifier"
> ```

see my general comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTp_hpJtTPkd2r9wx:-L7K7YmOVLiyhT6z-U7m:beer68s) (no related file):*
> u changes entry details/users/change owner? 
+@esakal - you are correct. I will let Meirav know that the legacy KMC permits specifying users not from the suggestions. This PR fix should only apply to prevent using empty values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTp_hpJtTPkd2r9wx:-L7O69u4tsOA3UK-ko1W:b66zfu6) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

> u changes entry details/users/change owner? 
+@esakal - you are correct. I will let Meirav know that the legacy KMC permits specifying users not from the suggestions. This PR fix should only apply to prevent using empty values.
</blockquote></details>

any news on this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by amirch1** [comment]
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTp_hpJtTPkd2r9wx:-L7Ox9jZhJe4f8www4A8:bpkxjv4) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

any news on this one?
</blockquote></details>

Yes - you should permit users not from the suggestions list - just mark them in a lighter color and add a tooltip like we do in the Entry Details > Users tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by diamond-darrell** [comment]
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/436#-L7JTp_hpJtTPkd2r9wx:-L7Ox_s_iuccqO17nAZW:be2dseg) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Yes - you should permit users not from the suggestions list - just mark them in a lighter color and add a tooltip like we do in the Entry Details > Users tab
</blockquote></details>

yes, I'd found the issue with comments, already done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/436)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/436#-:-LCTIFAB1XsHvBPKSH1I:bnfp4nl)*

**Pull request merged**
