### PR TITLE
KMCNG-1298

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/357)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
Merge after this PR https://github.com/kaltura/kmc-ng/pull/353
Since this issue rely on predefined filter that was fixed in it


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/357#-:-L41OcSj8qGYGNOjtL68:b-c98y89)*

**Comment by esakal** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/357#-L4Vk1nFDSQF-PQH98cW:-L4Vk1nFDSQF-PQH98cX:b-pd0hrg) (no related file):*
pending insights from Amir

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/357)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/357)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/357#-L4oGraFrLHpxlflW-01:-L4oGraFrLHpxlflW-02:b4f2tfu) (no related file):*
Currently, in this branch - no entries are shown in the entries selector.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/357)*

**Comment by diamond-darrell** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/357#-L4oGraFrLHpxlflW-01:-L4oHbtehZyp3ex-B374:b-8qof2m) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Currently, in this branch - no entries are shown in the entries selector.
</blockquote></details>

yes, it's because the master wasn't merged into it, I've merged it, please try now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/357)*

**Comment by amirch1** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/357#-L4oGraFrLHpxlflW-01:-L4oKOW-KLxVawL_NOSq:b-klcre3) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

yes, it's because the master wasn't merged into it, I've merged it, please try now
</blockquote></details>

tested again. Now entries show but the bug still reproduces :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/357)*

**Comment by diamond-darrell** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/357#-L4oGraFrLHpxlflW-01:-L4ojD4yJIxSBnvW-HvE:boy3ows) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

tested again. Now entries show but the bug still reproduces :(
</blockquote></details>

weird, I've checked out on this branch, works for me


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/357)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/357#-:-L4pCalR81gTFCR53BFN:bnfp4nl)*

**Pull request merged**
