### PR TITLE
KMCNG-640 - Import: Error message is shown when removing focus from t…

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
…ext box without typing

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/252)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts, line 40 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/252#-Kyl1FKacz2ZnW4j5e74:-Kyl1FKacz2ZnW4j5e75:b5yr2ta) ([raw file](https://github.com/kaltura/kmc-ng/blob/3efaebdfe94cbba8ddceffcf4ac4126f1e2b5c64/src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts#L40)):*
> ```XML
> 
> 	_validate(){
> 		if (/^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})).?)(?::\d{2,5})?(?:[/?#]\S*)?$/i.test(this._flavorURL) || !this._flavorURL.length){
> ```

+@amirch1 maybe we should consider using [this validators](https://github.com/kaltura/kaltura-ng/blob/1cef9a7cd163029f33decae226ea1685131c1cee/kaltura-ui/src/validators/validators.ts#L31). there we assume reactive form is in use so we can just extend it with another function that perform direct validation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts, line 40 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/252#-Kyl1FKacz2ZnW4j5e74:-KyoDQVAw6ORmK8KvrpU:b5tnx3k) ([raw file](https://github.com/kaltura/kmc-ng/blob/3efaebdfe94cbba8ddceffcf4ac4126f1e2b5c64/src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts#L40)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 maybe we should consider using [this validators](https://github.com/kaltura/kaltura-ng/blob/1cef9a7cd163029f33decae226ea1685131c1cee/kaltura-ui/src/validators/validators.ts#L31). there we assume reactive form is in use so we can just extend it with another function that perform direct validation?
</blockquote></details>

Konstantin, please add function `isUrlValid(url: string): boolean` in [link](https://github.com/kaltura/kaltura-ng/blob/1cef9a7cd163029f33decae226ea1685131c1cee/kaltura-ui/src/validators/validators.ts#L31) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252)*

**Comment by konstantin-stepanets** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts, line 40 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/252#-Kyl1FKacz2ZnW4j5e74:-Kyoq7Y55PtwzRkr6P-9:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/3efaebdfe94cbba8ddceffcf4ac4126f1e2b5c64/src/applications/content-entries-app/entry/entry-flavours/flavor-import/flavor-import.component.ts#L40)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Konstantin, please add function `isUrlValid(url: string): boolean` in [link](https://github.com/kaltura/kaltura-ng/blob/1cef9a7cd163029f33decae226ea1685131c1cee/kaltura-ui/src/validators/validators.ts#L31) 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/252#-:-Kz-QFBMDiZTsmsaJ1x8:bnfp4nl)*

**Pull request merged**
