### PR TITLE
feat: add category details > metadata section

### PR DESCRIPTION
**Pull request by benstov**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/270)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrnGqoRBWZ4c7JqeyH:-KzrnGqoRBWZ4c7JqeyI:btghpcj) (no related file):*
sticky issue



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrnOT4LdsvXEABly6w:-KzrnOT4LdsvXEABly6x:blh6e2a) (no related file):*
error during save



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrngeEfiM9_as_euac:-KzrngeEfiM9_as_euad:bxw1vf4) (no related file):*
failure when trying to save with empty text in unlimited field. This is a valid scenario.





---

*[src/applications/content-categories-app/category/category-details/category-details.component.ts, line 28 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriMxYuVSWeUG_cVmu:-KzriMxYuVSWeUG_cVmv:bag2y5q) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-details/category-details.component.ts#L28)):*
> ```XML
> 
>         if (status) {
>           switch (status.action) {
> ```

missing implementation?

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriwrmCWAitsZXW9vY:-KzriwrmCWAitsZXW9vZ:b1bzixg) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L136)):*
> ```XML
>         if (!this.data.referenceId &&
>             this.data.referenceId != '' &&
>             this.data.referenceId != '__null_string__') {
> ```

from where did you take this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrngeEfiM9_as_euac:-KzrqCt0KuAGeUuQ8uaT:b-lhfq23) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

failure when trying to save with empty text in unlimited field. This is a valid scenario.





</blockquote></details>

Ben, @diamond-darrell will fix it as part of [kmcng-702](https://kaltura.atlassian.net/browse/KMCNG-702) but I added it here because you should have seen it during your tests, I want you to be familiar with this test and do some further random testings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by benstov** [comment]
Review status: 19 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrngeEfiM9_as_euac:-KzsO9LcegXmr1e6gpt2:bi75w89) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Ben, @diamond-darrell will fix it as part of [kmcng-702](https://kaltura.atlassian.net/browse/KMCNG-702) but I added it here because you should have seen it during your tests, I want you to be familiar with this test and do some further random testings.
</blockquote></details>

ok, i noted it to myself.
Also adding a date with the value null is valid?

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrnGqoRBWZ4c7JqeyH:-KzwRFQh8JAeOcMqXQU_:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

sticky issue



</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrnOT4LdsvXEABly6w:-KzwRIk1QXUjucViN_Z2:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

error during save



</blockquote></details>

Done.

---

*[src/applications/content-categories-app/category/category-details/category-details.component.ts, line 28 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriMxYuVSWeUG_cVmu:-KzsEISyXdAbYlHXeudM:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-details/category-details.component.ts#L28)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

missing implementation?
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriwrmCWAitsZXW9vY:-KzsFDtC0JfjLiMXvPkD:b3fwvoh) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L136)):*
>       this.data.referenceId != '__null_string__') {
convert '__null_string__' to/from empty string (PRD)

it is a leftover of amishay code, i have now refactored it so it will work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzrngeEfiM9_as_euac:-L-komN2lccffxS39vtC:bwq8enb) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

ok, i noted it to myself.
Also adding a date with the value null is valid?
</blockquote></details>

OK yes adding a date with null value is valid (it will be removed by the infrastructure automatically).

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lEdLyMmgRH3melDk5:-L-lEdLz043dmjbXU7yv:b-iwx4nd) (no related file):*
layout issue?



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lLUZAl6hq-sGfNBgM:-L-lLUZAl6hq-sGfNBgN:b-v3dvjf) (no related file):*
position of tooltip?



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lLt2OJGuFqxCvivvz:-L-lLt2OJGuFqxCvivw-:b-r8lvue) (no related file):*
if trying to access category that not exists - should allow only 'back to categories' button.

Also you parse the value as number so setting value `s33xce` in the url will try to get category 0. you should check that the number of the category is an actual number see the following [link](https://stackoverflow.com/a/6449623/5874422) and if not use the same logic



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lO33UV-o8Xmpv5UUE:-L-lO33UV-o8Xmpv5UUF:b-ufpb7d) (no related file):*
next/prev seems to be disabled even when reaching from categories list



---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriwrmCWAitsZXW9vY:-L-kpC5l3UCjvhBQOqin:bqyuvih) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L136)):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

>       this.data.referenceId != '__null_string__') {
convert '__null_string__' to/from empty string (PRD)

it is a leftover of amishay code, i have now refactored it so it will work
</blockquote></details>

this is not needed, the `kaltura-ngx-client` is handling this for you. please confirm what I just said (by removing this code and entering a category with and without reference id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by benstov** [comment]
Review status: 23 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lO33UV-o8Xmpv5UUE:-L-ztsu-Mmdy8I_qhRPP:b-rnraql) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

next/prev seems to be disabled even when reaching from categories list



</blockquote></details>

done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lLUZAl6hq-sGfNBgM:-L-zvIkz9wWVTjXY6nwQ:bdvt6j2) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

position of tooltip?



</blockquote></details>

opened task : https://kaltura.atlassian.net/browse/KMCNG-1096

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lLt2OJGuFqxCvivvz:-L0-Lx2mxRJsi-nUz3u3:bb6un1j) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

if trying to access category that not exists - should allow only 'back to categories' button.

Also you parse the value as number so setting value `s33xce` in the url will try to get category 0. you should check that the number of the category is an actual number see the following [link](https://stackoverflow.com/a/6449623/5874422) and if not use the same logic



</blockquote></details>

Done

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lEdLyMmgRH3melDk5:-L0-NXRri4PjmGNm2NdY:b-7rl0jd) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

layout issue?



</blockquote></details>

done.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-KzriwrmCWAitsZXW9vY:-L0-NVH_FdNUzZiTncN3:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/8568f98f943ae733c81db7f8c6350e167172b070/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L136)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not needed, the `kaltura-ngx-client` is handling this for you. please confirm what I just said (by removing this code and entering a category with and without reference id.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lO33UV-o8Xmpv5UUE:-L08ZST-T39dwq0qMAew:b-8zf7ub) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done.
</blockquote></details>

+@amirch1 please confirm

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lEdLyMmgRH3melDk5:-L08ZYKHwJaK4M5Qtnfk:b-8zf7ub) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done.
</blockquote></details>

+@amirch1 please confirm

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08ZCE1DWB3CYJTG-cd:-L08ZCE1DWB3CYJTG-ce:b-n9o4w1) (no related file):*
This comment is here to prevent merging until we complete the review of:
- https://github.com/kaltura/kmc-ng/pull/276
- https://github.com/kaltura/kmc-ng/pull/285

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08iEFbA8GkYyPS4FTD:-L08iEFcdmgr5H2PUBFT:b-t1qv7) (no related file):*
I don't think the prefix 'Category -' is by design, please confirm



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by benstov** [comment]
Review status: 25 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08ZCE1DWB3CYJTG-cd:-L0978qw6JXwWqMmAHJY:b-ss9pei) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

This comment is here to prevent merging until we complete the review of:
- https://github.com/kaltura/kmc-ng/pull/276
- https://github.com/kaltura/kmc-ng/pull/285
</blockquote></details>

its is fixed in subcategories

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08iEFbA8GkYyPS4FTD:-L0974Zj6fBqhP89VYLR:b-7rl0jd) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I don't think the prefix 'Category -' is by design, please confirm



</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by amirch1** [comment]
Review status: 25 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lEdLyMmgRH3melDk5:-L09lLYw6_HatTf_VtR4:b-xujw5) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 please confirm
</blockquote></details>

yes - should get padding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by amirch1** [comment]
Reviewed 13 of 24 files at r1, 2 of 6 files at r2, 7 of 9 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lEdLyMmgRH3melDk5:-L0J3DmVzdAe1PlPtI-I:b-7rl0jd) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

yes - should get padding
</blockquote></details>

done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L-lO33UV-o8Xmpv5UUE:-L0J3FvfVtDYQCzj6iCv:b-e0ok76) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 please confirm
</blockquote></details>

fixed in subcategories branch.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08ZCE1DWB3CYJTG-cd:-L0J3JtveY94oOSToNT-:b-7rl0jd) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

its is fixed in subcategories
</blockquote></details>

done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08iEFbA8GkYyPS4FTD:-L0J3LRaXXz8VP3v2zrU:b-7rl0jd) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done.
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-L08ZCE1DWB3CYJTG-cd:-L17HTzo2vz1q4wseBx-:b3ksm) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done.
</blockquote></details>

k

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
Reviewed 25 of 38 files at r8, 5 of 11 files at r9, 15 of 15 files at r10, 175 of 175 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 175 files at r11, 16 of 16 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/270#-:-L2P1fsJwjuUVuLdMJgT:bnfp4nl)*

**Pull request merged**
