### PR TITLE
Itunes feed

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/242157298/Content+Distribution+New+Edit+Feed+-+ITunes

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/480)

### CODE REVIEW

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/480#-:-LACHEvw-E5WM2Ilh8PY:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/480)*

**Comment by esakal** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.ts, line 189 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/480#-LCOO8_z7PHuh6ougewc:-LCOO8_z7PHuh6ougewd:b-6i2e2k) ([raw file](https://github.com/kaltura/kmc-ng/blob/de348b4d6e0a08ca1b12539f46ca89b23daf2d4a/src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.ts#L189)):*
> ```XML
>     // load all supported languages
>     this._languages = [];
>     const excludedLanguages = ['he', 'id', 'yi']; // duplicated languages TODO [KMCNG] - should be checked with backend
> ```

I assume you took this logic from entry captions edit view? 
Can you please extract it to a shared service and check if there are other places that are using this approach and refactor them as well to use the shared service?

---

*[src/i18n/en.json, line 703 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/480#-LCOOJK55fgJDdXQ8OV6:-LCOOJK55fgJDdXQ8OV7:b-278ym5) ([raw file](https://github.com/kaltura/kmc-ng/blob/de348b4d6e0a08ca1b12539f46ca89b23daf2d4a/src/i18n/en.json#L703)):*
> ```JSON
>                 "itemsSelected":"{0} Selected Categories",
>                 "availableCategories": {
>                   "Arts": "Arts",
> ```

please use a naming convention of lower camel case. If you wish you can replace `/` and '&' with `_` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/480)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/480#-:-LCSoJdH8q9B4hsHcPNu:bnfp4nl)*

**Pull request merged**
