### PR TITLE
KMCNG-1228

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/359)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/359#-L41_rGy52m_i7TJKmol:-L41_rGy52m_i7TJKmom:bhim166) ([raw file](https://github.com/kaltura/kmc-ng/blob/8dd103dfd66c194926a45e92ad722291b31c80a3/src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts#L20)):*
> ```XML
>   ngOnInit() {
>     this._widgetService.attachForm();
>     this._widgetService.data$
> ```

Does this relates to the reported bug or something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/359#-L41_rGy52m_i7TJKmol:-L41a8IZWPtjCxtwXBMz:bb9615j) ([raw file](https://github.com/kaltura/kmc-ng/blob/8dd103dfd66c194926a45e92ad722291b31c80a3/src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts#L20)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Does this relates to the reported bug or something else?
</blockquote></details>

no, I didn't see an open bug on this issue, I've just noticed it and decided to fix
The issue is - if you select several or one entry by bulk selection then, for example, move some entries and hit save, after reload the selection is still visible, but it shouldn't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/359#-L41_rGy52m_i7TJKmol:-L4UhwB5206RRpPzwLci:bejmt2e) ([raw file](https://github.com/kaltura/kmc-ng/blob/8dd103dfd66c194926a45e92ad722291b31c80a3/src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts#L20)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

no, I didn't see an open bug on this issue, I've just noticed it and decided to fix
The issue is - if you select several or one entry by bulk selection then, for example, move some entries and hit save, after reload the selection is still visible, but it shouldn't
</blockquote></details>

Stas, this fix was done on an old version of playlist when you had only manual content. I reverted this change you will need to handle it again both in manual and in rule based widgets separately



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359#-:-L4UiQh_fb6i8ITvyZ5f:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/359#-:-L4UnjNKK8ub0pXiELr0:bnfp4nl)*

**Pull request merged**
