### PR TITLE
fix: fix loading spinner layout

### PR DESCRIPTION
**Pull request by amirch1**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/289)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry.component.html, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/289#-L-Rv2-55PwTN_Q81DXd:-L-Rv2-55PwTN_Q81DXe:b-w8msew) ([raw file](https://github.com/kaltura/kmc-ng/blob/5ffec88a831c8b6e49158966ed63ffcb886b462e/src/applications/content-entries-app/entry/entry.component.html#L1)):*
> ```HTML
> <k-area-blocker [showLoader]="_showLoader" [message]="_areaBlockerMessage" [centerOnScreen]="true" [classes]="'kFillHeight'">
> ```

what about renaming `centerOnScreen` to the name we discussed about? I don't remember if it was called `scrollable` you will probably remember it. Using `centerOnScreen` is not intuitive.

regarding `kFillHeight`, see image below:
1. why bulk-log-table has it? I don't see it in the scss file
2. what about other applications like categories, playlist etc... shouldn't they have it as well? If so, we must dedicate half a day to plan and move all the form related styles into the theme and enforce it across all applications....

Let's discuss
 



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289)*

**Comment by amirch1** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry.component.html, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/289#-L-Rv2-55PwTN_Q81DXd:-L-Vbev_ZdY7ssCKRgnQ:bdjm5p6) ([raw file](https://github.com/kaltura/kmc-ng/blob/5ffec88a831c8b6e49158966ed63ffcb886b462e/src/applications/content-entries-app/entry/entry.component.html#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

what about renaming `centerOnScreen` to the name we discussed about? I don't remember if it was called `scrollable` you will probably remember it. Using `centerOnScreen` is not intuitive.

regarding `kFillHeight`, see image below:
1. why bulk-log-table has it? I don't see it in the scss file
2. what about other applications like categories, playlist etc... shouldn't they have it as well? If so, we must dedicate half a day to plan and move all the form related styles into the theme and enforce it across all applications....

Let's discuss
 



</blockquote></details>

this should be removed from the bulk log component (its the old directive that is currently not in used).
added to playlist details. will add to category details once merged to master.
moved class definition to shared styles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289)*

**Comment by amirch1** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry.component.html, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/289#-L-Rv2-55PwTN_Q81DXd:-L-_OV2268yOSkk_8dUW:b-sdbqyv) ([raw file](https://github.com/kaltura/kmc-ng/blob/5ffec88a831c8b6e49158966ed63ffcb886b462e/src/applications/content-entries-app/entry/entry.component.html#L1)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

this should be removed from the bulk log component (its the old directive that is currently not in used).
added to playlist details. will add to category details once merged to master.
moved class definition to shared styles.
</blockquote></details>

changed centerOnScreen to bodyScroll. Removed kFillHeight from areablocker (moved to inner DIV)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289)*

**Comment by esakal** [comment]
Reviewed 22 of 23 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289#-:-L-aWqsiBaJamo8kmpoc:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/289)*

**Pull request merged**
