### PR TITLE
KMCNG-1169, KMCNG-1170

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1169
https://kaltura.atlassian.net/browse/KMCNG-1170

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/442)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JQsYsE1DO5_-OGHoL:-L7JQsYsE1DO5_-OGHoM:b-d864yj) (no related file):*
I cannot reproduce it as it works for me and the code seems right. 

I suspect the server doesn't manage to index it fast enough thus returning a list without the new bulk upload.

+@amirch1 please confirm.

---

*[src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.ts, line 133 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JPsodNklyG4-rArKr:-L7JPsodNklyG4-rArKs:bk5npqx) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba2faa75f4c874cc8c82ed0e2988604ab2eb47b9/src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.ts#L133)):*
> ```XML
> 
>   public _closeUploadSuccessPopup(): void {
>     this._appEvents.publish(new BulkLogReloadListEvent());
> ```

I'm not sure we should publish here an event, since this function doesn't 'reload' bulk log. but see general comment before continue with this PR 

---

*[src/i18n/en.json, line 998 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JPM3dHgvJvyVkO-0L:-L7JPM3eOczixheHLMtk:b-ypp37c) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba2faa75f4c874cc8c82ed0e2988604ab2eb47b9/src/i18n/en.json#L998)):*
> ```JSON
>           "failed": "Failed",
>           "otherStatuses": "All other statuses",
>           "datesRangeError": "'From Date' must be before 'To Date'"
> ```

the app has two different messages addressing the same type of filter, none of them according to the open ticket. 

+@amirch1 can you please check which message should be used?



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/442)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/i18n/en.json, line 998 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JPM3dHgvJvyVkO-0L:-L7O8hxTVjMmGQm4hm9Z:b-8nw3pz) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba2faa75f4c874cc8c82ed0e2988604ab2eb47b9/src/i18n/en.json#L998)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the app has two different messages addressing the same type of filter, none of them according to the open ticket. 

+@amirch1 can you please check which message should be used?



</blockquote></details>

but it is according to one of the tickets attached to this PR


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/442)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/i18n/en.json, line 998 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JPM3dHgvJvyVkO-0L:-L7O9e_XEMudPDt8aXe0:b-s5dzc8) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba2faa75f4c874cc8c82ed0e2988604ab2eb47b9/src/i18n/en.json#L998)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

but it is according to one of the tickets attached to this PR


</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/442)*

**Comment by diamond-darrell** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JQsYsE1DO5_-OGHoL:-L7OHZs5-gj23PYZZ29P:bkmafkk) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I cannot reproduce it as it works for me and the code seems right. 

I suspect the server doesn't manage to index it fast enough thus returning a list without the new bulk upload.

+@amirch1 please confirm.
</blockquote></details>

actually, you right, we are already doing reload, will create another PR just for the error message fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/442)*

**Comment by diamond-darrell** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/i18n/en.json, line 998 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/442#-L7JPM3dHgvJvyVkO-0L:-L7OLNMSlT9_ozQpXN5R:b-w72sis) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba2faa75f4c874cc8c82ed0e2988604ab2eb47b9/src/i18n/en.json#L998)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>


</blockquote></details>

+@esakal +@amirch1 created new PR - https://reviewable.io/reviews/kaltura/kmc-ng/456

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/442)*

**Comment by esakal** [comment]
already implemented in other PRs

**Pull request closed without merging**
