### PR TITLE
KMCNG-293: Entry details > Custom Data > EntryId list

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-293
https://kaltura.atlassian.net/browse/KMCNG-1580

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/463)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
+@esakal this branch also holds an implementation of the CONTENT_MANAGE_CUSTOM_DATA permission (https://kaltura.atlassian.net/browse/KMCNG-1580)

---

Review status: 0 of 29 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lCoLO8Zco-aqpGB8G:-L8lCoLO8Zco-aqpGB8H:bsatl24) (no related file):*
+@amirch1 there's an issue with the styling of the disabled items in the entry detail's custom metadata section, Eran asked me to address it to you 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-:-L8lCeMu4kGVUsCpCN14:b-63f686)*

**Comment by esakal** [comment]
Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lCoLO8Zco-aqpGB8G:-L8lKO8hDQTSrgOG8hJF:bptrmmc) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@amirch1 there's an issue with the styling of the disabled items in the entry detail's custom metadata section, Eran asked me to address it to you 
</blockquote></details>

The issue is when the button is disabled due to permissions and the user hover on the button (which is an anchor element)



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lH6hi8W6-SnzXATIP:-L8lH6hi8W6-SnzXATIQ:b-78kdzh) (no related file):*
text placeholder is too big in my opinion. is it the same as in other places? maybe we should consider shrinking it a bit. +@amirch1 what do you think?



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lIxmMEfIF-94UB47k:-L8lIxmMEfIF-94UB47l:blldq0o) (no related file):*
should change the position of the component:
- move to the same line of the label 
- remove the padding of the button so it will align to the other components
- add margin to the table the same as other controls has



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lKe-sDHIzECSicwXB:-L8lKe-sDHIzECSicwXC:b-f1lklj) (no related file):*
Stas, check if you need to add the binding to custom storing here as well to prevent the table from sorting it differently

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLHU1AZso2feeMVWr:-L8lLHU1AZso2feeMVWs:b-pt98hf) (no related file):*
pressing the delete button should clear selections



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLmDa9HZKFfhYKzDl:-L8lLmDa9HZKFfhYKzDm:b-uhbxgo) (no related file):*
I know the invision is saving a place for two entries only but lets extend it to up to 4 rows



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLultD817QDcBNgv8:-L8lLultD817QDcBNgv9:b-ol52w0) (no related file):*
The legacy allows having the entry multiple times. remember to add the unique id for the reordering to workn



---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463)*

**Comment by diamond-darrell** [comment]
Review status: 28 of 29 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lCoLO8Zco-aqpGB8G:-L8lmiI_AH1aY8zOkupZ:b-pdipm1) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The issue is when the button is disabled due to permissions and the user hover on the button (which is an anchor element)



</blockquote></details>

and also buttons, they have no dedicated styling for the disabled state


---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLHU1AZso2feeMVWr:-L8ljnMvCXVCa4M7hmx6:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

pressing the delete button should clear selections



</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLmDa9HZKFfhYKzDl:-L8ljoNSCDdIVxftz714:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I know the invision is saving a place for two entries only but lets extend it to up to 4 rows



</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lLultD817QDcBNgv8:-L8ljpfP-ChfV9GBnWqX:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The legacy allows having the entry multiple times. remember to add the unique id for the reordering to workn



</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463)*

**Comment by diamond-darrell** [comment]
Review status: 21 of 29 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lKe-sDHIzECSicwXB:-L8lnX4A1vsu5nlYVx6-:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Stas, check if you need to add the binding to custom storing here as well to prevent the table from sorting it differently
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lH6hi8W6-SnzXATIP:-L8lnZV2-SOD4sGkctw_:b-wgwmsq) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

text placeholder is too big in my opinion. is it the same as in other places? maybe we should consider shrinking it a bit. +@amirch1 what do you think?



</blockquote></details>

Made them smaller

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lIxmMEfIF-94UB47k:-L8lnaTt1sbspA6vZH3N:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

should change the position of the component:
- move to the same line of the label 
- remove the padding of the button so it will align to the other components
- add margin to the table the same as other controls has



</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lCoLO8Zco-aqpGB8G:-L8luuaV8NiBpucJnnWc:b9hxa7i) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

and also buttons, they have no dedicated styling for the disabled state


</blockquote></details>

will take this with Amir on Sunday

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-L8lIxmMEfIF-94UB47k:-L8lubRy3bi6d_vuxVXL:b307wj5) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

Amir let's discuss about the small resolution issue here

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/463#-:-L9-XCxg-2qPVS_9Yjl-:bnfp4nl)*

**Pull request merged**
