### PR TITLE
Whitelist beta users

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://trello.com/c/kS8PE1Wm

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/589)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 226 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/589#-LAyUEvHBUy3sxyuu_Ci:-LAyUEvHBUy3sxyuu_Cj:b-ckhxvd) ([raw file](https://github.com/kaltura/kmc-ng/blob/16a8227aa098578bf64af14a68d4c075822c11f2/src/shared/kmc-shell/auth/app-authentication.service.ts#L226)):*
> ```XML
> 
>         if (!this._hasAccessToBeta) {
>             this.logout(false);
> ```

are you sure we need this call? I think the service doesn't set and state outside of `_afterLogin`, can you please confirm?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/589)*

**Comment by esakal** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/configuration/server-config.ts, line 75 at r2](https://reviewable.io/reviews/kaltura/kmc-ng/589#-LBGjlrH-qZdwhx7NYE6:-LBGjlrH-qZdwhx7NYE7:b-ivjh0m) ([raw file](https://github.com/kaltura/kmc-ng/blob/05b2d5805c4c94ec117bd4f904e0420d0dc2e235/src/configuration/server-config.ts#L75)):*
> ```XML
>             limitAccess: {
>                 enabled: boolean,
>                 whitelist: number[]
> ```

please change this property with `verifyBetaServiceUrl` which should be a url like the following: `/example/verify-beta.php?partner-id={partnerId}`

- Your code should replace `{partnerId}`with actual value instead and use angular Http client to query the url and get back json response `{ isPartnerPartOfBeta: boolean }`
- you should change [this code](https://github.com/kaltura/kmc-ng/blob/whitelist-beta-users/src/shared/kmc-shell/auth/app-authentication.service.ts#L236)
- if error happened, return it as login error (don't treat it as not part of beta).

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/589)*

**Comment by diamond-darrell** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/configuration/server-config.ts, line 75 at r2](https://reviewable.io/reviews/kaltura/kmc-ng/589#-LBGjlrH-qZdwhx7NYE6:-LBKNMEpDxlVKGxWV73j:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/05b2d5805c4c94ec117bd4f904e0420d0dc2e235/src/configuration/server-config.ts#L75)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please change this property with `verifyBetaServiceUrl` which should be a url like the following: `/example/verify-beta.php?partner-id={partnerId}`

- Your code should replace `{partnerId}`with actual value instead and use angular Http client to query the url and get back json response `{ isPartnerPartOfBeta: boolean }`
- you should change [this code](https://github.com/kaltura/kmc-ng/blob/whitelist-beta-users/src/shared/kmc-shell/auth/app-authentication.service.ts#L236)
- if error happened, return it as login error (don't treat it as not part of beta).

</blockquote></details>

OK

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 226 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/589#-LAyUEvHBUy3sxyuu_Ci:-LBKNLDQ1M7KPZpoXcGo:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/16a8227aa098578bf64af14a68d4c075822c11f2/src/shared/kmc-shell/auth/app-authentication.service.ts#L226)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

are you sure we need this call? I think the service doesn't set and state outside of `_afterLogin`, can you please confirm?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/589)*

**Comment by esakal** [comment]
Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/589)*

**Pull request merged**
