### PR TITLE
KMCNG-713 Entries - While saving - menu panel should be disabled

### PR DESCRIPTION
**Pull request by benstov**
…ble.tag('x').subscribe) that will mark the operation under 'x' tag.

This way we can mark operations that will block the main panel ".tag('block-shell')"

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/245)

### CODE REVIEW

**Comment by benstov** [comment]
@amirch1 Regarding the area blocker:
- The shell isn’t being fully blocked, the blue navigation strip is still clickable 
- Whenever a popup is opened and the area blocker is busy the popup is still editable (the popup z-index is probably higher than the app.component area blocker)

**Comment by amirch1** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 195 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxM-5RmpvOejas_HPJC:-KxM-5RmpvOejas_HPJD:b-29tygb) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L195)):*
> ```XML
>         },
>         error => {
>           this._browserService.setAppStatus({ isBusy: false, errorMessage: this._appLocalization.get('applications.content.bulkActions.error') });
> ```

this will probably won't work as it is connected to an area blocker. without the isBusy the area blocker will not show at all the the error message will not be seen

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 272 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLzKeOMb_HAEJ2Nz9v:-KxLzKeOMb_HAEJ2Nz9w:bfr76i8) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L272)):*
> ```XML
>               error => {
>                 this._state.next({
>                   isBusy: true,
> ```

can't we just remove the isBusy from the subject behavior?

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLyvh4e-jsDXBdwMKA:-KxLyvh4e-jsDXBdwMKB:b-hy1nf0) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/shared/kmc-shell/providers/browser.service.ts#L37)):*
> ```XML
> export class BrowserService implements IAppStorage {
> 
>   private _appStatus = new BehaviorSubject<{isBusy : boolean, errorMessage : string}>({ isBusy : false, errorMessage : null});
> ```

+@esakal - I think we should keep the ability to set app status globally for operation that are not requests to the server. However, if we remove it, we should probably remove all places in the application that currently use it (probably in browser.service and other places)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Comment by amirch1** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Comment by esakal** [comment]
Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 272 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLzKeOMb_HAEJ2Nz9v:-KyASFoRCpAQM3tMJHMT:b55j5m6) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L272)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

can't we just remove the isBusy from the subject behavior?
</blockquote></details>

we should. since this function is not raising the `isBusy` it shouldn't remove it 

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLyvh4e-jsDXBdwMKA:-KyAT2-IQ_3RwWBDCPhR:bx9nldw) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/shared/kmc-shell/providers/browser.service.ts#L37)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

+@esakal - I think we should keep the ability to set app status globally for operation that are not requests to the server. However, if we remove it, we should probably remove all places in the application that currently use it (probably in browser.service and other places)
</blockquote></details>

BTW Continuing our discussion,  +@benstov already removed it from the other places and from the infrastructure as-well. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 272 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLzKeOMb_HAEJ2Nz9v:-KyKtMjxGZHlotyUJ4Lh:bmhdrni) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L272)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we should. since this function is not raising the `isBusy` it shouldn't remove it 
</blockquote></details>

There are places that we need this isBusy not just in the save process, so i think we should leave it.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxLyvh4e-jsDXBdwMKA:-KyKtrxFBx_B2DtVUYVO:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/shared/kmc-shell/providers/browser.service.ts#L37)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

BTW Continuing our discussion,  +@benstov already removed it from the other places and from the infrastructure as-well. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 195 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/245#-KxM-5RmpvOejas_HPJC:-KyLUWyH2b1_3IpLgAMn:b9us1up) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae61eac7ec847250bab77b79bac1e21f03f19064/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L195)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

this will probably won't work as it is connected to an area blocker. without the isBusy the area blocker will not show at all the the error message will not be seen
</blockquote></details>

I have made a quick check and the error message is displayed as it should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/245)*

**Pull request merged**
