### PR TITLE
KMCNG-683 Metadata: Categories tree - focus is not on search box

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/225)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KvzaWps_LSBt4yr61E8:-KvzaWps_LSBt4yr61E9:bltfpag) (no related file):*
Again, this document was reformatted. Was this intentional? Very difficult to review the changes. FYI +@esakal 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 121 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-Kwj7xCeYYjiRjNHbVFe:-Kwj7xCeYYjiRjNHbVFf:byzdnpp) ([raw file](https://github.com/kaltura/kmc-ng/blob/f4191145d7266d6b5cec6ea65208a75935d0d265/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L121)):*
> ```XML
>     this.updateTreeSelections();
> 
>     if (this._categoriesLoaded) {
> ```

this it too technical to take part in an applicative component. it should be a directive that can be robust in be used in other places. 

Please discuss with +@diamond-darrell and join his implementation with yours. I'm not sure if he created a component/directive for that but it is worth checking if maybe you can share the same behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 121 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-Kwj7xCeYYjiRjNHbVFe:-Kx7P5h1vlOngAZbGram:bq3mti0) ([raw file](https://github.com/kaltura/kmc-ng/blob/f4191145d7266d6b5cec6ea65208a75935d0d265/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L121)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this it too technical to take part in an applicative component. it should be a directive that can be robust in be used in other places. 

Please discuss with +@diamond-darrell and join his implementation with yours. I'm not sure if he created a component/directive for that but it is worth checking if maybe you can share the same behavior.
</blockquote></details>

No, I didn't implement anything related to the autocomplete autofocus, but I think maybe we better extend the autocomplete component in the kaltura-primeng-ui to provide public API for support this feature
+@esakal +@benstov what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 121 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-Kwj7xCeYYjiRjNHbVFe:-KxC8n1q7RXNnGXdkYtG:bdpu866) ([raw file](https://github.com/kaltura/kmc-ng/blob/f4191145d7266d6b5cec6ea65208a75935d0d265/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L121)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

No, I didn't implement anything related to the autocomplete autofocus, but I think maybe we better extend the autocomplete component in the kaltura-primeng-ui to provide public API for support this feature
+@esakal +@benstov what do you think?
</blockquote></details>

It make sense. I missed the part that we traverse inside the auto-complete. 

In general, we created the `kaltura-primeng-ui` library because we are messing with the internals of primeng library. The HTML template is not public API which means that tend to change it between versions.

accessing the `domHandler` and searching the `input` is risky here but acceptable in the `kaltura-primeng-ui`.

+@benstov consider moving this into the `kaltura-primeng-ui/auto-complete` component **including** the `setTimeout` part. you can name the function something like.... `focus()` :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by benstov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 121 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-Kwj7xCeYYjiRjNHbVFe:-KxNRvWjY3jq26CuBRCx:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/f4191145d7266d6b5cec6ea65208a75935d0d265/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L121)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

It make sense. I missed the part that we traverse inside the auto-complete. 

In general, we created the `kaltura-primeng-ui` library because we are messing with the internals of primeng library. The HTML template is not public API which means that tend to change it between versions.

accessing the `domHandler` and searching the `input` is risky here but acceptable in the `kaltura-primeng-ui`.

+@benstov consider moving this into the `kaltura-primeng-ui/auto-complete` component **including** the `setTimeout` part. you can name the function something like.... `focus()` :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 61 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyAK9QqkHVrt7Z5Pu0g:-KyAK9QqkHVrt7Z5Pu0h:bn27am1) ([raw file](https://github.com/kaltura/kmc-ng/blob/434132de541a0d9dbfbb1c65a1a42462da9665d3/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L61)):*
> ```XML
>     this._selectedCategories = this.value && this.value instanceof Array ? [...this.value] : [];
>     setTimeout(() => {
>       if (this._tags) {
> ```

use relevant lifecycle event where view child exists already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 61 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyAK9QqkHVrt7Z5Pu0g:-KyBlQRu4gLGFsFq6KIi:b-2snfc8) ([raw file](https://github.com/kaltura/kmc-ng/blob/434132de541a0d9dbfbb1c65a1a42462da9665d3/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L61)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

use relevant lifecycle event where view child exists already
</blockquote></details>

it also doesn't exist in   ngAfterViewInit() lifecycle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by benstov** [comment]
@esakal @amirch1 Please notice that there is another PR related to this issue in the Kaltura-ng project https://reviewable.io/reviews/kaltura/kaltura-ng/24#-

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-:-KyFMmjJgyCL7aW7Vuq8:bo98g79)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 61 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyAK9QqkHVrt7Z5Pu0g:-KyGr3sObVZXc9Ng8LhT:b-5qmbk2) ([raw file](https://github.com/kaltura/kmc-ng/blob/434132de541a0d9dbfbb1c65a1a42462da9665d3/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L61)):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

it also doesn't exist in   ngAfterViewInit() lifecycle
</blockquote></details>

- What do you mean : "it also doesn't exist in ngAfterViewInit() lifecycle"

- your condition will fall on `null`, you should  always check both : `if (typeof this._tags !== 'undefined' && this._tags !== null)`

- why did you add this as part of KMCNG-683? I don't see the connection to the bug description.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 213 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyGrlpHwl-eFHFODNqM:-KyGrlpHwl-eFHFODNqN:b-hcmndt) ([raw file](https://github.com/kaltura/kmc-ng/blob/f44f54ee3f7092807e6a8f0980c0c5cc06f90c84/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L213)):*
> ```XML
> 					fullNamePath : selectedItem.fullNamePath,
> 					name: selectedItem.name,
> 				tooltip: selectedItem.tooltip});
> ```

did you add this line of was it added from a merge from master?

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 247 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyGrppitjbf7_SI5ofj:-KyGrppitjbf7_SI5ofk:b-hcmndt) ([raw file](https://github.com/kaltura/kmc-ng/blob/f44f54ee3f7092807e6a8f0980c0c5cc06f90c84/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L247)):*
> ```XML
> 					fullNamePath : node.origin.fullNamePath,
> 					name: node.origin.name,
> 				tooltip: node.origin.tooltip});
> ```

did you add this line of was it added from a merge from master?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 61 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyAK9QqkHVrt7Z5Pu0g:-KyLOmO9AoFYNHlPJEpZ:bipctuw) ([raw file](https://github.com/kaltura/kmc-ng/blob/434132de541a0d9dbfbb1c65a1a42462da9665d3/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L61)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- What do you mean : "it also doesn't exist in ngAfterViewInit() lifecycle"

- your condition will fall on `null`, you should  always check both : `if (typeof this._tags !== 'undefined' && this._tags !== null)`

- why did you add this as part of KMCNG-683? I don't see the connection to the bug description.
</blockquote></details>

* I meant that i get null also when i move this code to ngAfterViewInit() function
* Your'e right, thanks 
* It prevented me from coding, this error kept on popping up. 
I can erase this line and commit without it (and create a new issue for it) but then you wont be able to test.

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 213 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyGrlpHwl-eFHFODNqM:-KyLQyHXkFfs_PY8Bcn7:bbgys71) ([raw file](https://github.com/kaltura/kmc-ng/blob/f44f54ee3f7092807e6a8f0980c0c5cc06f90c84/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L213)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

did you add this line of was it added from a merge from master?
</blockquote></details>

added from the merge, i just added a redundant space 

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 236 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyLPr5_nCs60yAQsnLa:-KyLPr5_nCs60yAQsnLb:b-r5n1cr) ([raw file](https://github.com/kaltura/kmc-ng/blob/f44f54ee3f7092807e6a8f0980c0c5cc06f90c84/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L236)):*
> tooltip: selectedItem.tooltip

---

*[src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts, line 247 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/225#-KyGrppitjbf7_SI5ofj:-KyLR4DfsYrqa-hToM44:bbgys71) ([raw file](https://github.com/kaltura/kmc-ng/blob/f44f54ee3f7092807e6a8f0980c0c5cc06f90c84/src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts#L247)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

did you add this line of was it added from a merge from master?
</blockquote></details>

added from the merge, i just added a redundant space 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/225)*

**Pull request merged**
