### PR TITLE
KMCNG-1797

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1797

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @diamond-darrell and @amirch1)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppfXK3iWTzhw7q6yt:-LFppfXK3iWTzhw7q6yu:b-pidt69) (no related file):*
the resize cursor position is off



---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppiefDOE8oxFm04Kr:-LFppiefDOE8oxFm04Ks:bhaujq0) (no related file):*
the line of the resized column when dragging is white and since our bg is white as well it is not noticable

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFpqX4T9Xv2uYsO5oJR:-LFpqX4T9Xv2uYsO5oJS:b9ocp12) (no related file):*


should not be resizable if possible. The tricky part here is that you don't resize the actions column, you extend the tags column - check if you can enforce minimum width on the actions column so the user will not be able to affect it. Don't spend more then ~20 minutes on this feature

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @diamond-darrell, @esakal, and @amirch1)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppiefDOE8oxFm04Kr:-LFpzy_Y3pIxRHkSUXxz:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the line of the resized column when dragging is white and since our bg is white as well it is not noticable
</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppfXK3iWTzhw7q6yt:-LFq2wK19WCv8_94QqrB:b-96mdua) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the resize cursor position is off



</blockquote></details>

not sure I understand

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFpqX4T9Xv2uYsO5oJR:-LFq3-Un7olSv5pfcGTy:bf43q57) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>



should not be resizable if possible. The tricky part here is that you don't resize the actions column, you extend the tags column - check if you can enforce minimum width on the actions column so the user will not be able to affect it. Don't spend more then ~20 minutes on this feature
</blockquote></details>

We can make the previous column as not resizable so it will be resizable by another previous column (Tags not resizable, but we will be able to resize it by resizing Status column). But it's a hack, not solution since we have entries table where the columns are dynamic and we cannot tell which column will be the second from the end

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @esakal and @amirch1)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppfXK3iWTzhw7q6yt:-LFqX4ca-vN93EO71bd7:brm23wd) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

not sure I understand
</blockquote></details>

I cannot capture the mouse cursor, in order to resize Asset ID column I need to put the cursor ~10 pixels to the left of the column line

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFpqX4T9Xv2uYsO5oJR:-LFqXQZY382fhKtlT_Hr:b-174bxu) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

We can make the previous column as not resizable so it will be resizable by another previous column (Tags not resizable, but we will be able to resize it by resizing Status column). But it's a hack, not solution since we have entries table where the columns are dynamic and we cannot tell which column will be the second from the end
</blockquote></details>

I understand, but I think your suggestion is acceptable as it will solve it. Lets' add it to flavors as here we have static number of columns and we will think how to solve it in entires list in the relevant branch

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @diamond-darrell and @amirch1)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFppfXK3iWTzhw7q6yt:-LFqaB8O2lZ2H4vZCkce:bprd1y2) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I cannot capture the mouse cursor, in order to resize Asset ID column I need to put the cursor ~10 pixels to the left of the column line
</blockquote></details>

oh, it's a default behavior, I cannot configure or fix it (unless extending the table)

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @esakal and @amirch1)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/695#-LFpqX4T9Xv2uYsO5oJR:-LFqaN5JA8PXEQDf0zZ4:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I understand, but I think your suggestion is acceptable as it will solve it. Lets' add it to flavors as here we have static number of columns and we will think how to solve it in entires list in the relevant branch
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amirch1)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/695#-:-LFqjWdo9zfw8ezw6F6u:bnfp4nl)*

**Pull request merged**
