### PR TITLE
Content > Categories > Table

### PR DESCRIPTION
**Pull request by benstov**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/239)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi6F_luUs9V9pBOJ_j:-Kwi6F_m_JxnM6b_6hh1:b-9rwqct) (no related file):*
we need to discuss about the formatter you are using. It seems that the formatter is too aggressive...

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 108 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi2ZQdqNs7_AYsXN5F:-Kwi2ZQdqNs7_AYsXN5G:b-y67vfj) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories.service.ts#L108)):*
> ```XML
>     public getNextCategoryId(categoryId: number): number | null {
>         const categories = this._categories.getValue().items;
>         if (!categories || !categories.length) {
> ```

did it affect the behavior of the code somehow?

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 7 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi32dDTHwmGaL59A7v:-Kwi32dDTHwmGaL59A7w:blox2cu) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L7)):*
> ```XML
> import {AreaBlockerMessage} from "@kaltura-ng/kaltura-ui";
> import {PopupWidgetComponent} from "@kaltura-ng/kaltura-ui/popup-widget/popup-widget.component";
> import {CategoriesTableComponent} from "../categories-table/categories-table.component";
> ```

btw, splitting the code into multiple folders is a preference of the the developer not a style-guide. We only enforce splitting by context so entry flavor section will be separated from entry metadata section. 

I just wanted to make sure you know it is not a style-guide issue, you can leave it as you did.

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi4pW_rpmzDog4aHVe:-Kwi4pW_rpmzDog4aHVf:bv170bg) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L136)):*
> ```XML
>   }
> 
>   private _confirmDeletion(category: KalturaCategory) {
> ```

- the function name is misleading because you are not only asking for approval but also handle the actual delete.
- your confirmation is not split in two functions. Both in `onActionSelected` and in this function.

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 172 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5ARTsqgmfP-dMRam:-Kwi5ARTsqgmfP-dMRan:bg6qgn8) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L172)):*
> ```XML
>       error => {
>         this._isBusy = false;
>         this._browserService.showGrowlMessage({
> ```

can you add a reference to this requirement in the PRD?

---

*[src/applications/content-categories-app/categories/categories-table/categories-table.component.ts, line 13 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5RicvEcwGmRtdVZd:-Kwi5RicvEcwGmRtdVZe:bg6mlg2) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-table/categories-table.component.ts#L13)):*
> ```XML
> } from '@angular/core';
> import {ISubscription} from 'rxjs/Subscription';
> import {DataTable, Menu, MenuItem} from 'primeng/primeng';
> ```

your formatting too seems to be too aggresive. I assume it is re-arranging the imports by ABC? 

Are you using webstorm?

---

*[src/applications/content-categories-app/categories/categories-table/categories-table.component.ts, line 61 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5qxvbQqnJg8l8-50:-Kwi5qxvbQqnJg8l8-51:b-elccap) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-table/categories-table.component.ts#L61)):*
> ```XML
>   private _categoriesServiceStatusSubscription: ISubscription;
> 
>   public _emptyMessage = '';
> ```

is this also something done by your formatter. Does it removes the declaration because the declaration can be implied from the provided default value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi6F_luUs9V9pBOJ_j:-Kx3LN8u9vqYXA50AANa:b-7j86r0) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we need to discuss about the formatter you are using. It seems that the formatter is too aggressive...
</blockquote></details>

sure.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 108 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi2ZQdqNs7_AYsXN5F:-Kx3BSJX8vfvMOifGmHJ:b9h8nt3) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories.service.ts#L108)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

did it affect the behavior of the code somehow?
</blockquote></details>

not really, i just found it wrong that if there is no items so it shouldn't do the call to the server

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 7 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi32dDTHwmGaL59A7v:-Kx3CA349aWcNgZ6rQ0B:b-jq6h8h) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L7)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

btw, splitting the code into multiple folders is a preference of the the developer not a style-guide. We only enforce splitting by context so entry flavor section will be separated from entry metadata section. 

I just wanted to make sure you know it is not a style-guide issue, you can leave it as you did.
</blockquote></details>

yeah sure, well i did it since it is more comfortable for me to focus on the files im working on.

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 136 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi4pW_rpmzDog4aHVe:-Kx3LPImJuUThs-xvE7w:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L136)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- the function name is misleading because you are not only asking for approval but also handle the actual delete.
- your confirmation is not split in two functions. Both in `onActionSelected` and in this function.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-list/categories-list.component.ts, line 172 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5ARTsqgmfP-dMRam:-Kx3L6pmBvON7L0b_RYu:b-klxdh0) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-list/categories-list.component.ts#L172)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can you add a reference to this requirement in the PRD?
</blockquote></details>

Allow deleting a single category:

deletion successful - Show a floating success message: "Category deleted successfully"	use growl, auto-hide

deletion failure -  Show a floating error message: Category could not be deleted"	use growl, with close button

---

*[src/applications/content-categories-app/categories/categories-table/categories-table.component.ts, line 13 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5RicvEcwGmRtdVZd:-Kwo-J5vU2ZkuYOmoWad:b2nign6) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-table/categories-table.component.ts#L13)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

your formatting too seems to be too aggresive. I assume it is re-arranging the imports by ABC? 

Are you using webstorm?
</blockquote></details>

yes

---

*[src/applications/content-categories-app/categories/categories-table/categories-table.component.ts, line 61 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-Kwi5qxvbQqnJg8l8-50:-Kwo-G53c23yW7tyRafC:b-mdy27e) ([raw file](https://github.com/kaltura/kmc-ng/blob/6c6521febad439b08bf5a965f0a8148c0630ba49/src/applications/content-categories-app/categories/categories-table/categories-table.component.ts#L61)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is this also something done by your formatter. Does it removes the declaration because the declaration can be implied from the provided default value?
</blockquote></details>

yes, exactly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by esakal** [comment]
Reviewed 5 of 17 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-KyAusaT0Ii5OrWoSFXI:-KyAusaT0Ii5OrWoSFXJ:b-tzwu1h) (no related file):*
+@amirch1 please review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by esakal** [comment]
Reviewed 4 of 17 files at r1, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-KyKu1d8O8Q9KOcwCkvi:-KyKu1d8O8Q9KOcwCkvj:bdrg0lu) (no related file):*
waiting for @amirch1 review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-KyAusaT0Ii5OrWoSFXI:-KyLNmgQxiS5vY1GlUG1:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 please review
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 8 of 17 files at r1, 1 of 1 files at r2, 5 of 7 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-:-KyL_uRw6wRu_nL6OnrW:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 2 of 17 files at r1, 5 of 5 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/239#-:-KyQ1qW0VBIremGzagyk:bnfp4nl)*

**Pull request merged**
