### PR TITLE
Upload monitor

### PR DESCRIPTION
**Pull request by diamond-darrell**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/234)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/234#-Kw_PcJ9bfw9GFiHTO1G:-Kw_PcJAIeOYA5tKoiE3:b-2e72bw) ([raw file](https://github.com/kaltura/kmc-ng/blob/2d0ad203a38b13ac06c50bb52f65cf9b07974815/src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts#L66)):*
> ```XML
>           }
> 
>           switch (trackedFile.status) {
> ```

you should handle status purged.
Try the following scenario:
1. start an upload
2. cancel an upload

desired behavior: should be removed from the widget and update the relevant bucket accordingly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by esakal** [comment]
Stas, please use the following branch in kaltura-ng - [branch](use new api provided by the extended upload-management) when you work on upload monitor. also review my changes in the kmc-ng that I did to support the extended upload management

---

Review status: 7 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234#-:-KweB68HH37GYMGS8HJZ:bf1v7zc)*

**Comment by esakal** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by diamond-darrell** [comment]
OK

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/234#-Kw_PcJ9bfw9GFiHTO1G:-KxDxDL_rMlQegC-eyXw:b-i2vh9u) ([raw file](https://github.com/kaltura/kmc-ng/blob/2d0ad203a38b13ac06c50bb52f65cf9b07974815/src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts#L66)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should handle status purged.
Try the following scenario:
1. start an upload
2. cancel an upload

desired behavior: should be removed from the widget and update the relevant bucket accordingly
</blockquote></details>

So it means that cancel = fail in this case? Because there's no bucket for canceled upload

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234#-:-KxDx-I61rXSla5EkW1x:b32w0x)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/234#-Kw_PcJ9bfw9GFiHTO1G:-KxDyu1lDxB93G6olNyH:b-2mm7jh) ([raw file](https://github.com/kaltura/kmc-ng/blob/2d0ad203a38b13ac06c50bb52f65cf9b07974815/src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts#L66)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

So it means that cancel = fail in this case? Because there's no bucket for canceled upload
</blockquote></details>

Sorry, skip my previous comment, I got it :slightly_smiling_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Comment by esakal** [comment]
Reviewed 10 of 13 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/234)*

**Pull request merged**
