### PR TITLE
Settings integration settings

### PR DESCRIPTION
**Pull request by benstov**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/314)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 12 of 38 files at r1, 9 of 14 files at r2, 16 of 16 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cEk2nFuNQ7ugK9nEb:-L3cEk2nFuNQ7ugK9nEc:b2n5w3g) (no related file):*
should prevent sending request if category is already  in list



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cHHl5ZMYNJXtMXMTk:-L3cHHl5ZMYNJXtMXMTl:b-wjnh6a) (no related file):*
should enforce rules on the value the legacy allows. Prime has  [new component to consider](https://www.primefaces.org/primeng/#/keyfilter) - should consult with +@amirch1 





---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cHqKSRtmDD1pudSKz:-L3cHqKSRtmDD1pudSL-:bcpgqhw) (no related file):*
not centered



---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 35 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cKKFb3-bwBlZD1OsK:-L3cKKFb3-bwBlZD1OsL:b-ai1yv) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L35)):*
> ```XML
>     );
> 
>     return this._kalturaServerClient.multiRequest(request).map(
> ```

missing `.cancelOnDestroy(this)`

---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 57 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cM49Xl1QtLPDPMk2n:-L3cM49Xl1QtLPDPMk2o:b2ai7l9) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L57)):*
> ```XML
> 
>     if (privacyContextData) {
>       const context = (privacyContextData && privacyContextData.privacyContext.split(',')) || [];
> ```

? can privacyContext be null or undefined?

---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 61 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cMMxfSpB7xTLiFTnD:-L3cMMxfSpB7xTLiFTnE:bco05ae) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L61)):*
> ```XML
> 
>       // Subtract privacyContext from privacyContexts and if no contexts left so set the following properties
>       if (contexts.length && contexts.filter(c => (context.indexOf(c) < 0)).length) {
> ```

The logic is not according to the PRD



---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 76 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cMViHx8XMl54r7dG_:-L3cMViHx8XMl54r7dGa:b6if76a) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L76)):*
> ```XML
> 
>   public addEntitlement({id, privacyContext}: { id: number, privacyContext: string }): Observable<void> {
>     if (!id || !privacyContext) {
> ```

the logic is not according to the PRD



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314)*

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cEk2nFuNQ7ugK9nEb:-L3gVQgWPVGlDgC9EoZe:b8fkkjq) (no related file):*
> new component to consider
Fixed. Please verify the logic as this requires nested async calls. 

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cHHl5ZMYNJXtMXMTk:-L3gV_8n5nOW0alJwR0r:b-lxno2f) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

should enforce rules on the value the legacy allows. Prime has  [new component to consider](https://www.primefaces.org/primeng/#/keyfilter) - should consult with +@amirch1 





</blockquote></details>

sadly the new PrimeNG directive is not available in our current PrimeNG version so handled manually.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cHqKSRtmDD1pudSKz:-L3gY17rfyahtw0Zae7b:bxpknpt) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

not centered



</blockquote></details>

this is actually a PrimeNG bug, much like we have with our popup widget when height is not defined. I've force it to top: 200px like in our popup widget.

---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 35 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cKKFb3-bwBlZD1OsK:-L3g-wt2pYfh0Tmi4wrQ:byven2z) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L35)):*
> .cancelOnDestroy(this)
Added.

---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 57 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cM49Xl1QtLPDPMk2n:-L3g0iTCDR_JTw-ckKS0:b-7upu1j) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L57)):*
>  if (privacyContextData) {
changed verification for null and undefined

---

*[src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts, line 61 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-L3cMMxfSpB7xTLiFTnD:-L3gFH2zQVOlStlDydCz:b-ps923b) ([raw file](https://github.com/kaltura/kmc-ng/blob/e658eca400897acf0149b47952b99d0ece554b6f/src/applications/settings-integration-settings-app/entitlement/entitlement.service.ts#L61)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The logic is not according to the PRD



</blockquote></details>

refactored. Changes in the PRD as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314)*

**Comment by esakal** [comment]
Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314#-:-L3wGGLTszd_0DPhQfgT:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/314)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/314#-:-L3xJerZCq5sJIL_ZSqz:bnfp4nl)*

**Pull request merged**
