### PR TITLE
Playlist bulk issue

### PR DESCRIPTION
**Pull request by esakal**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/341)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts, line 75 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-L2VPcYJd9r6c3m0l5xk:-L2VPcYJd9r6c3m0l5xl:b37rvgc) ([raw file](https://github.com/kaltura/kmc-ng/blob/98f59103095c9a652dd77edb1ccf397999a3cb94/src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts#L75)):*
> ```XML
> 
>     super._showLoader();
>     this._state.next({ loading: true, error: false });
> ```

I removed this state because it is duplication of the underline class that also has loader state (`_showLoader`)

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.ts, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-L2VQ0rmm9hcaDvFqqvu:-L2VQ0rmm9hcaDvFqqvv:by7ohau) ([raw file](https://github.com/kaltura/kmc-ng/blob/97ff0c4c6f61af92bf84c240c0e1416a79903ab3/src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.ts#L29)):*
> ```XML
>     }else
>     {
>         this.assignEmptyMessage();
> ```

we simplified the assign empty message logic so it will be always visible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/341)*

**Comment by diamond-darrell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts, line 75 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-L2VPcYJd9r6c3m0l5xk:-L2VQ7Vu-ko4SeViVqg3:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/98f59103095c9a652dd77edb1ccf397999a3cb94/src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts#L75)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I removed this state because it is duplication of the underline class that also has loader state (`_showLoader`)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-:-L2VQI_CHR5-wai9UD2N:bnfp4nl)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.ts, line 29 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-L2VQ0rmm9hcaDvFqqvu:-L2VQcLdrIHyCbDc-7Bj:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/97ff0c4c6f61af92bf84c240c0e1416a79903ab3/src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.ts#L29)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we simplified the assign empty message logic so it will be always visible
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/341)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/341#-:-L2YpJIMJSnVg-xI33ld:bnfp4nl)*

**Pull request merged**
