### PR TITLE
feat: Settings> Account-Information

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/378)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/applications/settings-account-information-app/settings-account-information.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f-qrfFmrHHMH4HIy6:-L4f-qrfFmrHHMH4HIy7:bu1tbxn) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/settings-account-information.service.ts#L20)):*
> ```XML
> 
> @Injectable()
> export class SettingsAccountInformationService {
> ```

consider checking that 'environment.....force' exists (use try...catch...) and don't show the form if it doesn't exists or invalid uri. write warn if this is the case 

---

*[src/applications/settings-account-information-app/settings-account-information.service.ts, line 34 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2EepTiZLosUZ7Bth:-L4f2EepTiZLosUZ7Bti:bqw0u52) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/settings-account-information.service.ts#L34)):*
> ```XML
>     return this._kalturaServerClient.request(new PartnerGetStatisticsAction())
>       .map((response: KalturaPartnerStatistics) => ({
>           bandwidth: response.bandwidth ? response.bandwidth.toFixed(2) : this._appLocalization.get('app.common.n_a'),
> ```

consider moving the translation to the component.ts

---

*[src/applications/settings-account-information-app/account-info/account-info.component.ts, line 30 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2iwk534abdlLDThm:-L4f2iwk534abdlLDThn:b-20m857) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/account-info/account-info.component.ts#L30)):*
> ```XML
> 
>       this._trialExpirationDateString =
>         (new DatePipe()).transform(this._appAuthentication.appUser.createdAt.getTime() + trialPeriod, 'MM/DD/YYYY'); // "01/15/1992"
> ```

use moment instead of DatePipe

---

*[src/applications/settings-account-information-app/account-info/account-info.component.ts, line 42 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2nguW72PsEhr0m86:-L4f2nguW72PsEhr0m87:be5lic4) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/account-info/account-info.component.ts#L42)):*
> ```XML
>         this._isBusy = false;
>         this._bandwidth = bandwidth;
>         this._storage = storage;
> ```

you are missing the catch part with blocker message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378)*

**Comment by esakal** [comment]
Reviewed 5 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/settings-account-information-app/settings-account-information.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f-qrfFmrHHMH4HIy6:-L4kZUMvFE605h8uhI4V:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/settings-account-information.service.ts#L20)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider checking that 'environment.....force' exists (use try...catch...) and don't show the form if it doesn't exists or invalid uri. write warn if this is the case 
</blockquote></details>

Done.

---

*[src/applications/settings-account-information-app/settings-account-information.service.ts, line 34 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2EepTiZLosUZ7Bth:-L4kZVizASz5PhvbSjez:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/settings-account-information.service.ts#L34)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider moving the translation to the component.ts
</blockquote></details>

Done.

---

*[src/applications/settings-account-information-app/account-info/account-info.component.ts, line 30 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2iwk534abdlLDThm:-L4k_OSNUEZZ34oVtww0:b-twn652) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/account-info/account-info.component.ts#L30)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

use moment instead of DatePipe
</blockquote></details>

Decided to leave it like this and clean the moment from other places

---

*[src/applications/settings-account-information-app/account-info/account-info.component.ts, line 42 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4f2nguW72PsEhr0m86:-L4k_iUII_DTzKuT2sCC:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/2a13dbf45821befc4d7af8a6c4450aab568a7939/src/applications/settings-account-information-app/account-info/account-info.component.ts#L42)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you are missing the catch part with blocker message
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 2 of 24 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-:-L4kf7svR8Y4F3vj4rjR:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 16 of 24 files at r1, 4 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/i18n/en.json, line 1659 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4oas01BTJT3BfKQeIR:-L4oas02qsa8_poEn_gT:b-orfoed) ([raw file](https://github.com/kaltura/kmc-ng/blob/4b589598a1fcce5f6d12fe0b8998c2b142799279/src/i18n/en.json#L1659)):*
> ```JSON
>         "accountInfo": {
>           "header": "We are excited that you’re looking for more info on upgrading your account!",
>           "trial": "Your Free trial will expire at {{0}}",
> ```

+@benstov  - please use the text specified in the PRD and not in the design

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378)*

**Comment by benstov** [comment]
Review status: 13 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/i18n/en.json, line 1659 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/378#-L4oas01BTJT3BfKQeIR:-L4p80jpc2mzd1b4dX9C:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/4b589598a1fcce5f6d12fe0b8998c2b142799279/src/i18n/en.json#L1659)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

+@benstov  - please use the text specified in the PRD and not in the design
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/378)*

**Comment by esakal** [comment]
Reviewed 9 of 12 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/378)*

**Pull request merged**
