### PR TITLE
Live dashboard Integration

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/391)

### CODE REVIEW

**Comment by benstov** [comment]
@esakal  @amirch1 
Please notice there are 2 TODOs with text: “todo: override from configuration".
It will be implemented once Eran will push his configurations files modifications.

**Comment by benstov** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 292 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/391#-L4pxwiItZ9DtUUUN5Mp:-L4pxwiItZ9DtUUUN5Mq:b-6j17a5) ([raw file](https://github.com/kaltura/kmc-ng/blob/e5bf98d5fc30132505861f035240d595d08325b1/src/shared/kmc-shell/providers/browser.service.ts#L292)):*
> ```XML
> 	}
> 
>   public handleUnpermittedAction(reason: UnpermittedActionReasons, navigateTo?: string): void {
> ```

@esakal I haven't implemented it with observable<void> for few reasons.
Amir and I didn't quite understand why should you get an observable so if you can please let us know (that's why i called you, sorry for that).
And also there's a problem of navigating in the middle of subscribe, the code inside the subscribe won't get executed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/391)*

**Comment by benstov** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/studio-app/studio.component.ts, line 17 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/391#-L4pz3lu69CvFdawbbYh:-L4pz3lu69CvFdawbbYi:bh1ov68) ([raw file](https://github.com/kaltura/kmc-ng/blob/e5bf98d5fc30132505861f035240d595d08325b1/src/applications/studio-app/studio.component.ts#L17)):*
> ```XML
>   public studioUrl = '';
> 
>   constructor(private appAuthentication: AppAuthentication, private _appEvents: AppEventsService, private logger: KalturaLogger, private browserService: BrowserService) {
> ```

moved the code from the ctor to ngOnInit for the sake of not checking the enabled flag in both places.
I also removed the prod flag from here so the behaviour will be the same as usageDashboard in the matter of using only the URL as indicator whether to show component or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/391)*

**Comment by benstov** [comment]
Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entry/entry-live/live-dashboard/live-dashboard.component.ts, line 26 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/391#-L4pzcZ7gJfQ8TclhtTx:-L4pzcZ7gJfQ8TclhtTy:bk8qsjs) ([raw file](https://github.com/kaltura/kmc-ng/blob/e5bf98d5fc30132505861f035240d595d08325b1/src/applications/content-entries-app/entry/entry-live/live-dashboard/live-dashboard.component.ts#L26)):*
> ```XML
>     }
> 
>     if (!serverConfig.externalApps.liveDashboard.enabled) {
> ```

Didn't use the browserService unpermittedAction function since this component is a part of entry and not a standalone one.
However I do show a message as before that the dashboard cannot be loaded (just not as an alert as in studio and usageDashboard)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/391)*

**Comment by esakal** [comment]
Reviewed 5 of 8 files at r1, 6 of 14 files at r2, 9 of 16 files at r4, 5 of 7 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/391)*

**Pull request merged**
