### PR TITLE
KMCNG-1656

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1656

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636)

### CODE REVIEW

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 14 of 16 files at r1, 2 of 2 files at r2, 6 of 9 files at r3, 12 of 18 files at r4, 2 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/636#-LC4W_D-6qGDP8wBOSCI:-LC4W_D-6qGDP8wBOSCJ:b-2m9wq4) (no related file):*
+@diamond-darrell please review my adjustments and LGTM or comment

---

*[src/applications/content-entries-app/entry/entry-components-list.ts, line 79 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/636#-LC4UrsxDcR20v_j0WWS:-LC4UrsyC0MfN4iluc4p:b-augl2h) ([raw file](https://github.com/kaltura/kmc-ng/blob/d22683f94f2423ca2dbff68c50368c26eaefd9a9/src/applications/content-entries-app/entry/entry-components-list.ts#L79)):*
> ```XML
>     EditDistributionProfileThumbnailsComponent,
>     EditDistributionProfileThumbnailItemComponent,
>     EntryEditorComponent
> ```

i removed the duplicated editor 

---

*[src/applications/content-entries-app/entry/entry-store.service.ts, line 392 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/636#-LC4K_GvB_NBzE7e5rjF:-LC4K_GvB_NBzE7e5rjG:buqnkba) ([raw file](https://github.com/kaltura/kmc-ng/blob/064250c5e5f4704925a4856f4e687f216bfc31bb/src/applications/content-entries-app/entry/entry-store.service.ts#L392)):*
> ```XML
>   }
> 
>   public updateHasSourceStatus(value: boolean) : void {
> ```

consider using this  method during replace video once the user approve (or auto approve) the replace

---

*[src/applications/content-entries-app/entry/entry-store.service.ts, line 59 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/636#-LC4Uz5R1c8sqbdHz_VV:-LC4Uz5S8C9kpfj2jfuH:b-o7mr54) ([raw file](https://github.com/kaltura/kmc-ng/blob/d22683f94f2423ca2dbff68c50368c26eaefd9a9/src/applications/content-entries-app/entry/entry-store.service.ts#L59)):*
> ```XML
> 	}
> 
>     private _hasSource = new BehaviorSubject<boolean>(false);
> ```

we need to propogate this value so the `editor button will update its availablity when: 
1. user deletes a source
2. user approve replace video

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636#-:-LC4WZ0K2LmQWSxHg4sC:bnfp4nl)*

**Comment by diamond-darrell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-store.service.ts, line 392 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/636#-LC4K_GvB_NBzE7e5rjF:-LC4XOXy4eASHaw9lCwC:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/064250c5e5f4704925a4856f4e687f216bfc31bb/src/applications/content-entries-app/entry/entry-store.service.ts#L392)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider using this  method during replace video once the user approve (or auto approve) the replace
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636#-:-LC4XTQxE-7qjSBjJ01i:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636#-:-LC8C9jA8qrBpkyBAtGu:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 1 of 16 files at r1, 2 of 2 files at r2, 6 of 9 files at r3, 10 of 18 files at r4, 2 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/636#-:-LC8CUYb6_kSp873gNQD:bnfp4nl)*

**Pull request merged**
