### PR TITLE
KMCNG-439 Playlist Details - metadata suggested tags

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/191)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Krk91mDprETqf06YZFe:-Krk91mDprETqf06YZFf:b-jxzkp9) (no related file):*
regarding styles - please see attached image. The text area should get a style like in entry details description (colors, padding-left). Ther should be a larger padding on the right hand side (check invision). 

Other than that - looks great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Krk9iqtz4cyI63YCBYL:-Krk9iqtz4cyI63YCBYM:b-dp7kyf) (no related file):*
can't seem to edit previous comment - this is the correct image:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by konstantin-stepanets** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Krk91mDprETqf06YZFe:-Krkp_93DPbi2cg_eQAi:b-45tqpm) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

regarding styles - please see attached image. The text area should get a style like in entry details description (colors, padding-left). Ther should be a larger padding on the right hand side (check invision). 

Other than that - looks great!
</blockquote></details>

OK. I have updated the padding. Fields should have the similar styles like for entry metadata. To be honest, don't know, why a usual <textarea pInputTextarea></textarea>  could has the different styles at these pages. Was fixed this strange issue by adding manually the several extra primeng css classes.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Krk9iqtz4cyI63YCBYL:-KrkpVJ3DS1eGdSlC0pz:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

can't seem to edit previous comment - this is the correct image:


</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-:-Ks3Ya3iaxpdlVUmRKCX:bnfp4nl)*

**Comment by esakal** [comment]
waiting for +@amirch1 to reply on the comment about [Add suggested tag to list of tags requirement ](https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/222780051/Content+Playlist+Details+Metadata). we might need to close this PR without merging it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-:-Ks4EyD8BAODd7CwdXix:b9r7kag)*

**Comment by esakal** [comment]
:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-:-Ks4FoBQTGcu3oHqJEd8:b8b79qu)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks4FtxFTvgRL_1x6zRZ:-Ks4FtxFTvgRL_1x6zR_:b8iw02x) (no related file):*
:lgtm_cancel: 
waiting for +@amirch1 to reply on the comment about [Add suggested tag to list of tags requirement ](https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/222780051/Content+Playlist+Details+Metadata). we might need to close this PR without merging it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by esakal** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html, line 16 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks7IIFLvjETdAkl2LUE:-Ks7IIFLvjETdAkl2LUF:b-80tuxv) ([raw file](https://github.com/kaltura/kmc-ng/blob/a73fa146b2ebc6738779f254cc5d60e1ef2cd738/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html#L16)):*
> ```HTML
>         <span class="kLabel">{{'applications.content.playlistDetails.metadata.description' | translate}}</span>
>         <div class="kControl">
>           <textarea formControlName="description" class="threeRows ui-widget ui-inputtext" pInputTextarea></textarea>
> ```

no need for the ui-widget ui-inputtext classes

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts, line 100 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks7IT9Spg3vjoYTmL-f:-Ks7IT9Spg3vjoYTmL-g:b-ye5wrq) ([raw file](https://github.com/kaltura/kmc-ng/blob/a73fa146b2ebc6738779f254cc5d60e1ef2cd738/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts#L100)):*
> ```XML
>   }
> 
>   _getSelectedValue(value): void {
> ```

can be removed as the tags component already handles duplicates

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191)*

**Comment by amirch1** [comment]
PRD updated - no need for additional check for duplicates

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-:-Ks7Ods3XoWoIS0egFZc:b-7kr28d)*

**Comment by konstantin-stepanets** [comment]
OK

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks4FtxFTvgRL_1x6zRZ:-Ks7QC-b_B-RvFpnm4uc:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

:lgtm_cancel: 
waiting for +@amirch1 to reply on the comment about [Add suggested tag to list of tags requirement ](https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/222780051/Content+Playlist+Details+Metadata). we might need to close this PR without merging it.
</blockquote></details>

OK

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html, line 16 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks7IIFLvjETdAkl2LUE:-Ks7QEh67yFen-oqMTU2:b-j1az26) ([raw file](https://github.com/kaltura/kmc-ng/blob/a73fa146b2ebc6738779f254cc5d60e1ef2cd738/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html#L16)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

no need for the ui-widget ui-inputtext classes
</blockquote></details>

I agree, but as I mentioned earlier, don't know why these "primeng" classes aren't automatically added to my textarea (so I have the wrong font-family, size, padding..). I removed these classes but had to add a few necessary styles to another class so the texteareas for the entry's and for playlist's metadata look the same now.

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts, line 100 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-Ks7IT9Spg3vjoYTmL-f:-Ks7RNOxl8sdQwvTUmt2:bci0dzd) ([raw file](https://github.com/kaltura/kmc-ng/blob/a73fa146b2ebc6738779f254cc5d60e1ef2cd738/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts#L100)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

can be removed as the tags component already handles duplicates
</blockquote></details>

Yes, they handles the duplicates, but they don't support the case sensitive tags, so I think some similar solution could be used in the appropriate shared place later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/191#-:-Ks7SOyG5c7yrJjEy2Cd:b32w0x)*

**Pull request closed without merging**
