### PR TITLE
feat: add section for downloading child entries

### PR DESCRIPTION
**Pull request by pnts-se**
### PR information

**What is the current behavior?**

It's difficult for users to download multivideo recordings
You have to use the API or at least browser developer tools

**What is the new behavior?**

This commit adds a "FlavoursChildren" section
It does not have all the features that the Flavour section has
It's only for downloading

twoChildren

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by pnts-se** [comment]
@amirch1 
Ah, I see how that can be problematic. I didn't consider clips.

I was looking for an easy way to let KMC administrators download multivideo recordings, e.g. Kaltura Capture dual screen recordings.

**Comment by pnts-se** [comment]
@amirch1 I would say that is a better solution than what I had in mind. 

But I would suggest also adding it for sourceType `LECTURE_CAPTURE 37`. That was one of the main reasons for me to do this, customers wanting to download their Kaltura Capture recordings.

**Comment by amirch1** [comment]
@pnts-se  - I see that the "Clips" tab is available for Webcast entries and lists all the recordings with links to the entries which allows downloading the recording flavors. Can you confirm that?
If indeed this is the case, the only change I think we should make is renaming "Clips" to "Recordings" for live and webcast entries.

**Comment by pnts-se** [comment]
@amirch1 Yes, I see the "Clips" tab. It's a nice feature!

But the raison d'etre for this PR is when there are multiple video streams.
That could be Kaltura Capture recordings, or perhaps recordings from Cattura recorders.

Consider this Kaltura Capture recording with camera + screen capture. In the clips tab I only see the parentEntry.
image

There is another entry though. It's needed in the KMC editor. When used, we're making a media->list call to get the child entry.

image

So, how do I download flavorAssets for this child entry?
Perhaps I do not have access to the recording, whereever it was made.
Now I need it for whatever reason.

I could manually find the entryid of the child entry and go to:
`/index.php/kmcng/content/entries/entry/0_hnbxvd14/flavours`

How could we make this available for KMC admins in an easy way?

I was way off, making a childFlavours component.
I would suggest making the child entry visible somewhere as a link.
Then we load it in entry component and leverage the functionality already in KMC.

Perhaps the link could be added here, right after the ID of the parentEntry
image

**Comment by amirch1** [comment]
@pnts-se  - so I've finished researching the issue and this is what I found:
1. For regular VOD entries, the clips tab lists the clips created from the entry using the rootEntryId filter. We do have an issue there which causes the original entry itself to be returned as well - I will fix it.
2. For live entries, the clips tab shows the live entry recordings using the same rootEntryId filter. I think we should change the tab name from "Clips" to "Recordings" for live entries and remove the "Clip & Trim" button there as it redirected to the VOD entry anyhow.
3. For Lecture Capture, the children entries are not listed in the "Clips" tab as we need to fetch them using the "parentEntryId" and not using the rootEntryId filter. I think we need to add a new tab for lecture capture only to list its children which will allow quick navigation to these entries (and of course flavors download).

I will pass all this info to our product team and hopefully they will approve the required changes.

**Comment by pnts-se** [comment]
@amirch1 That sounds like good changes. Let's hope the product team approves of them.

Thank you for a good discussion! If it's alright with you, I'll go ahead and close the PR.

**Pull request closed without merging**
