### PR TITLE
Permissions selector

### PR DESCRIPTION
**Pull request by diamond-darrell**
## Review along with https://github.com/kaltura/kaltura-ng/pull/102

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/224362071/Role+permissions

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/503)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 32 of 34 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8fqtp-3m2dHW9gV9Rg:-L8fqtp-3m2dHW9gV9Rh:bxwgew5) (no related file):*
we need to figure out why the order of the rows are not according to the json filexx

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gKX7oBjslb0zOT_Rt:-L8gKX7oBjslb0zOT_Ru:brj8fza) (no related file):*
update layout of permissions dropdown according to invision

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gK_jG0d9IvnAp48c3:-L8gK_jG0d9IvnAp48c4:b-459vgj) (no related file):*
if a row is invalid:
1. show the following generic message
2. use the icon as we have in file upload to indicate on a validation issue. use the following tooltip: "select permissions or disable the features set"



---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by diamond-darrell** [comment]
Review status: 21 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gKX7oBjslb0zOT_Rt:-L8gkj9y8k8Eev8FZ5zc:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

update layout of permissions dropdown according to invision
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gK_jG0d9IvnAp48c3:-L8gm4CE-rOR35e6jZZH:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

if a row is invalid:
1. show the following generic message
2. use the icon as we have in file upload to indicate on a validation issue. use the following tooltip: "select permissions or disable the features set"



</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gKX7oBjslb0zOT_Rt:-L8hFJCSDpcgGYGNQbhJ:b-qdv0jc) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

nice, I pushed another fix that hide the all permission checkbox while the user filter the list, please pull

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hFOmGCe3vCG6yBZ3d:-L8hFOmGCe3vCG6yBZ3e:bm6o98e) (no related file):*
the validation error icon should be shown only when the user tries to save as we are doing in other places.
scenario:
1. switch on content injestion
2. un select all permissions

the error icon is shown immediately. should be only after the user tries to save. 



---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHI4vE-ZIgH25xNDG:-L8hHI4vE-ZIgH25xNDH:b-2een0d) (no related file):*
saving a change of one permission deleted all the other permissions and left only the row permission...

I tried to reproduce it but failed, can you try it on your own?

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHSnMAD_lt3HJp07t:-L8hHSnMAD_lt3HJp07u:baq287b) (no related file):*
duplicating a role opens the rule popup with the button save enabled

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHWZb6o9xSGvHQV3R:-L8hHWZb6o9xSGvHQV3S:b-hzrmou) (no related file):*
changing a duplicated role immediately after creating it doesn't save the changes (nor update the roles list) - happens only if you change the permission tree, changing the role name will work as expected

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gK_jG0d9IvnAp48c3:-L8hHwHq8H71OLvdVyah:b7qo93y) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

typo in the tooltip message (permission instead of permissions)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gKX7oBjslb0zOT_Rt:-L8hIYnf5ZkMxXpw1nSL:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

nice, I pushed another fix that hide the all permission checkbox while the user filter the list, please pull
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8gK_jG0d9IvnAp48c3:-L8hI_COBFLSTOaAPpRn:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

typo in the tooltip message (permission instead of permissions)
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hFOmGCe3vCG6yBZ3d:-L8kUISfD_r8CLvB1Aaw:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the validation error icon should be shown only when the user tries to save as we are doing in other places.
scenario:
1. switch on content injestion
2. un select all permissions

the error icon is shown immediately. should be only after the user tries to save. 



</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHSnMAD_lt3HJp07t:-L8kXb2yCYFB9wMauNtp:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

duplicating a role opens the rule popup with the button save enabled
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHWZb6o9xSGvHQV3R:-L8kXcA-3RA-Nx7eHajX:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

changing a duplicated role immediately after creating it doesn't save the changes (nor update the roles list) - happens only if you change the permission tree, changing the role name will work as expected
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-L8hHI4vE-ZIgH25xNDG:-L8kXm6c3XxvN-TN7MzL:bdz4y04) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

saving a change of one permission deleted all the other permissions and left only the row permission...

I tried to reproduce it but failed, can you try it on your own?
</blockquote></details>

I couldn't reproduce it as well

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503#-:-L8kuk9m3h0rsB2K3dEp:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/503)*

**Pull request merged**
