### PR TITLE
Check all entry sections that uploading files and make sure they handle relevant statuses

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/266)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KylxD3pUgfjxwe5TQYV:-KylxD3qaa4w3VE97U3h:bvcseux) (no related file):*
Did you reviewed other file upload based sections like:
- flavor
- captions
- thumbnail
- upload entry
- bulk upload

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KylylN8TCGCEivaKV-H:-KylylN8TCGCEivaKV-I:b-cctpvi) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L66)):*
> ```XML
> 
> 
>   private _trackUploadFiles(): void {
> ```

I think you didn't handle several scenarios:
- you update the `isBusy` to false only during `prepared` phase but you didn't handle 'failure' and also you didn't handle multiple uploads.
- setting is busy to true during `added` state seems more natural then doing it in an other function
- you show uploading immediately when adding a file but if the user is currently uploading entries, the upload will be on status 'pending'
- what about `pendingUpload` which is a relevant status when the user resume a failed upload? maybe it doesn't happen in related but it might happen in entry upload for example, check if it was handled there correctly. 

We can map all the relevant scenario together if you wish to.

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 87 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kym0TLQgjWJ-b0A_CLP:-Kym0TLQgjWJ-b0A_CLQ:bu3zf1l) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L87)):*
> ```XML
>             case TrackedFileStatuses.prepared:
>               relevantRelatedFile.serverUploadToken = (<NewEntryRelatedFile>uploadedFile.data).serverUploadToken;
>               this.updateState({ isBusy: false });
> ```

You can remove the isBusy flag after preparation only if the file upload continues after the user saves the entry. It means that you choose to allow uploading the file in the background after the user saves the file and move on to other area in the application. But then you must address advanced scenarios like:
- when user save the file you should continue to upload files that has a matching related record. Currently the code cancel them as shown in the snapshot below
  - also, we get an error as shown in the snapshot below.
- the user can add a file to upload then remove it before he saves or leave the entry without saving, you should make sure you cancel relevant uploads in this scenario
- the user can start an upload then save entry, go to another entry and come back. We should show the related file upload current progress and allow him to cancel. 
- we should notify the product that the user has no indication that a file is currently being uploaded 

The scenarios above are relevant to any sections that currently upload a file. 

We have an alternative, but since you updated the `prepared` state I assume you wanted to support this one. 

Lets discuss with +@amirch1.



---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 233 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kylxoaz37FZ8a4bWZ12:-Kylxob-Ycimps3uj4gf:bfyg4rr) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L233)):*
> ```XML
> 		this._relatedFiles.next({items: files});
> 
>     this.updateState({ isBusy: true });
> ```

consider using the state `added` instead? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KylxD3pUgfjxwe5TQYV:-KyoH4A6_Ok1EYetfcdA:b-290qdn) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Did you reviewed other file upload based sections like:
- flavor
- captions
- thumbnail
- upload entry
- bulk upload
</blockquote></details>

I haven't checked upload entry since it was developing along with the new upload-management (I'll check it). For flavors - upload-management is not used (`ThumbAssetAddFromImageAction` is used instead).

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KylylN8TCGCEivaKV-H:-KyoFwL3uZSjvUkLNLTJ:bl5p3if) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L66)):*
Regarding `added` state - yes, I was considering to use `added` status, but since putting `filter` on a relevant file this one is not being called. I haven't found out why the request cancels, but it's definitely related to this error and once I prevent this error request is not canceled anymore on save. I put a filter on the top because otherwise, I need to check if there's relevant entry every time I want to perform some operation with it. 

> We can map all the relevant scenario together if you wish to.
I will check it again, sorry, I should have clarified this before, but I thought I got the meaning of the task.  

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 87 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kym0TLQgjWJ-b0A_CLP:-KyoDfUvpBtvX0Tksn0d:bqxsqs7) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L87)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

You can remove the isBusy flag after preparation only if the file upload continues after the user saves the entry. It means that you choose to allow uploading the file in the background after the user saves the file and move on to other area in the application. But then you must address advanced scenarios like:
- when user save the file you should continue to upload files that has a matching related record. Currently the code cancel them as shown in the snapshot below
  - also, we get an error as shown in the snapshot below.
- the user can add a file to upload then remove it before he saves or leave the entry without saving, you should make sure you cancel relevant uploads in this scenario
- the user can start an upload then save entry, go to another entry and come back. We should show the related file upload current progress and allow him to cancel. 
- we should notify the product that the user has no indication that a file is currently being uploaded 

The scenarios above are relevant to any sections that currently upload a file. 

We have an alternative, but since you updated the `prepared` state I assume you wanted to support this one. 

Lets discuss with +@amirch1.



</blockquote></details>

We have to wait by `prepared` state because in this one we get the `serverUploadToken` needed to link an entry and an upload file.

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 233 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kylxoaz37FZ8a4bWZ12:-KyoH2GPQw4Jpcyrl4de:b-wfxxxd) ([raw file](https://github.com/kaltura/kmc-ng/blob/b9961a1bc09c6ae8bb249e5fd14dd1e8550c71cc/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L233)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider using the state `added` instead? 
</blockquote></details>

Answered above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KylxD3pUgfjxwe5TQYV:-KypsMRwicgnd3enkDgU:b-ltfojh) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I haven't checked upload entry since it was developing along with the new upload-management (I'll check it). For flavors - upload-management is not used (`ThumbAssetAddFromImageAction` is used instead).
</blockquote></details>

Bulk upload is using action instead of upload-management as well as thumbnails

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 152 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytROsXDxsRIX_lFVPX:-KytROsXDxsRIX_lFVPY:b-9qjo30) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L152)):*
> ```XML
>       .do(response => {
>         // set file type
>         response.objects.map((asset: RelatedFile) => {
> ```

I know it is minor but this function is a bit long and also is doing both the activation flow and the manipulation of the data. if you can separate them it might be better. you choice

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 157 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytQiFODYiXbP-8K30o:-KytQiFODYiXbP-8K30p:b-qtg0nt) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L157)):*
> ```XML
>           }
> 
>           const trackedFiles = this._uploadManagement.getTrackedFiles().filter(file => file.data instanceof NewEntryRelatedFile);
> ```

consider removing this and using the `find` you did to assign `relevantFile` below instead to fin using both conditions. this will improve performance and will not affect the logic

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 220 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytSgcZM8iec0BoBdBw:-KytSgcZM8iec0BoBdBx:b-6xfq7w) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L220)):*
> ```XML
>                   this._cancelUpload(newAsset);
>                 } else {
>                   const relevantAsset = this._relatedFiles.getValue().items
> ```

consider setting the assetId directly on the relevant file in upload management

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 233 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytzKb3cFMTUIIycyxE:-KytzKb3cFMTUIIycyxF:b-ah4dw4) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L233)):*
> ```XML
>           changes.forEachRemovedItem((record: IterableChangeRecord<RelatedFile>) => {
>             // remove deleted assets
>             const deleteAssetRequest = new AttachmentAssetDeleteAction({ attachmentAssetId: (record.item as RelatedFile).id });
> ```

remove upload if necessary 

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 283 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytSwxWvqqW-YoBizNR:-KytSwxWvqqW-YoBizNS:b-cb640k) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L283)):*
> ```XML
>     this._relatedFiles.next({ items: this._relatedFiles.getValue().items.filter((item: RelatedFile) => item !== file) });
> 
>     this._uploadManagement.cancelUpload(file.uploadFileId);
> ```

only relevant for new files not currently part of the entry

---

*[src/applications/content-entries-app/entry/entry-related/entry-related.component.html, line 28 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytTRtauZkMrblhhJ00:-KytTRtauZkMrblhhJ01:b-97dma1) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related.component.html#L28)):*
> ```HTML
> 				<p-column field="id" header="{{'applications.content.entryDetails.related.assetId' | translate}}">
> 					<ng-template let-col let-file="rowData" pTemplate="body">
> 						<div *ngIf="!file.uploadFailure">
> ```

cosdier simplification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: 2 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 152 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytROsXDxsRIX_lFVPX:-Kyu4u_4ZGml8J0-dQTy:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L152)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I know it is minor but this function is a bit long and also is doing both the activation flow and the manipulation of the data. if you can separate them it might be better. you choice
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 157 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytQiFODYiXbP-8K30o:-Kyu4vmcvb206JMAqp-k:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L157)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider removing this and using the `find` you did to assign `relevantFile` below instead to fin using both conditions. this will improve performance and will not affect the logic
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 220 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytSgcZM8iec0BoBdBw:-Kyu4x07tfZbDAFZCq0u:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L220)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider setting the assetId directly on the relevant file in upload management
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 233 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytzKb3cFMTUIIycyxE:-KyuMEdeU40D_lBulfyr:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L233)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

remove upload if necessary 
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts, line 283 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytSwxWvqqW-YoBizNR:-KyuMFIM-CNLaE519AsY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts#L283)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

only relevant for new files not currently part of the entry
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related.component.html, line 28 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KytTRtauZkMrblhhJ00:-KyuMG0uF8pRbMMXonRF:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/03d4ca552f9d6e7562a307d34fbb119ccca25d10/src/applications/content-entries-app/entry/entry-related/entry-related.component.html#L28)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

cosdier simplification
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by esakal** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyuoZLoAWfIuRNU5jXp:-KyzAj21UEmpwHkdLwre:be6q19l) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Flavors section is using upload management, but we cannot do anything to upload after the upload has started. Also, we don't need to update `busy state` and status of upload received from the server, so a user needs to refresh the list to see changes, I assume it's done by design. 
</blockquote></details>

OK you are right, flavors doesn't need any special care

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzB2goIFBzaEzTHb35:-KyzB2goIFBzaEzTHb36:byi4r91) (no related file):*
performance enhancement # 1:

our tracked files list is actually an hash map. but since we didn't expose a public function to get specific file you need each time to :
1. call `getTrackedFiles` - which convert the complete hash map to array
2. traverse on that array to find the specific one.

instead all we need to do it to add the following function to upload management:

```
public getTrackedFile(fileId: string): TrackedFileData
    {
        const relevantFile = this._trackedFiles[fileId];
        return relevantFile? relevantFile.asData() : null;
    }
```

wdyt?



---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 73 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyyvW_-UnOYF9IUolg9:-KyyvW_-UnOYF9IUolgA:b-o1l9rp) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L73)):*
> ```XML
>   private _syncBusyState(): void {
>     const trackedFiles = this._uploadManagement.getTrackedFiles();
>     const relevantFiles = this._captions.getValue()
> ```

performance enhancement # 1

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 143 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kyyv8VAjy7QaQL1ECht:-Kyyv8VAjy7QaQL1EChu:b-wbv3cn) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L143)):*
> ```XML
>       .monitor('get captions')
>       .do(response => {
>         // WARN: mutating of the response object
> ```

why do you warn? the mutation is part of the design 

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 169 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyyvQDnefw6-LC12R9L:-KyyvQDnefw6-LC12R9M:b-o1l9rp) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L169)):*
> ```XML
>   private _updateCaptionsResponse(response): void {
>     response.objects.forEach((caption: CaptionRow) => {
>       const relevantFile = this._uploadManagement.getTrackedFiles().find(file =>
> ```

performance enhancement # 1

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 249 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyywkZW5Lm4z2rNebr-:-KyywkZW5Lm4z2rNebr0:b-aspffl) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L249)):*
> ```XML
>     this._captions.next({ items: captions });
>     this.currentCaption = newCaption;
>     this.updateState({ isBusy: true });
> ```

should be done only if the user starts the upload. here you only open the popup. the user can close the popup without starting to upload the file. I think you will need to use the `added` state eventually :)

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 330 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kyz4XSJxwgiNFcojKZS:-Kyz4XSJxwgiNFcojKZT:b-o1l9rp) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L330)):*
> ```XML
>                     this._uploadManagement.cancelUpload(newCaption.uploadFileId, true);
>                   } else {
>                     const relevantUploadFile = this._uploadManagement.getTrackedFiles().find(file =>
> ```

performance enhancement # 1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzBxUPcXkklQtEodpo:-KyzBxUPcXkklQtEodpp:bewf9rs) (no related file):*
it seems that we support chunk upload in upload entry so we need to conditionally use the file size limitation of 2Gb according to the chunk upload support.

I will need to add such a function that you will be able to query in the `kaltura-typescript-client`.

If I will manage to do it soon it will be part of this task, otherwise we will handle it later in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzB2goIFBzaEzTHb35:-KyzF6y8SPl_BLOIvdT1:b-irl63o) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

performance enhancement # 1:

our tracked files list is actually an hash map. but since we didn't expose a public function to get specific file you need each time to :
1. call `getTrackedFiles` - which convert the complete hash map to array
2. traverse on that array to find the specific one.

instead all we need to do it to add the following function to upload management:

```
public getTrackedFile(fileId: string): TrackedFileData
    {
        const relevantFile = this._trackedFiles[fileId];
        return relevantFile? relevantFile.asData() : null;
    }
```

wdyt?



</blockquote></details>

Sounds reasonable - [PR](https://reviewable.io/reviews/kaltura/kaltura-ng/34)

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzBxUPcXkklQtEodpo:-KyzDPHqJmhCPUOWO59s:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

it seems that we support chunk upload in upload entry so we need to conditionally use the file size limitation of 2Gb according to the chunk upload support.

I will need to add such a function that you will be able to query in the `kaltura-typescript-client`.

If I will manage to do it soon it will be part of this task, otherwise we will handle it later in the future.


</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 73 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyyvW_-UnOYF9IUolg9:-KyzGUhzEOQvetz4Y44h:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L73)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

performance enhancement # 1
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 143 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kyyv8VAjy7QaQL1ECht:-KyzDSgfNq2twxcvV8AV:b-77k5i) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L143)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

why do you warn? the mutation is part of the design 
</blockquote></details>

I know, maybe `warn` caption is not needed, it's just I used to use immutable approach so much, so for now when I see a code that mutates something I think it can confuse others 🙂
Will remove this comment 

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 169 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyyvQDnefw6-LC12R9L:-KyzGWGo6wexGjBOojIL:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L169)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

performance enhancement # 1
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 249 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyywkZW5Lm4z2rNebr-:-KyzETBqRVbX3EhYuFm8:b-lnr652) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L249)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

should be done only if the user starts the upload. here you only open the popup. the user can close the popup without starting to upload the file. I think you will need to use the `added` state eventually :)
</blockquote></details>

We already discussed it, `added` state fires before there's actual relevant file, so we will miss it. I'll look for a better place for it

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 330 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-Kyz4XSJxwgiNFcojKZS:-KyzGXYTBiCvoJNodoFf:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L330)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

performance enhancement # 1
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts, line 169 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyyvQDnefw6-LC12R9L:-KyzJoL2WPiqAWh7EQXC:b-6hls25) ([raw file](https://github.com/kaltura/kmc-ng/blob/0a53f30b62c434d1f3e0f23b99ab27a44802aaba/src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts#L169)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

actually, here we search not by tracked file id, but by captionId we've set `onDataSaving` hook, so we need to leave it as is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzBxUPcXkklQtEodpo:-KyzWuuyZ0Oa57ucmqOK:b-ut6f92) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

done :) 

please pull the branch in kaltura-ng you just created and build [pr](https://reviewable.io/reviews/kaltura/kaltura-ng/34). then use the following to decide if you should validate the file size or not

```
this._uploadManagement.supportChunkUpload(new NewEntryCaptionFile(null))
```
replace `NewEntryCaptionFile` with the file you are using to upload.

If you can do it in:
- flavor
- related 
- entry upload

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/266#-KyzBxUPcXkklQtEodpo:-Kyzfv0MznVKrEukPPfW:bb6un1j) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

done :) 

please pull the branch in kaltura-ng you just created and build [pr](https://reviewable.io/reviews/kaltura/kaltura-ng/34). then use the following to decide if you should validate the file size or not

```
this._uploadManagement.supportChunkUpload(new NewEntryCaptionFile(null))
```
replace `NewEntryCaptionFile` with the file you are using to upload.

If you can do it in:
- flavor
- related 
- entry upload

</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/266)*

**Pull request merged**
