### PR TITLE
Custom Data: Save is not optional after deleting one value in an unlimited field

### PR DESCRIPTION
**Pull request by diamond-darrell**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/233)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
It was a very confusing bug :slightly_smiling_face: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/233#-:-KwEzNxbijCEsQVEuyBt:bfu37vm)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts, line 89 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/233#-Kwjg1Kstylo0wrfmOjS:-Kwjg1Kstylo0wrfmOjT:b7wobyb) ([raw file](https://github.com/kaltura/kmc-ng/blob/f3565b343660c547e27aecd55b5401c709cf2896/src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts#L89)):*
> ```XML
>         Observable.merge(...formsChanges)
>             .cancelOnDestroy(this, this.widgetReset$)
>             .delay(0) // must defer to the next event cycle loop to get relevant form metadata
> ```

are you sure this is relevant to [kmcng-704](https://kaltura.atlassian.net/browse/KMCNG-704)? this subscriber doesn't touch any ui elements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/233)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts, line 89 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/233#-Kwjg1Kstylo0wrfmOjS:-KwjxvJrcWT2rJNWwNa2:b-z58jd7) ([raw file](https://github.com/kaltura/kmc-ng/blob/f3565b343660c547e27aecd55b5401c709cf2896/src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts#L89)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

are you sure this is relevant to [kmcng-704](https://kaltura.atlassian.net/browse/KMCNG-704)? this subscriber doesn't touch any ui elements
</blockquote></details>

you right, sorry, I've changed the title, it's related to https://kaltura.atlassian.net/browse/KMCNG-745

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/233)*

**Comment by esakal** [comment]
Thanks.

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/233)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/233#-KyGq6HPlc2gXGWo8KHe:-KyGq6HPlc2gXGWo8KHf:bns5tzk) (no related file):*
Let's try to resolve this bug later this month together

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/233)*

**Comment by esakal** [comment]
closing the PR for now, will be handled later

**Pull request closed without merging**
