### PR TITLE
feat: Preview & Embed

### PR DESCRIPTION
**Pull request by amirch1**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/308)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 11 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tX-Ko3t5R-b1LXL9k:-L0tX-Ko3t5R-b1LXL9l:b-wd4ijc) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L11)):*
> ```XML
> import { ContentEntriesAppService } from '../content-entries-app.service';
> import { AppEventsService } from 'app-shared/kmc-shared';
> import { PreviewAndEmbedEvent } from '../../../applications/preview-and-embed/preview-and-embed-event';
> ```

application should not depend on each other. you should add the app event in 'kmc-shared' which is exposed to all our applications

---

*[src/applications/content-entries-app/entry/entry-details/entry-details-widget.service.ts, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tXbBFjW_4pK42GsB3:-L0tXbBFjW_4pK42GsB4:b-yb3tdk) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-details/entry-details-widget.service.ts#L70)):*
> ```XML
>         }
> 
>         this.iframeSrc = `http//${environment.core.kaltura.cdnUrl}/p/${partnerID}/sp/${partnerID}00/embedIframeJs/uiconf_id/${UIConfID}/partner_id/${partnerID}?iframeembed=true&${flashVars}&entry_id=${entry.id}`;
> ```

1. aren't you missing : (`http://`)?
2. didn't we add http to the configuration?



comment 1

---

*[src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tXxx4qNyLemMhmcDO:-L0tXxx4qNyLemMhmcDP:b-k80pmq) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts#L66)):*
> ```XML
> 
>             this._urlHash = this._urlHash + 1;
>             result = `http://${environment.core.kaltura.cdnUrl}/p/${partnerID}/sp/${partnerID}00/embedIframeJs/uiconf_id/${UIConfID}/partner_id/${partnerID}?iframeembed=true&${flashVars}&entry_id=${entryId}&hash=${this._urlHash}`;
> ```

see comment 1

---

*[src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts, line 8 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tY-ngIXiZn8MP0Z99:-L0tY-ngIXiZn8MP0Z9A:b-vv8sn0) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts#L8)):*
> ```XML
> 
> import { AppEventsService } from 'app-shared/kmc-shared';
> import { PreviewAndEmbedEvent } from '../../../../applications/preview-and-embed/preview-and-embed-event';
> ```

see upper comment about location of app events in 'kmc-shared'

---

*[src/applications/preview-and-embed/preview-and-embed.module.ts, line 33 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tYZuVtzLDYq1ROFDB:-L0tYZuWw-II-Ol_byIk:b-pxaccz) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-and-embed.module.ts#L33)):*
> ```XML
>   ],
>   providers: [
>     PreviewEmbedService
> ```

is this singleton on purpose? consider putting it on the component unless you really need app level state management

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 162 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZTF7s_sMXAfhIEm-:-L0tZTF7s_sMXAfhIEm0:belrxt7) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L162)):*
> ```XML
>     const baseCdnUrl = environment.core.kaltura.cdnUrl.replace("http://","");
>     const securedCdnUrl = environment.core.kaltura.securedCdnUrl.replace("https://","");
>     return new window['kEmbedCodeGenerator']({
> ```

you should check if this one exists and if not handle such a scenario....

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 171 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_2ZocJvK1HnwyzbO:-L0t_2ZocJvK1HnwyzbP:b-z30e8x) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L171)):*
> ```XML
> 
>   private generateCode(isPreview = false): string{
>     this._previewLink = null;
> ```

i would wrap all this code with `try...catch` and handle it if needed.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 177 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_-Wo1kz3susPrYOl:-L0t_-Wo1kz3susPrYOm:b-k9vrn1) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L177)):*
> ```XML
>       protocol: this.getProtocol(isPreview),
>       embedType: this._previewForm.controls['selectedEmbedType'].value,
>       uiConfId: this._previewForm.controls['selectedPlayer'].value.id,
> ```

can 'value' be null?

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 211 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_BCWaeNOG3w66e4_:-L0t_BCWaeNOG3w66e4a:b-z30e8x) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L211)):*
> ```XML
> 
>   private getEmbedFlashVars(isPreview: boolean): any{
>     let flashVars =  {};
> ```

i would wrap all this code with `try...catch` and handle it if needed.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 239 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZgjPnRlPGpmeiiEC:-L0tZgjPnRlPGpmeiiED:b-1vigjq) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L239)):*
> ```XML
>   private flashVarsToUrl(flashVarsObject: any): string{
>       let params = '';
>       for( let i in flashVarsObject ){
> ```

consider checking that `flashVarsObject` is not null

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 247 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZmDbQF1t9izM9D8m:-L0tZmDbQF1t9izM9D8n:b-z30e8x) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L247)):*
> ```XML
> 
>   private createPreviewLink(isPreview: boolean):void{
>       let url = this.getProtocol(isPreview) + '://' + environment.core.kaltura.serverEndpoint + '/index.php/extwidget/preview';
> ```

i would wrap all this code with `try...catch` and handle it if needed.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 273 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_Hjv8SExNsmv8Qia:-L0t_Hjv8SExNsmv8Qib:b-facfuv) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L273)):*
> ```XML
>     newDoc.open();
>     newDoc.write('<!doctype html><html><head>' + style + '</head><body><div id="framePlayerContainer">' + this._generatedPreviewCode + '</div></body></html>');
>     newDoc.close();
> ```

i didn't run the code, just wondering if it will not close the document immediately

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/308)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 11 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tX-Ko3t5R-b1LXL9k:-L16MJUPEA51qGtQ9FFX:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L11)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

application should not depend on each other. you should add the app event in 'kmc-shared' which is exposed to all our applications
</blockquote></details>

Done.

---

*[src/applications/content-entries-app/entry/entry-details/entry-details-widget.service.ts, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tXbBFjW_4pK42GsB3:-L16RjQvRnUE6rIN42Kd:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-details/entry-details-widget.service.ts#L70)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

1. aren't you missing : (`http://`)?
2. didn't we add http to the configuration?



comment 1
</blockquote></details>

Done.

---

*[src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts, line 66 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tXxx4qNyLemMhmcDO:-L16RkPNz59WhXTzBr75:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts#L66)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see comment 1
</blockquote></details>

Done.

---

*[src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts, line 8 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tY-ngIXiZn8MP0Z99:-L16Rm53urNqQXpF83wr:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts#L8)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see upper comment about location of app events in 'kmc-shared'
</blockquote></details>

Done.

---

*[src/applications/preview-and-embed/preview-and-embed.module.ts, line 33 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tYZuVtzLDYq1ROFDB:-L16Xgppw-Sjil4NLnYU:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-and-embed.module.ts#L33)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is this singleton on purpose? consider putting it on the component unless you really need app level state management
</blockquote></details>

Done.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 162 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZTF7s_sMXAfhIEm-:-L16Xiez-Z2Gxn2fFczd:b-nc3rhu) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L162)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should check if this one exists and if not handle such a scenario....
</blockquote></details>

bundled with the app as asset. Added comment in code

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 171 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_2ZocJvK1HnwyzbO:-L16YhWk-h6rZ5Ymmet_:b-p1y16q) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L171)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

i would wrap all this code with `try...catch` and handle it if needed.
</blockquote></details>

There are no parameter values that might cause an error and the generator itself will return an error if the embed code template is invalid. So I can't think of a scenario in which we will get an error thrown.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 177 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_-Wo1kz3susPrYOl:-L16ZdmCSZArVdp1atYV:b-g09of4) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L177)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can 'value' be null?
</blockquote></details>

It is null when the form is created but the code generation occur only when a player is selected so it can't be null during code generation.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 211 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_BCWaeNOG3w66e4_:-L16awRqUqQuZ-DFo2TW:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L211)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

i would wrap all this code with `try...catch` and handle it if needed.
</blockquote></details>

Done.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 239 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZgjPnRlPGpmeiiEC:-L16b9To-DTNH0XBurJ4:b-bw0dr0) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L239)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider checking that `flashVarsObject` is not null
</blockquote></details>

as this is called with the object created by the getEmbedFlashVars function that now includes a try-catch - it will always get an object, could be an empty object but thats ok.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 247 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0tZmDbQF1t9izM9D8m:-L16eRojyzAq11NvL-sv:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L247)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

i would wrap all this code with `try...catch` and handle it if needed.
</blockquote></details>

Done.

---

*[src/applications/preview-and-embed/preview-embed.component.ts, line 273 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/308#-L0t_Hjv8SExNsmv8Qia:-L16hACrI6N4SSgA8N7U:b-a4nowm) ([raw file](https://github.com/kaltura/kmc-ng/blob/feb326895f676fa2d4cc5b95d940bae2ba5bdcb8/src/applications/preview-and-embed/preview-embed.component.ts#L273)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

i didn't run the code, just wondering if it will not close the document immediately
</blockquote></details>

verified on all supported browsers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/308)*

**Comment by esakal** [comment]
Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/308)*

**Comment by esakal** [comment]
Reviewed 4 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/308)*

**Pull request merged**
