### PR TITLE
fix(settings/custom-data): fix confirmation message for deleting a single schema

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1459

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/447)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/447#-L7JLSKpJ-K8NdzICqxv:-L7JLSKqkLyE5NH2KmIY:b3uwrc) (no related file):*
+@amirch1 shouldn't we have a space here (either new line or empty line)?




---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/447)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/447#-L7JLSKpJ-K8NdzICqxv:-L7Jve6XXSbPGkRuKudC:b-66onnf) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 shouldn't we have a space here (either new line or empty line)?




</blockquote></details>

yes - new line please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/447)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/447#-L7JLSKpJ-K8NdzICqxv:-L7O7j-XY0SYK4Lw4OeA:b-uuhidf) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

yes - new line please
</blockquote></details>

but it's already fixed here



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/447)*

**Comment by amirch1** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/447)*

**Pull request merged**
