### PR TITLE
KMCNG-1593

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1593

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/576)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576#-L9ZTY_75RuL8XpEY9az:-L9ZTY_75RuL8XpEY9b-:b5u50fm) (no related file):*
Seems that the original bug is caused when using a confirmation dialog without specifying a header. If we want to fix it across the app - there are 3 additional places we should handle for confirmations:
https://github.com/kaltura/kmc-ng/blob/6cc18e33cc56d1c5be8e34d5d7c30cb29933e111/src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-store.service.ts#L221-L221
https://github.com/kaltura/kmc-ng/blob/6beceb83378e3a488afc59e33d9ef3ea082a13ab/src/shared/content-shared/entries/link-entries-selector/linked-entries/linked-entries.component.ts#L210-L210
https://github.com/kaltura/kmc-ng/blob/c831726795d8f95914dc88bae9f58be99b700e56/src/applications/content-categories-app/category/category.service.ts#L193-L193
We need to also handle alerts without a header - there are many like this in the code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576#-L9ZTY_75RuL8XpEY9az:-LAE-09L-4yJUycRKOm9:b-ndwwrk) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Seems that the original bug is caused when using a confirmation dialog without specifying a header. If we want to fix it across the app - there are 3 additional places we should handle for confirmations:
https://github.com/kaltura/kmc-ng/blob/6cc18e33cc56d1c5be8e34d5d7c30cb29933e111/src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-store.service.ts#L221-L221
https://github.com/kaltura/kmc-ng/blob/6beceb83378e3a488afc59e33d9ef3ea082a13ab/src/shared/content-shared/entries/link-entries-selector/linked-entries/linked-entries.component.ts#L210-L210
https://github.com/kaltura/kmc-ng/blob/c831726795d8f95914dc88bae9f58be99b700e56/src/applications/content-categories-app/category/category.service.ts#L193-L193
We need to also handle alerts without a header - there are many like this in the code.

</blockquote></details>

+@amirch1 could you please merge current master in this branch, you've done some changes in the translations en.json file, I'm not sure which changes needed here

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576#-L9ZTY_75RuL8XpEY9az:-LAHzKo774cqwERRnwjd:b32w0x) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@amirch1 could you please merge current master in this branch, you've done some changes in the translations en.json file, I'm not sure which changes needed here
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/576)*

**Comment by esakal** [comment]
provide default header to handle future additions of alerts/confirmations

**Pull request closed without merging**
