### PR TITLE
KMCNG-1482

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1482

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653)

### CODE REVIEW

**Comment by esakal** [comment]
+@amirch1 please review and merge as part of the GA
-reviewer:@esakal 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653#-:-LDl_rKwDH__fOIlloFm:b-f94b0e)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/653#-LDoW8tQ1dGtXCKWkhqo:-LDoW8tQ1dGtXCKWkhqp:b-4cn3wl) (no related file):*
I don't think hiding the flags which fail to load is the correct approach - can we figure out why it fails to load? If a flag is missing - let us know and we will add it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653)*

**Comment by esakal** [comment]
imo we need both to add the missing flag and to keep the new behavior 
because in the attached snapshot in Jira all flags fail to load probabely 
due to network issue

**Comment by amirch1** [comment]
Agreed. In that case, please look at the attached screen captures - we also need to handle the flag missing in the table summary view.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653#-:-LDocPDv3wR12rtFgpsQ:b-ewz1yu)*

**Comment by diamond-darrell** [comment]
> Agreed. In that case, please look at the attached screen captures - we also need to handle the flag missing in the table summary view.

done

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/653#-LDoW8tQ1dGtXCKWkhqo:-LDonv6e8y68Ro2owMWW:b-egt1va) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

I don't think hiding the flags which fail to load is the correct approach - can we figure out why it fails to load? If a flag is missing - let us know and we will add it.
</blockquote></details>

Saint Martin's flag is missing, the country code is `mf`. Also, there's something wrong with Andorra's flag, a browser hide it itself, it's broken in the legacy as well


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653#-:-LDooaD9DGyjL04f9Wkk:bhep3hq)*

**Comment by diamond-darrell** [comment]
not relevant anymore in favor of https://github.com/kaltura/kmc-ng/pull/689

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/653#-:-LEEXSSZ17m0vJSD3Vtc:bnfp4nl)*

**Pull request merged**
