### PR TITLE
KMCNG-69

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/297)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jfVq_TTykzGJOgYdx:-L-jfVq_TTykzGJOgYdy:b-7hw89q) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L37)):*
> ```XML
> }
> 
> export class ExtendedKalturaPlaylist extends KalturaPlaylist {
> ```

see "comment 1"

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 192 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-X7c_utk4Ti0D6C3q5:-L-X7c_vSd27EUdxdM0V:b-4pcp1u) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L192)):*
> ```XML
>           if (currentPlaylistId !== this._playlistId) {
>             if (currentPlaylistId === 'new') {
>               const newData = this._playlistCreationService.getNewPlaylistData();
> ```

I saw that you moved some function from  `PlaylistsStore`. if you don't need them there  anymore then remove them



---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 205 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jg2wdWex4j3EYH8lK:-L-jg2wdWex4j3EYH8lL:b-7hw89q) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L205)):*
> ```XML
>                     playlistType: KalturaPlaylistType.staticList,
>                     playlistContent: Array.isArray(newData.entries) ? newData.entries.map(({id}) => id).join(',') : ''
>                   }, newData.entries)
> ```

see "comment 1"

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts, line 62 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jgBWPollclUATxIJO:-L-jgBWPollclUATxIJP:b-hgc3pu) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts#L62)):*
> ```XML
>   protected onActivate(): Observable<{ failed: boolean, error?: Error }> {
>     if (!this.data.id) {
>       this.entries = this.data.entries;
> ```

comment 1:
I saw that you already assign the id on 'playlistContent' property which I think serve the purpose. 

I don't think that you need to extend `KalturaPlaylist` locally with `entries` instead do the following logic:
1. if playlist has id (meaning it is existing playlist) -> run the existing logic
2. if playlist id is empty -> run here a new logic that extract those entries from the server. 

Note that:
- this way you don't create duplication of the data (both in playlistContent and entries properties) and also your code is almost similiar on both situations. 
- you can pass only entries ids' from the entries bulk action instead of sending instances that are managed by entries and using them in playlist
- if you want to close it tight you can also pre-check the selected entries in the bulk operation and confirm their status,  and if there are some entries with wrong status (like no media) show a warning message and if the user choose to continue then filter them out. It would be super cool but it is not mandatory because the legacy currently allow this situation and also handles it in the server as we saw. so it is up to you if you want to implement this or not.

Please make sure the PRD is aligned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/297)*

**Comment by diamond-darrell** [comment]
Review status: 5 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jfVq_TTykzGJOgYdx:-L-kJEuCoPLg8VAPkAQS:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L37)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see "comment 1"
</blockquote></details>

OK

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 192 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-X7c_utk4Ti0D6C3q5:-L-kJCyzMXK05vitNXgq:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L192)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I saw that you moved some function from  `PlaylistsStore`. if you don't need them there  anymore then remove them



</blockquote></details>

OK

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 205 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jg2wdWex4j3EYH8lK:-L-kJECktWcu0tuoeREe:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L205)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see "comment 1"
</blockquote></details>

OK

---

*[src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts, line 62 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-L-jgBWPollclUATxIJO:-L-kKLn48Zr032vFUpP5:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/cfe3564919816bd6c5621446e92dfebcdda787fb/src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts#L62)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

comment 1:
I saw that you already assign the id on 'playlistContent' property which I think serve the purpose. 

I don't think that you need to extend `KalturaPlaylist` locally with `entries` instead do the following logic:
1. if playlist has id (meaning it is existing playlist) -> run the existing logic
2. if playlist id is empty -> run here a new logic that extract those entries from the server. 

Note that:
- this way you don't create duplication of the data (both in playlistContent and entries properties) and also your code is almost similiar on both situations. 
- you can pass only entries ids' from the entries bulk action instead of sending instances that are managed by entries and using them in playlist
- if you want to close it tight you can also pre-check the selected entries in the bulk operation and confirm their status,  and if there are some entries with wrong status (like no media) show a warning message and if the user choose to continue then filter them out. It would be super cool but it is not mandatory because the legacy currently allow this situation and also handles it in the server as we saw. so it is up to you if you want to implement this or not.

Please make sure the PRD is aligned
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/297)*

**Comment by esakal** [comment]
Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/297)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-:-L-ztjsalvuRTKF_xcer:bnfp4nl)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 5 of 11 files at r1, 7 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/297#-:-L0-8Yx-9NbGruXNC748:bnfp4nl)*

**Pull request merged**
