### PR TITLE
KMCNG-759

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-759

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/416)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/416#-L6zfXB3vkFv5Xw9AnMe:-L6zfXB3vkFv5Xw9AnMf:b-6rwwoz) (no related file):*
it appears that we are showing wrong post creation messages to all our types. Please sync them according to the legacy. 

---

*[src/shared/content-shared/entries/entries-table/entries-table.component.ts, line 172 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/416#-L6zfIXqGMW34a65nw5c:-L6zfIXqGMW34a65nw5d:bl9t730) ([raw file](https://github.com/kaltura/kmc-ng/blob/1813b441483e0e47735fc4d550262fae36dcfda2/src/shared/content-shared/entries/entries-table/entries-table.component.ts#L172)):*
> ```XML
> 
>   public _onActionSelected(action: string, entry: KalturaMediaEntry): void {
>     const actionAllowed = this._allowDrilldown(entry.mediaType, entry.status);
> ```

this will prevent 'delete', consider providing the action to `_allowDrilldown`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/416)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/416#-L6zfXB3vkFv5Xw9AnMe:-L6zyslq_cvbpBCIrwnG:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

it appears that we are showing wrong post creation messages to all our types. Please sync them according to the legacy. 
</blockquote></details>

OK

---

*[src/shared/content-shared/entries/entries-table/entries-table.component.ts, line 172 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/416#-L6zfIXqGMW34a65nw5c:-L6zo3GAf6iMH-QsO-uB:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/1813b441483e0e47735fc4d550262fae36dcfda2/src/shared/content-shared/entries/entries-table/entries-table.component.ts#L172)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this will prevent 'delete', consider providing the action to `_allowDrilldown`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/416)*

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/416)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/416#-:-L7-0uDZP-Hv6p3Q5g7U:bnfp4nl)*

**Pull request merged**
