### PR TITLE
Content > Categories > Bulk Operations

### PR DESCRIPTION
**Pull request by benstov**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/242)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 196 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAdpcqjMgmJuAHbElx:-KyAdpcqjMgmJuAHbEly:b-43iun3) ([raw file](https://github.com/kaltura/kmc-ng/blob/9488239a5961d31b4e2b41efa191d865d5f5e46f/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L196)):*
> ```XML
>   private hasEditWarnings(): boolean {
>     let isEditWarning: boolean = false;
>     this.selectedCategories.every(obj => {
> ```

when using [high level functions](https://en.wikipedia.org/wiki/Higher-order_function) you basically want to provide a function and get a result. 

You should use the result of the function instead of changing `isEditWarning` internally. 

read more about [every](https://en.wikipedia.org/wiki/Higher-order_function)

---

*[src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts, line 27 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAfROCKys9RfjzzR7L:-KyAfROCKys9RfjzzR7M:b-n6j02r) ([raw file](https://github.com/kaltura/kmc-ng/blob/281061af7ccb73c9b4fab8cfff893b2333b1b6ca/src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts#L27)):*
> ```XML
>   @Output() ownerChanged = new EventEmitter<KalturaUser>();
> 
>   public _loading = false;
> ```

I just want to verify. I see that you removed a lot of code from this file but I don't see that you added it to an other file (either another component or the relevant service). Was this on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAuyxE3cYzcicN58L3:-KyAuyxE3cYzcicN58L4:b-tzwu1h) (no related file):*
+@amirch1 please review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by amirch1** [comment]
Reviewed 5 of 8 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 162 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFe7cXX1mvpKTb9gla:-KyFe7cXX1mvpKTb9glb:b-ek3js4) ([raw file](https://github.com/kaltura/kmc-ng/blob/72af810ce85d023d7fe317dd7b8578f92e3882de/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L162)):*
> bulk-operations
Where did this logic is coming from? Category IDs should not be listed in the confirmation message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFevtGPSezCu8sFI21:-KyFevtGPSezCu8sFI22:b-thdrsh) (no related file):*


prompt text is cut. We had the same issue in the entry "change owner" section. Please take the CSS solution from there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by benstov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAuyxE3cYzcicN58L3:-KyLKukAjLqFyMA0_OOr:bb7f2mf) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 please review
</blockquote></details>

done

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFevtGPSezCu8sFI21:-KyLMpq2mw-30WHvOQZq:b-7rl0kd) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>



prompt text is cut. We had the same issue in the entry "change owner" section. Please take the CSS solution from there.

</blockquote></details>

done

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 196 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAdpcqjMgmJuAHbElx:-KyKyBrkjgB0ZwU5ScsZ:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/9488239a5961d31b4e2b41efa191d865d5f5e46f/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L196)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

when using [high level functions](https://en.wikipedia.org/wiki/Higher-order_function) you basically want to provide a function and get a result. 

You should use the result of the function instead of changing `isEditWarning` internally. 

read more about [every](https://en.wikipedia.org/wiki/Higher-order_function)
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 162 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFe7cXX1mvpKTb9gla:-KyKvmCLA-beM2N7eOLu:b47hau7) ([raw file](https://github.com/kaltura/kmc-ng/blob/72af810ce85d023d7fe317dd7b8578f92e3882de/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L162)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

> bulk-operations
Where did this logic is coming from? Category IDs should not be listed in the confirmation message
</blockquote></details>

Fixed.
I saw this also in the playlist that's why.

---

*[src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts, line 27 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAfROCKys9RfjzzR7L:-KyLHufGJr6PrR84PvI8:b-5tedtx) ([raw file](https://github.com/kaltura/kmc-ng/blob/281061af7ccb73c9b4fab8cfff893b2333b1b6ca/src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts#L27)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I just want to verify. I see that you removed a lot of code from this file but I don't see that you added it to an other file (either another component or the relevant service). Was this on purpose?
</blockquote></details>

The code that was exist here earlier is a copy of  bulk-change-owner.component.ts, the component doesn't have the logic for confirmation upon closing or search users

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by benstov** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAuyxE3cYzcicN58L3:-KyLNcxV8d11S1-seHwp:b-896fix) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFevtGPSezCu8sFI21:-KyLNdu980o1kR5wrSSk:b-896fix) (no related file):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 196 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAdpcqjMgmJuAHbElx:-KyLNewDUsI2eC5R3CXW:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/9488239a5961d31b4e2b41efa191d865d5f5e46f/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L196)):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts, line 162 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyFe7cXX1mvpKTb9gla:-KyLNaxf7MEfbfPFTHyQ:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/72af810ce85d023d7fe317dd7b8578f92e3882de/src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts#L162)):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

Fixed.
I saw this also in the playlist that's why.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts, line 27 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-KyAfROCKys9RfjzzR7L:-KyLNg3PH71F1tUqmYMB:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/281061af7ccb73c9b4fab8cfff893b2333b1b6ca/src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-contribution-policy/bulk-change-contribution-policy.component.ts#L27)):*
<details><summary><i>Previously, benstov wrote…</i></summary><blockquote>

The code that was exist here earlier is a copy of  bulk-change-owner.component.ts, the component doesn't have the logic for confirmation upon closing or search users
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242#-:-KyQDHV3skOu3h4an19E:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/242)*

**Pull request merged**
