### PR TITLE
KMCNG-713 Entries - While saving - menu panel should be disabled

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/228)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/228#-KweF3IMaKMQAC9JJ5Mn:-KweF3IMaKMQAC9JJ5Mo:b-cgi96p) (no related file):*
+@amirch1 I'm not sure if manipulating the global app loader is the right approach... Let's discuss together tomorrow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/228)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/228#-KweF3IMaKMQAC9JJ5Mn:-Kwj8i983HfQcfcnCUIP:b-wbp0mv) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 I'm not sure if manipulating the global app loader is the right approach... Let's discuss together tomorrow
</blockquote></details>

waiting for Oct 19 meeting dealing with the design of this request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/228)*

**Comment by benstov** [comment]
Decided to go for OperationTag implementation that will allow us to tags operations (observable.tag('x').subscribe) that will mark the operation under 'x' tag.
This way we can mark operations that will block the main panel ".tag('block-shell')"

**Comment by benstov** [comment]
Decided to go for OperationTag implementation that will allow us to tags operations (observable.tag('x').subscribe) that will mark the operation under 'x' tag.
This way we can mark operations that will block the main panel ".tag('block-shell')"

**Pull request closed without merging**
