### PR TITLE
fix(administration/users): display error message returned from server for invalid user names

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1420

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/405)

### CODE REVIEW

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-:-L6zSWjTjBg_eZPIWi7l:bnfp4nl)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-:-L6zU2XcydGFwsfXF7E1:bnfp4nl)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/applications/administration-users-app/users/users.service.ts, line 227 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zV-aua3cYphz8Fko2:-L6zV-aua3cYphz8Fko3:baueaoe) ([raw file](https://github.com/kaltura/kmc-ng/blob/dbdd73ee887f517dcef0a53d49892d1a9cd9522d/src/applications/administration-users-app/users/users.service.ts#L227)):*
> ```XML
>       .map((responses) => {
>         if (responses.hasErrors()) {
>           const errorMessage = responses.map(response => {
> ```

shouldn't you use a `reduce` to aggregate the messages instead of map? the error message should be of type string and I think here you return array of strings....

---

*[src/applications/administration-users-app/users/users.service.ts, line 272 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zV9s4gXoXnkT3wRw7:-L6zV9s4gXoXnkT3wRw8:baueaoe) ([raw file](https://github.com/kaltura/kmc-ng/blob/dbdd73ee887f517dcef0a53d49892d1a9cd9522d/src/applications/administration-users-app/users/users.service.ts#L272)):*
> ```XML
>       .map((responses) => {
>         if (responses.hasErrors()) {
>           const errorMessage = responses.map(response => {
> ```

shouldn't you use a `reduce` to aggregate the messages instead of map? the error message should be of type string and I think here you return array of strings....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/administration-users-app/users/users.service.ts, line 227 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/405#-L6zV-aua3cYphz8Fko2:-L6zVM2Z6diBGVOK2qrq:bn4l6yw) ([raw file](https://github.com/kaltura/kmc-ng/blob/dbdd73ee887f517dcef0a53d49892d1a9cd9522d/src/applications/administration-users-app/users/users.service.ts#L227)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

shouldn't you use a `reduce` to aggregate the messages instead of map? the error message should be of type string and I think here you return array of strings....
</blockquote></details>

here's a `.join('')` in the end

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/405)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zXI42hotE3dFzKg-B:-L6zXI42hotE3dFzKg-C:b-4n28ud) (no related file):*
the error returned from the server is: "value in field [email] is not valid
User was not found". It should say "User was not created". Can we simply fix the client side email validator to prevent entering x@x?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zXI42hotE3dFzKg-B:-L6zXkHDeuVY_TB2JezL:b-jkhns8) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

the error returned from the server is: "value in field [email] is not valid
User was not found". It should say "User was not created". Can we simply fix the client side email validator to prevent entering x@x?
</blockquote></details>

we can, but then it will be inconsistent with other email fields where we are using the default angular's email validator

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zXI42hotE3dFzKg-B:-L6zY2ztgx-nDJaDyr7M:b-xiy71x) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

we can, but then it will be inconsistent with other email fields where we are using the default angular's email validator
</blockquote></details>

I agree with Stas, validating emails is complex and if the server does it we can stick with the default angular email validator. Regarding the message content, I think this is the message provided by the server, Stas am I right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zXI42hotE3dFzKg-B:-L6zYu_WiDJBDNeoI03w:b-hw8ww1) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I agree with Stas, validating emails is complex and if the server does it we can stick with the default angular email validator. Regarding the message content, I think this is the message provided by the server, Stas am I right?
</blockquote></details>

Yes, the message is provided by the server yet we can check error code if we have to show a custom message for needed case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/405#-L6zXI42hotE3dFzKg-B:-L6zdb1dhQ_1Y1BzV8vF:bkk3a74) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Yes, the message is provided by the server yet we can check error code if we have to show a custom message for needed case
</blockquote></details>

lets keep it as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/405)*

**Pull request merged**
