### PR TITLE
KMCNG-454 move growl to browser service

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/180)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/app.component.ts, line 21 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwjeb7OC2ED_8bldQd:-Kqwjeb7OC2ED_8bldQe:bmmomq6) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L21)):*
> ```XML
>   public _isBusy: boolean = false;
>   public _blockerMessage: AreaBlockerMessage = null;
>   public growlMessages: GrowlMessage[] = [];
> ```

rename to _growlMessages

---

*[src/app/app.component.ts, line 53 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwjpYaTMrd969mGnBO:-KqwjpYaTMrd969mGnBP:btuc36s) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L53)):*
> ```XML
>     this._browserService.growlMessages$.subscribe(
>       (message: GrowlMessage) => {
>         this.growlMessages = message && message.detail ? [message] : [];
> ```

- assume the message is correct 
- use the ECMA6 approach

ECMA6
```
this._growlMessages = [ ...this._growlMessages, message ];


ECMA5
```
var newArray = oldArray.slice();
newArray.push(message);
```
```


---

*[src/app/app.module.ts, line 76 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwogc0wDr957WFhE3a:-Kqwogc0wDr957WFhE3b:b-gzuumy) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.module.ts#L76)):*
> ```XML
>     KalturaServerModule,
>     AreaBlockerModule,
>     GrowlModule
> ```

Remove all places the import 'GrowlModule' (expect for the app.module)

---

*[src/applications/content-entries-app/entries/entries-list.component.ts, line 160 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwon5SgFRPFR0I_hS2:-Kqwon5SgFRPFR0I_hS3:b-mu0t41) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entries/entries-list.component.ts#L160)):*
> ```XML
>         () => {
>           this.isBusy = false;
>           this._browserService.showGrowlMessage(null);
> ```

remove this line

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 54 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwpAq4xXY9d7J79_ht:-KqwpAq4xXY9d7J79_hu:b-eqqnb5) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L54)):*
> ```XML
>     protected _onReset()
>     {
>       this._browserService.showGrowlMessage(null);
> ```

you don't need this line or any replacement

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 244 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwpM_sbCHpB6qTFg3M:-KqwpM_sbCHpB6qTFg3N:b-i2munj) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L244)):*
> ```XML
> 							    super._hideLoader();
>                   this._browserService.showGrowlMessage(null);
>                   this._browserService.showGrowlMessage({severity: 'success', summary: '', detail: this._appLocalization.get('applications.content.entryDetails.flavours.deleteSuccess')});
> ```

remove all the empty `summary` properties

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwkZgM-TRpNSZKKBI_:-KqwkZgM-TRpNSZKKBIa:b8079h9) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L20)):*
> ```XML
> 
> export interface GrowlMessage {
>   severity?: string;
> ```

severity should be mandatory (remove the ?)

```
severity : 'success' | 'info' | 'error' | 'warn';
```

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 23 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwlXUIMsT9wNGd6FhF:-KqwlXUIMsT9wNGd6FhG:b846o3a) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L23)):*
> ```XML
>   summary?: string;
>   detail?: string;
>   id?: any;
> ```

remove the id unless needed and the comment a reply

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwp_oe5bMtFO1R9gXA:-Kqwp_oe5bMtFO1R9gXB:bdx7ult) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L37)):*
> ```XML
> 
>   private _appStatus = new BehaviorSubject<{isBusy : boolean, errorMessage : string}>({ isBusy : false, errorMessage : null});
>   private _growlMessages = new BehaviorSubject<GrowlMessage>({severity: null, summary: null, detail: null, id: null});
> ```

- change all properties to singular
```
private _growlMessage = new Subject<GrowlMessage>();
```

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 39 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwq-Hh3g8k30mkNBjF:-Kqwq-Hh3g8k30mkNBjG:byom1a9) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L39)):*
> ```XML
>   private _growlMessages = new BehaviorSubject<GrowlMessage>({severity: null, summary: null, detail: null, id: null});
>   public appStatus$ = this._appStatus.asObservable();
>   public growlMessages$ = this._growlMessages.asObservable();
> ```

rename to singular 

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 204 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwp0BGcFtQxj9Fo0sD:-KqwjslXaAQUGJPhhlfr:b-u53ce6) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L204)):*
> ```XML
> 
> 	public showGrowlMessage(message: GrowlMessage): void {
>     this._growlMessages.next(message);
> ```

should ignore messages that doesn't have either `detail` or `summary`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*

**Comment by konstantin-stepanets** [comment]
Review status: 4 of 14 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/app/app.component.ts, line 21 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwjeb7OC2ED_8bldQd:-KqxNAvU8MyWUExxTwvk:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L21)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

rename to _growlMessages
</blockquote></details>

OK

---

*[src/app/app.component.ts, line 53 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwjpYaTMrd969mGnBO:-KqxOI4xUqWeffyzmnd4:b-8hpk9t) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L53)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- assume the message is correct 
- use the ECMA6 approach

ECMA6
```
this._growlMessages = [ ...this._growlMessages, message ];


ECMA5
```
var newArray = oldArray.slice();
newArray.push(message);
```
</blockquote></details>

https://www.screencast.com/t/YuQ0xwyko0
So this behavior is correct, right?

---

*[src/app/app.module.ts, line 76 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwogc0wDr957WFhE3a:-KqxOOUW1SgvP5EWltWY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.module.ts#L76)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Remove all places the import 'GrowlModule' (expect for the app.module)
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entries/entries-list.component.ts, line 160 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwon5SgFRPFR0I_hS2:-KqxNLH_UrXiTTdi5Mho:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entries/entries-list.component.ts#L160)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 54 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwpAq4xXY9d7J79_ht:-KqxNOgHIGUkDkiG_Mqn:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L54)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you don't need this line or any replacement
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 244 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwpM_sbCHpB6qTFg3M:-KqxNR1Gw7ysVQGGlhiW:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L244)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

remove all the empty `summary` properties
</blockquote></details>

OK

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwkZgM-TRpNSZKKBI_:-KqxNSrCupC0KdhUSbHF:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L20)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

severity should be mandatory (remove the ?)

```
severity : 'success' | 'info' | 'error' | 'warn';
```
</blockquote></details>

OK

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 23 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwlXUIMsT9wNGd6FhF:-KqxNUanXHTBbYOZrenK:b-yfs270) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L23)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

remove the id unless needed and the comment a reply
</blockquote></details>

Removed. Can't find where it was copied from.

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 37 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwp_oe5bMtFO1R9gXA:-KqxO4LpCx5SCHVEDYJY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L37)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- change all properties to singular
```
private _growlMessage = new Subject<GrowlMessage>();
```
</blockquote></details>

OK

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 39 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwq-Hh3g8k30mkNBjF:-KqxO5_-xV8tW08FeJJq:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L39)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

rename to singular 
</blockquote></details>

OK

---

*[src/shared/kmc-shell/providers/browser.service.ts, line 204 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-Kqwp0BGcFtQxj9Fo0sD:-KqxO6uYzUVNQutXGBG4:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/shared/kmc-shell/providers/browser.service.ts#L204)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

should ignore messages that doesn't have either `detail` or `summary`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*
<!-- Sent from Reviewable.io -->

**Comment by esakal** [comment]
Review status: 4 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/app.component.ts, line 53 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwjpYaTMrd969mGnBO:-KqyOvCzh-UGj5U5sFbY:b-k8f7zz) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L53)):*
<details><summary><i>Previously, konstantin-stepanets (Konstantin Stepanets) wrote…</i></summary><blockquote>

https://www.screencast.com/t/YuQ0xwyko0
So this behavior is correct, right?
</blockquote></details>

nope but you are close....

You didn't bind to the growl updates when it dismiss a message. This is why messages keep showing to you. 

To demonstrate my point I'm showing a growl message every time the user click 'enter' in the search field. see the following gif animation



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*

**Comment by esakal** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*

**Comment by konstantin-stepanets** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/app.component.ts, line 53 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-KqwjpYaTMrd969mGnBO:-Kr16amVSd9uri7anf24:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a5a1aceb2d1e963d8f6bb1fa3f0aca0dba758fcf/src/app/app.component.ts#L53)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

nope but you are close....

You didn't bind to the growl updates when it dismiss a message. This is why messages keep showing to you. 

To demonstrate my point I'm showing a growl message every time the user click 'enter' in the search field. see the following gif animation




</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*

**Comment by esakal** [comment]
:lgtm:

I cannot approve the PR since you have conflicts with master (which is reasonable but need to be fixed so I will be abe to merge.). Don't forget to check after you merge and then push it so I will be able to approve your PR.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-:-Kr19u8az4xxi6ZFBmYX:b-dt0iiu)*

**Comment by konstantin-stepanets** [comment]
Conflict should be resolved now

---

Review status: 11 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180#-:-Kr1D0L-YcpePf06wLws:b-pkw0jd)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/180)*

**Pull request merged**
