### PR TITLE
Replace video > match from drop folder

### PR DESCRIPTION
**Pull request by diamond-darrell**
#### IS BLOCKED BY https://github.com/kaltura/kaltura-ng/pull/116

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/382369956/Replace+Video+Widget+Match+from+Drop+Folder
and
https://kaltura.atlassian.net/browse/KMCNG-1864

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
Review status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @amirch1 and @esakal)

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts, line 471 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LF1su7x4ax5mRv7QPpO:-LF1su7x4ax5mRv7QPpP:bsj4675) ([raw file](https://github.com/kaltura/kmc-ng/blob/85dfa42708ad57473ee2cae76322cd47b973555f/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts#L471)):*
> ```XML
> 
>             request$ = this._kalturaClient
>                 .multiRequest(new KalturaMultiRequest(flavorAssetAddAction, flavorAssetSetContentAction))
> ```

+@esakal could you please check what possibly could be wrong with this multirequest - it returns no response for me and the kaltura client throws "server response is invalid, expected array of 2" error because of that, thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
@diamond-darrell - please look at: https://projects.invisionapp.com/d/main#/console/12328412/290541218/preview

**Comment by diamond-darrell** [comment]
+@amirch1 I've added a title, what about a small window width is this okay?

---

Review status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @amirch1 and @esakal)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705#-:-LFGe2c_5tMFULhE2nbq:b-45tc9t)*

**Comment by esakal** [comment]
Review status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @esakal and @amirch1)

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts, line 471 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LF1su7x4ax5mRv7QPpO:-LFqyDp2BIOz80Bf0dGF:bplsdlk) ([raw file](https://github.com/kaltura/kmc-ng/blob/85dfa42708ad57473ee2cae76322cd47b973555f/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts#L471)):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

+@esakal could you please check what possibly could be wrong with this multirequest - it returns no response for me and the kaltura client throws "server response is invalid, expected array of 2" error because of that, thanks
</blockquote></details>

I discussed about it with Yossi. he said that we should split the request into two separated ones as the server has troubles with this multi request

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 14 files reviewed, all discussions resolved (waiting on @amirch1 and @esakal)

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts, line 471 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LF1su7x4ax5mRv7QPpO:-LFqyg61DmVk5_6dhOHq:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/85dfa42708ad57473ee2cae76322cd47b973555f/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts#L471)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I discussed about it with Yossi. he said that we should split the request into two separated ones as the server has troubles with this multi request
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by esakal** [comment]
:lgtm: 
code confirmed, 

+@amirch1  please check at runtime and merge if possible.

---

Reviewed 4 of 13 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amirch1)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705#-:-LFv3Nqi1Ld4Om-Cmu5G:bstofgx)*

**Comment by amirch1** [comment]
@diamond-darrell - is there a corresponding PR on kaltura-ng that should be compiled with this PR?

**Comment by amirch1** [comment]
Reviewed 4 of 13 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell)

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html, line 8 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzfyIkDJhveFdANvFd:-LFzfyIkDJhveFdANvFe:b-j73l7u) ([raw file](https://github.com/kaltura/kmc-ng/blob/138be5ba43d33b0378ac7d66d1a442ffac598831/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html#L8)):*
> ```HTML
>         (click)="_openReplacementMenu('upload')"></button>
> 
> <button *ngIf="_uploadEnabled"
> ```

this is a duplicate - we now have 2 "Upload from desktop" buttons

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzi-Q-CJA6QSA0p4ls:-LFzi-Q-CJA6QSA0p4lt:b-jn2ml3) (no related file):*
Since in smaller resolution the buttons spread to 2 lines, lets add a media query and for screen width lower than 1310px apply these changes:


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzlUquBL5HG19Nqaic:-LFzlUquBL5HG19Nqaid:bufuxf1) (no related file):*
Radio buttons seems to behave like checkboxes - they can be unselected as well by clicking again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzmuKbBUuki_1b493T:-LFzmuKbBUuki_1b493U:bgpm8mg) (no related file):*
disabled radio buttons are hard to detect:


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzlUquBL5HG19Nqaic:-LFzmnk93YeQF5kN5yDn:byp5sjb) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Radio buttons seems to behave like checkboxes - they can be unselected as well by clicking again.
</blockquote></details>

fixed, sorry, appeared after a merge

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzlUquBL5HG19Nqaic:-LFzn7HKDZkSJ9RH-74J:b8glyik) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

fixed, sorry, appeared after a merge
</blockquote></details>

disregard comment, wrong reply

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html, line 8 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzfyIkDJhveFdANvFd:-LFzn5gu9JT-XKmrdwip:byp5sjb) ([raw file](https://github.com/kaltura/kmc-ng/blob/138be5ba43d33b0378ac7d66d1a442ffac598831/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html#L8)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

this is a duplicate - we now have 2 "Upload from desktop" buttons
</blockquote></details>

fixed, sorry, appeared after a merge

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzlUquBL5HG19Nqaic:-LFznPx_CzBfAXuAmAdy:btgzwho) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

disregard comment, wrong reply
</blockquote></details>

yes, this is the default behavior of the primeng table's single select mode, not sure we can configure it

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFznvg77EUYmSaa-GkT:-LFznvg77EUYmSaa-GkU:bueqq04) (no related file):*
When trying to add a file from drop folder to a specific flavor - getting this error. Doesn't happen in legacy:


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzlUquBL5HG19Nqaic:-LFzoZGRE31bafOu5zm2:b-72tuha) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

yes, this is the default behavior of the primeng table's single select mode, not sure we can configure it
</blockquote></details>

ok then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFznvg77EUYmSaa-GkT:-LFzrGoz80zHZrgpRWOA:b-s74788) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

When trying to add a file from drop folder to a specific flavor - getting this error. Doesn't happen in legacy:


</blockquote></details>

OK
Now the server returns "Flavor not found" error but the legacy is doing the same, could you please check it? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by amirch1** [comment]
Review status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFznvg77EUYmSaa-GkT:-LFzsPZsCsrBl4qXuyHH:bab0xoh) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

OK
Now the server returns "Flavor not found" error but the legacy is doing the same, could you please check it? 
</blockquote></details>

it could be an error on the server side (there are some glitches today) but if we are getting the same results as the legacy - lets leave it for QA

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzi-Q-CJA6QSA0p4ls:-LFztWoGEynkVn5P4IZg:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Since in smaller resolution the buttons spread to 2 lines, lets add a media query and for screen width lower than 1310px apply these changes:


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzmuKbBUuki_1b493T:-LFzvTPB506lmR33g59S:bemgh1s) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

disabled radio buttons are hard to detect:


</blockquote></details>

`$kGrayscale4` makes it even more visible then a normal one


let's make it at least `$kGrayscale6


Or we can leave the original color, but instead of `opacity: .3` make it `opacity: .5`


wdyt?

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFznvg77EUYmSaa-GkT:-LFztYbm0nC4tbG1WmcH:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

it could be an error on the server side (there are some glitches today) but if we are getting the same results as the legacy - lets leave it for QA
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @amirch1, @esakal, and @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzmuKbBUuki_1b493T:-LG-0fkS0_Jl1-Fo9aaH:b-3zlixq) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

`$kGrayscale4` makes it even more visible then a normal one


let's make it at least `$kGrayscale6


Or we can leave the original color, but instead of `opacity: .3` make it `opacity: .5`


wdyt?
</blockquote></details>

I'll push the opacity option (it looks the same as color, but requires the one line less code)

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @amirch1 and @esakal)

---

*[src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html, line 8 at r3](https://reviewable.io/reviews/kaltura/kmc-ng/705#-LFzfyIkDJhveFdANvFd:-LG-1z0oBTPSWBDGLn0W:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/138be5ba43d33b0378ac7d66d1a442ffac598831/src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html#L8)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

fixed, sorry, appeared after a merge
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/705)*

**Pull request merged**
