### PR TITLE
KMCNG-1380

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1380

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/582)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582#-L9osF601BHXR2BqDW9l:-L9osF601BHXR2BqDW9m:b-o6b8ii) (no related file):*
cannot move into `no parent`



---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582)*

**Comment by diamond-darrell** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582#-L9osF601BHXR2BqDW9l:-L9p2oxTEdt0ypljAhiu:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

cannot move into `no parent`



</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/582#-:-L9pB3Gf5PxfzFcDshGl:bnfp4nl)*

**Pull request merged**
