### PR TITLE
Distribution

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/397)

### CODE REVIEW

**Comment by amirch1** [comment]
Reviewed 31 of 65 files at r1, 34 of 35 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6BnBxS3DifVXj8YdY7:-L6BnBxS3DifVXj8YdY8:bf2r5a9) (no related file):*


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6BwB9p4zHMEaMeRCwo:-L6BwB9p4zHMEaMeRCwp:bya9rl2) (no related file):*


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6C8CrhcWvFFTH4FzvR:-L6C8CrhcWvFFTH4FzvS:bamrn0x) (no related file):*

If you delete a profile from within the edit floater using the "Delete" button, when you open the edit floater again - you still see the delete confirmation box

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Review status: 46 of 53 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6H70Dzt4ctLlbdlmsO:-L6H70Dzt4ctLlbdlmsP:b-wze8l) (no related file):*


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Review status: 46 of 53 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6H7WH4aJy7ESAYOKE6:-L6H7WH4aJy7ESAYOKE7:bmbyxtl) (no related file):*

Selecting a date in the calendar keeps it open and doesn't auto-close

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by amirch1** [comment]
Reviewed 12 of 35 files at r2, 58 of 111 files at r4, 53 of 53 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6H70Dzt4ctLlbdlmsO:-L6HIzSxW2S9dgjPTVvd:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6H7WH4aJy7ESAYOKE6:-L6HJ-B7LL_aHGAWY63k:b-36j83i) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>


Selecting a date in the calendar keeps it open and doesn't auto-close
</blockquote></details>

by design

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by esakal** [comment]
+@diamond-darrell superb job! :)

---

Reviewed 12 of 35 files at r2, 53 of 53 files at r5.
Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LlsE09w4y43vkpM9E:-L6LlsE09w4y43vkpM9F:btmf07r) (no related file):*
please move the svg files from /src/assets/distribution_connectors into `/src/content-entries-app/styles/assets/connectors`

---

*[src/applications/sub-applications-config.ts, line 16 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6HVUW6Ee6iylslBgev:-L6HVUW6Ee6iylslBgew:b-5u26cp) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/sub-applications-config.ts#L16)):*
> ```XML
>         embedType: 'dynamic' | 'iframe' | 'auto' | 'thumb'
>     },
>     entryDetails: {
> ```

please use here the name of your (sub) application 'contentEntriesApp'x

---

*[src/applications/sub-applications-config.ts, line 38 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6HV9ej8EQ8o4bqsGfd:-L6HV9ek6pX7eCG4viwp:b6oopj5) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/sub-applications-config.ts#L38)):*
> ```XML
>         'embedType': 'dynamic'
>     },
>     'entryDetails': {
> ```

please use here the name of your (sub) application 'contentEntriesApp'

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 84 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LVuO5uRYsSqtmePgm:-L6LVuO5uRYsSqtmePgn:be1vqeu) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L84)):*
> ```XML
>    */
>   protected onReset() {
>     this._flavors.next({ items: [] });
> ```

you should clear all behavior subjects to prevent data passing between entries:
1. access any entry
2. open 'distribution' section
3. navigate to the next entry using the arrow on the top
4. in dev tool > network > go to offline
5. open 'distribution' section

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 252 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lb75zaR7DnxE64tcb:-L6Lb75zaR7DnxE64tcc:bdasawa) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L252)):*
> ```XML
>       .cancelOnDestroy(this, this.widgetReset$)
>       .map(([partnerDistribution, entryDistribution, entryFlavors, entryThumbnails]) => {
>         if (partnerDistribution.error) {
> ```

your code seems solid! you did well (+1 for that). Still I think it would be safer to wrap the map content with general try...catch as it is doing massive manipulation on the multiple responses. and it is better not getting runtime errors.

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 319 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LfDjMTSJ5KM0BVDPu:-L6LfDjMTSJ5KM0BVDPv:bo0srya) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L319)):*
> ```XML
>             buttons: [
>               {
>                 label: this._appLocalization.get('app.common.retry'),
> ```

you should provide only 'ok' button and refresh the section once clicked to reflect the updates server status

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 323 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lgkjx_BDf0liLqAbk:-L6Lgkjx_BDf0liLqAbl:b-v60cji) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L323)):*
> ```XML
>               },
>               {
>                 label: this._appLocalization.get('app.common.cancel'),
> ```

you should remove this option

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 435 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lgu6lur16DVjudG2R:-L6Lgu6mDqQpvD1gQECz:bvm7u6y) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L435)):*
> ```XML
> 
>       default:
>         return '';
> ```

return a constant value 'unknown provider'

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 466 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lhdua_SQr18u-MMq6:-L6Lhdua_SQr18u-MMq7:bt6qq9o) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L466)):*
> ```XML
> 
>     const partnerProfile = this.getPartnerProfileById(profile.distributionProfileId);
>     const connectorName = partnerProfile ? this.getProviderName(partnerProfile.providerType) : '';
> ```

use static value 'unknown provider'

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 566 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LiS_4jOp0a7cVjQ_x:-L6LiS_4jOp0a7cVjQ_y:bo0srya) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L566)):*
> ```XML
>             message: error.message || this._appLocalization.get('applications.content.entryDetails.distribution.errors.updateFailed'),
>             buttons: [
>               {
> ```

you should provide only 'ok' button and refresh the section once clicked to reflect the updates server status

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 571 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LiT40JU0PkjqgqfYY:-L6LiT40JU0PkjqgqfYZ:b7nb8z0) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L571)):*
> ```XML
>               },
>               {
>                 label: this._appLocalization.get('app.common.cancel'),
> ```

please remove this option

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 588 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lj1x3J_u28ZmwIXb-:-L6Lj1x3J_u28ZmwIXb0:blpgnzi) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L588)):*
> ```XML
>         },
>         error => {
>           this._browserService.alert({
> ```

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 603 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lj5B9QUHgT2KIEC4i:-L6Lj5B9QUHgT2KIEC4j:blpgnzi) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L603)):*
> ```XML
>         },
>         error => {
>           this._browserService.alert({
> ```

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 618 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LjGTcaYfs52fuvyTy:-L6LjGTcaYfs52fuvyTz:blpgnzi) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L618)):*
> ```XML
>         },
>         error => {
>           this._browserService.alert({
> ```

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action

---

*[src/applications/content-entries-app/entry/entry-distribution/distributed-profile/distributed-profile.component.html, line 31 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LkfSh8ND7I4byQdtj:-L6LkfSh8ND7I4byQdtk:b-39rkuu) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/distributed-profile/distributed-profile.component.html#L31)):*
> ```HTML
>       </span>
>       <span class="kLastUpdate">
>         {{'applications.content.entryDetails.distribution.lastUpdate' | translate:[(_profile?.updatedAt | kDate:'MM/DD/YYYY')]}}
> ```

use 'longDateonly' preset for the kDate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-:-L6Llxe_daTrCotKq29d:bc4bx9)*

**Comment by diamond-darrell** [comment]
thanks :slightly_smiling_face: 

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LlsE09w4y43vkpM9E:-L6LnYGYFkjWLxzM3k1f:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please move the svg files from /src/assets/distribution_connectors into `/src/content-entries-app/styles/assets/connectors`
</blockquote></details>

OK

---

*[src/applications/sub-applications-config.ts, line 16 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6HVUW6Ee6iylslBgev:-L6LppD-AUeMy6JNVx40:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/sub-applications-config.ts#L16)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please use here the name of your (sub) application 'contentEntriesApp'x
</blockquote></details>

OK

---

*[src/applications/sub-applications-config.ts, line 38 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6HV9ej8EQ8o4bqsGfd:-L6Lpq2NpAJ5aIOQVSwg:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/sub-applications-config.ts#L38)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please use here the name of your (sub) application 'contentEntriesApp'
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 84 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LVuO5uRYsSqtmePgm:-L6M--uT-k4zo-GZJHMo:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L84)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should clear all behavior subjects to prevent data passing between entries:
1. access any entry
2. open 'distribution' section
3. navigate to the next entry using the arrow on the top
4. in dev tool > network > go to offline
5. open 'distribution' section
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 252 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lb75zaR7DnxE64tcb:-L6Ls7r5ouga5A0IxzeB:bbk62aq) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L252)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

your code seems solid! you did well (+1 for that). Still I think it would be safer to wrap the map content with general try...catch as it is doing massive manipulation on the multiple responses. and it is better not getting runtime errors.
</blockquote></details>

I think it's not needed here since rxjs is wrapping it and if some error happens it will send it to the second callback function of subscribe

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 319 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LfDjMTSJ5KM0BVDPu:-L6LvfVqLQNWsUqBYrXL:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L319)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should provide only 'ok' button and refresh the section once clicked to reflect the updates server status
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 323 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lgkjx_BDf0liLqAbk:-L6LvgEI-jxX0g8vv02B:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L323)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should remove this option
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 435 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lgu6lur16DVjudG2R:-L6LvutKpqIa_RDY8ynF:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L435)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

return a constant value 'unknown provider'
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 466 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lhdua_SQr18u-MMq6:-L6Lw-i8Omz1ZOPoQM9z:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L466)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

use static value 'unknown provider'
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 566 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LiS_4jOp0a7cVjQ_x:-L6Lw8ZqjewahBNjTQMh:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L566)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should provide only 'ok' button and refresh the section once clicked to reflect the updates server status
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 571 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LiT40JU0PkjqgqfYY:-L6Lw9EGpr4CrCsCpO3L:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L571)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please remove this option
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 588 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lj1x3J_u28ZmwIXb-:-L6LwgQWaAq_1nYyHPqg:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L588)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 603 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6Lj5B9QUHgT2KIEC4i:-L6LwiGCa_2oIxM_IQCY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L603)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts, line 618 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LjGTcaYfs52fuvyTy:-L6LwjCXGuSsP2lZIxlL:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts#L618)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can you use the section area blocker here instead? 

if so please provide ok button and refresh once clicked. otherwise just add a refresh action
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-distribution/distributed-profile/distributed-profile.component.html, line 31 at r6](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LkfSh8ND7I4byQdtj:-L6LoA93U8adlyl83SMO:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab2936533212030886899b245311edfad5d8b044/src/applications/content-entries-app/entry/entry-distribution/distributed-profile/distributed-profile.component.html#L31)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

use 'longDateonly' preset for the kDate
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-:-L6LnU_3mxucLp6E8BEf:b-1hwzj0)*

**Comment by esakal** [comment]
Reviewed 5 of 6 files at r7, 20 of 20 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6LlsE09w4y43vkpM9E:-L6RAqScChNLk56ivMXy:b7d9ukl) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK I moved the images into under the sub applications and consumed it using css classes. This is quite beneficial since we let webpack to handle the packaging of those images for us. 

Please review what I did and let me know if what do you think. 

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-L6RB8TBrAtK1nPe4yyc:-L6RB8TBrAtK1nPe4yyd:b-s5nwcq) (no related file):*
You can see it in Amir's account. this happens for width < 1300 px.



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397)*

**Comment by diamond-darrell** [comment]
Review status: 64 of 66 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/397#-L6LlsE09w4y43vkpM9E:-L6RH6PM5v0Fww1I42dJ:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

OK I moved the images into under the sub applications and consumed it using css classes. This is quite beneficial since we let webpack to handle the packaging of those images for us. 

Please review what I did and let me know if what do you think. 
</blockquote></details>

OK

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/397#-L6RB8TBrAtK1nPe4yyc:-L6RPuQBBdLgem6YCIV-:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

You can see it in Amir's account. this happens for width < 1300 px.



</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/397)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/397#-:-L6RS6rOGKsASNPeWiMd:bnfp4nl)*

**Pull request merged**
