### PR TITLE
KMCNG-1178, KMCNG-1092 + without ticket (details in review)

### PR DESCRIPTION
**Pull request by diamond-darrell**
* use recover function if possible
* do not show drop-folders section if user has no permission to use drop-folders

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/319)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/319#-:-L1RGvUPPIBV7oHDG8H4:b-gbeopu)*

**Comment by diamond-darrell** [comment]
+@esakal please check it by yourself, I've added KalturaLogger, but sometimes for some unknown, to me reason, it throws the following error during build


---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/319#-:-L1SdxyBzIG5sFcafzZ2:b14zcpd)*

**Comment by esakal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/319#-L1frNveD2aSsxVCEtih:-L1frNveD2aSsxVCEtii:b-tzwu1h) (no related file):*
+@amirch1 please review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/319)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/319)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/319#-:-L1g1jRbASchQF_3wiS2:bnfp4nl)*

**Pull request merged**
