### PR TITLE
Implement permission FEATURE_DISABLE_CATEGORY_LIMIT

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1596

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/540)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t6RU8DGd22so0aGHd:-L9t6RU8DGd22so0aGHe:ba5xd35) (no related file):*
you should extend this to the max amount  (I think 500). This is not directly related to your implementation but since you allow more then 32 it is safer to ask for 500. also I think it should be the max value (500) and not the one that if configurable (200)



---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts, line 68 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7dwfEGvGSS-QXEfK:-L9t7dwfEGvGSS-QXEfL:b-cvjox4) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts#L68)):*
> ```XML
>           const categoriesCount = (Array.isArray(input.value) ? input.value : []).length;
>           const isCategoriesValid = categoriesCount <= subApplicationsConfig.contentEntriesApp.maxLinkedCategories
>             || this._permissionsService.hasPermission(KMCPermissions.FEATURE_DISABLE_CATEGORY_LIMIT);
> ```

the configuration should hold 2 values. 
```
{ defaultLimit: 32, extendedLimit:200 } 
```
you should use the relevant value according to the permission. Currently you either lock to 32 or allow unlimited categories

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html, line 55 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t88fm4f2sdlU4-Cxm:-L9t88fn8LZx6PtNgCrv:b-oxoprz) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html#L55)):*
> ```HTML
>             <kAutoComplete formControlName="categories"
>                            field="name"
>                            [class.kHasError]="_widgetService.metadataForm.controls['categories'].touched && _widgetService.metadataForm.controls['categories'].invalid"
> ```

see my comment below regarding the touch

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html, line 66 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7ulm7dGmZoj8HmIj:-L9t7ulm7dGmZoj8HmIk:b8v8uam) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html#L66)):*
> ```HTML
>             </kAutoComplete>
>             <div
>               *ngIf="_widgetService.metadataForm.controls['categories'].touched && _widgetService.metadataForm.controls['categories'].invalid"
> ```

you should check if touched OR user tried to submit, otherwise you don't handle a scenario where the entry had 100 categories and after this permission was revoked. in such a scenario you get an error message without any indication on what actually happened.



---

*[src/i18n/en.json, line 1193 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7EbwAvO9rchhlvon:-L9t7EbwAvO9rchhlvoo:b-h9jllh) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/i18n/en.json#L1193)):*
> ```JSON
>           "missingEntriesWarning": "The following entries were not found: {{0}}",
>           "replaceLinkedEntry": "Selecting a new entry will replace the current entry. Continue?",
>           "maxCategoriesLinked": "Entry can be linked with a maximum of \"32\" categories"
> ```

this value should be taken according to the actual value taken from configuration (in our case 32 or 200 but it shouldn't be hard-coded). also remove the wrapping quotation marks

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t6RU8DGd22so0aGHd:-L9tDYOx64udy0GHtST5:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should extend this to the max amount  (I think 500). This is not directly related to your implementation but since you allow more then 32 it is safer to ask for 500. also I think it should be the max value (500) and not the one that if configurable (200)



</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts, line 68 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7dwfEGvGSS-QXEfK:-L9tDZCx4BRTL9EZHTdh:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts#L68)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the configuration should hold 2 values. 
```
{ defaultLimit: 32, extendedLimit:200 } 
```
you should use the relevant value according to the permission. Currently you either lock to 32 or allow unlimited categories
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html, line 55 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t88fm4f2sdlU4-Cxm:-L9tCTMqA3SPdztM2ZWV:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html#L55)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see my comment below regarding the touch
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html, line 66 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7ulm7dGmZoj8HmIj:-L9tCSlz3l-eExDExfzt:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html#L66)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should check if touched OR user tried to submit, otherwise you don't handle a scenario where the entry had 100 categories and after this permission was revoked. in such a scenario you get an error message without any indication on what actually happened.



</blockquote></details>

OK

---

*[src/i18n/en.json, line 1193 at r2](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9t7EbwAvO9rchhlvon:-L9tDHJx7G_zdcCB06ZX:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c6f49fefe4f0440375249131f9a19e34a2cf7dea/src/i18n/en.json#L1193)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this value should be taken according to the actual value taken from configuration (in our case 32 or 200 but it shouldn't be hard-coded). also remove the wrapping quotation marks
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540)*

**Comment by diamond-darrell** [comment]
Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts, line 474 at r3](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-L9tE0b71-YeAo-lx_5f:-L9tE0b71-YeAo-lx_5g:b-8wg134) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e9f64bf233e1f3c9f812bddfdbc7dc2aa02eaf0/src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts#L474)):*
> ```XML
>         return Observable.create(observer =>
>         {
>             this.metadataForm.markAsTouched();
> ```

+@esakal I couldn't test touch issue you've described above since I don't have access to the admin console to remove this permission, but this one should fix it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/540#-:-L9tkq_T5cs7UqJtWDaL:bnfp4nl)*

**Pull request merged**
