### PR TITLE
KMCNG-1601

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1601

**What is the new behavior?**

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/575)

### CODE REVIEW

**Comment by amirch1** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/applications/content-entries-app/entry/entry-live/entry-live.component.html, line 32 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/575#-L9ZW8rEAB7z-m9PETrO:-L9ZW8rEAB7z-m9PETrP:b-ot5bg7) ([raw file](https://github.com/kaltura/kmc-ng/blob/2e429ebb5a66be6ec95640e8b132868c5e37e209/src/applications/content-entries-app/entry/entry-live/entry-live.component.html#L32)):*
> ```HTML
>             <span>{{_widgetService.data?.streamName.replace('%i', '1')}}</span>
>           </div>
>           <div class="kRow" *ngIf="_widgetService?._selectedConversionProfile === 8871861">
> ```

Late hour? :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/575)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/575)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-live/entry-live.component.html, line 32 at r1](https://beta.reviewable.io/reviews/kaltura/kmc-ng/575#-L9ZW8rEAB7z-m9PETrO:-LADgNLZ5x7wO-6-ar7N:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/2e429ebb5a66be6ec95640e8b132868c5e37e209/src/applications/content-entries-app/entry/entry-live/entry-live.component.html#L32)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Late hour? :)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kaltura/kmc-ng/575)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/575#-:-LCbx_1vES5h3oFMU27x:bnfp4nl)*

**Comment by esakal** [comment]
ignoring this pr following request from product. see https://kaltura.atlassian.net/browse/KMCNG-1601

**Pull request closed without merging**
