### PR TITLE
KMCNG-1870 adjustments

### PR DESCRIPTION
**Pull request by esakal**
see: https://kaltura.atlassian.net/browse/KMCNG-1870

closes #716

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/729#-LFm48LQ1WMbqmaqhlRU:-LFm48LQ1WMbqmaqhlRV:be6tacd) (no related file):*
+@diamond-darrell the main difference here is that I limited the places that are aware to this feature

---

*[src/kmc-app/app.routes.ts, line 17 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/729#-LFm3rPc7ViUZQz9y394:-LFm3rPc7ViUZQz9y395:b-akv8l9) ([raw file](https://github.com/kaltura/kmc-ng/blob/f5eb65ddd1b8bca257d92676fd71030d2edbe8e7/src/kmc-app/app.routes.ts#L17)):*
> ```XML
>     },
>     {
>         path: '', canActivate: [AppBootstrap],
> ```

I saw that we are not enforcing `AppBootstrap` on actions

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @diamond-darrell)

---

*[src/kmc-app/app.routes.ts, line 17 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/729#-LFm3rPc7ViUZQz9y394:-LFm4ON7-E8V4W94ujfC:bjwggnk) ([raw file](https://github.com/kaltura/kmc-ng/blob/f5eb65ddd1b8bca257d92676fd71030d2edbe8e7/src/kmc-app/app.routes.ts#L17)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I saw that we are not enforcing `AppBootstrap` on actions
</blockquote></details>

isn't it was by design?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729)*

**Comment by diamond-darrell** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @esakal)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729#-:-LFm4dbQ6OcfLfV2NiSV:bnfp4nl)*

**Comment by esakal** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @esakal)

---

*[src/kmc-app/app.routes.ts, line 17 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/729#-LFm3rPc7ViUZQz9y394:-LFm5LQa6k2yEjN6hdtZ:bu9tzgy) ([raw file](https://github.com/kaltura/kmc-ng/blob/f5eb65ddd1b8bca257d92676fd71030d2edbe8e7/src/kmc-app/app.routes.ts#L17)):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

isn't it was by design?
</blockquote></details>

nope, the one who create actions can access any service available at that point including translations configuration etc

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729)*

**Comment by diamond-darrell** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[src/kmc-app/app.routes.ts, line 17 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/729#-LFm3rPc7ViUZQz9y394:-LFm5hCQ-ytO4vW0Vf9S:bb7m07t) ([raw file](https://github.com/kaltura/kmc-ng/blob/f5eb65ddd1b8bca257d92676fd71030d2edbe8e7/src/kmc-app/app.routes.ts#L17)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

nope, the one who create actions can access any service available at that point including translations configuration etc
</blockquote></details>

okay

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/729)*

**Pull request merged**
