### PR TITLE
My user settings refactoring

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/302)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 5 of 18 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beHipCpeAAHRLjQ-1:-L3beHipCpeAAHRLjQ-2:bpuzpnr) (no related file):*
the text color is gray indicating it is disabled although it is not



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beR_1Pbfj3QsPsScl:-L3beR_1Pbfj3QsPsScm:b-y5vsow) (no related file):*
clicking on the save has no visual feedback when no password was entered. in legacy it shows a message



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beZdRXE53CNrrC4Zp:-L3beZdRXE53CNrrC4Zq:bvoe372) (no related file):*
message is incorrect indicating my password is old. although it is the same in legacy we can/should change it as it appears to be a bug



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3berpUppSLwXoWSCr5:-L3berpUppSLwXoWSCr6:bawjsez) (no related file):*
clicking enter in any popup in this view closes the popup instead of trying to save (or being ignored as we are doing in all the other places)

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3bf8hy0ObQZR4riyfh:-L3bf8hy0ObQZR4riyfi:bmacg63) (no related file):*
changing the name should update the current user profile. for that please add a function in appAuthentication called `public _updateNameManually(firstName: string, lastName: string): void {}`
and update the following. NOTE that you should leave the `_` suffix because this is not best practice but more like a quick&dirty solution 





---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3bk0ANzifjm33kd_-o:-L3bk0ANzifjm33kd_-p:b-9clk46) (no related file):*
message is not formmated correctly. notice the `\n` characters that are shown (instead of replaced with line break)



in legacy


---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 66 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c3e1Meu2DfNeJAFBq:-L3c3e1Meu2DfNeJAFBr:b-1m0z81) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L66)):*
> ```XML
>               },
>               {
>                 label: this._appLocalization.get('app.common.cancel'),
> ```

please remove the cancel option since the user has nothing to do in this view without relevant data. Since we block only the content area he can use the upper menu to navigate away if retry fails

---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 77 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c4RG8TjLoYxZfOjtv:-L3c4RG8TjLoYxZfOjtw:b-6nzil1) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L77)):*
> ```XML
>   }
> 
>   public _updateLoginData(userData: UserUpdateLoginDataActionArgs, popup: string): void {
> ```

if you can limit the popup value to one of the relevant three it would be more stable.

---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 80 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c3wBzFuEhiPffdC17:-L3c3wBzFuEhiPffdC18:b3kre) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L80)):*
> ```XML
>     this._updateBlockerMessage = null;
>     this._myUserSettingsStore
>       .updateLoginData(userData)
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/302)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beHipCpeAAHRLjQ-1:-L3cI-GgBdZmnCmEidMW:borpa7s) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the text color is gray indicating it is disabled although it is not



</blockquote></details>

but it's according to the design https://projects.invisionapp.com/d/main#/console/12328412/261561671/preview

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beR_1Pbfj3QsPsScl:-L3cJw4XC1UFGMPc1eq9:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

clicking on the save has no visual feedback when no password was entered. in legacy it shows a message



</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3bf8hy0ObQZR4riyfh:-L3cPoxXVqTVTe94aHhP:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

changing the name should update the current user profile. for that please add a function in appAuthentication called `public _updateNameManually(firstName: string, lastName: string): void {}`
and update the following. NOTE that you should leave the `_` suffix because this is not best practice but more like a quick&dirty solution 





</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3beZdRXE53CNrrC4Zp:-L3cQ3a-PaoxuF7Or6P4:b-9dgpjd) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

message is incorrect indicating my password is old. although it is the same in legacy we can/should change it as it appears to be a bug



</blockquote></details>

what message should I provide for this case?

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3bk0ANzifjm33kd_-o:-L3cS7x-qan0RrM00o4k:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

message is not formmated correctly. notice the `\n` characters that are shown (instead of replaced with line break)



in legacy


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3berpUppSLwXoWSCr5:-L3cSCTAKpDk2PU-4nyN:bfzkdss) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

clicking enter in any popup in this view closes the popup instead of trying to save (or being ignored as we are doing in all the other places)
</blockquote></details>

Indeed, this is very strange, because the popups are declared in the same way as the rest
+@amirch1 do you know any possible reason for this behavior?

---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 66 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c3e1Meu2DfNeJAFBq:-L3cLXnNk-dZKvrZJKqM:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L66)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please remove the cancel option since the user has nothing to do in this view without relevant data. Since we block only the content area he can use the upper menu to navigate away if retry fails
</blockquote></details>

OK

---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 77 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c4RG8TjLoYxZfOjtv:-L3cN9-lcx0qAzn_63gC:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L77)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

if you can limit the popup value to one of the relevant three it would be more stable.
</blockquote></details>

OK

---

*[src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts, line 80 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3c3wBzFuEhiPffdC17:-L3cN9sIWr9u23y9CDmq:bjs83ap) ([raw file](https://github.com/kaltura/kmc-ng/blob/0494e9f07658991a7521c4a1c3b808639b1bac18/src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts#L80)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

?
</blockquote></details>

what's wrong here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/302)*

**Comment by esakal** [comment]
Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-L3berpUppSLwXoWSCr5:-L3cb4bhspZ83xekGFRs:bfetu0i) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Indeed, this is very strange, because the popups are declared in the same way as the rest
+@amirch1 do you know any possible reason for this behavior?
</blockquote></details>

OK fixed and pushed. the reason was that those buttons where inside the `form` element which delegate enter press to the first button inside it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/302)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/302#-:-L3ccq3zeitil-w78UIL:bnfp4nl)*

**Pull request merged**
