### PR TITLE
KMCNG-964-954-955-932

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/279)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
+@amirch1 +@esakal Providing custom message seems not relevant anymore. Almost all browsers removed custom message support - https://stackoverflow.com/a/38880926/4312928

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-:-KzyF0gyspkNFOGWOnoh:b-fag92k)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 7 of 19 files at r1, 12 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-:-L-C95BxG9dVFnFLcFjn:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 7 of 19 files at r1, 12 of 13 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/app/app.module.ts, line 167 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-R8h-7hWHHKV20I6Eg:-L-R8h-7hWHHKV20I6Eh:bi3qscf) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/app/app.module.ts#L167)):*
> ```XML
>     },
>     ConfirmationService,
>     PageExitVerificationService,
> ```

you should provide services only from the module that own them (using the `forRoot()`) and call that module for root from here. you shouldn't provide them from this module.

---

*[src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts, line 1 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RFHC9A444e3yFPLgB:-L-RFHCAmiDZsIG0d4I2:by1w9ta) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts#L1)):*
> ```XML
> import { Component, Input, OnDestroy } from '@angular/core';
> ```

I'm not reviewing this file changes here. Will review them in [here](https://reviewable.io/reviews/kaltura/kmc-ng/269#-L-BgVmk9Av42oA4oVQY) once we will merge them

---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 24 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RFy0jnW2Q1koVCP2z:-L-RFy0k6L4J_evImRqz:b-ra76ux) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L24)):*
> ```XML
>   }
> 
>   public enablePageExitVerification(verificationMessage?: string): string {
> ```

since the service name is already long, let's try to make it shorter. consider `add` instead of `enablePageExitVerification`

---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 25 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RGAJB0d3UTA5utj_F:-L-RGAJB0d3UTA5utj_G:bk2ue2j) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L25)):*
> ```XML
> 
>   public enablePageExitVerification(verificationMessage?: string): string {
>     this._verificationMessage = verificationMessage;
> ```

I think we decided not to manage verification messages per token? 
If you need to get them from the application (I assume you didn't want to add here dependency to `en.json`. then add another public api method 
```
setVerificationMessage(message: string): void
{
}
```
the default value should be hardcoded in english, you can take the text you added to the i18n .

---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 32 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-ReHCaCJQVwl_zyL_2:-L-ReHCaCJQVwl_zyL_3:b-evyran) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L32)):*
> ```XML
>   }
> 
>   public disablePageExitVerification(token: string): void {
> ```

since the service name is already long, let's try to make it shorter. consider `remove` instead of `disablePageExitVerification`

---

*[src/shared/kmc-shell/page-exit-verification/upload-page-exit-verification.service.ts, line 25 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RdxKGUrrM8vFkAlF8:-L-RdxKGUrrM8vFkAlF9:bi9z0q7) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/upload-page-exit-verification.service.ts#L25)):*
> ```XML
>       // run checkout on the next tick to make sure file was removed from trackedFiles list
>       setTimeout(() => {
>         if (!this._uploadManagement.getTrackedFiles().length) {
> ```

upload management manages many file types, not only those that interest you so you cannot rely on the length.

I think you can simplify the logic by managing inner list of files that interest you by id. when added update the array and here check the length of that inner list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 10 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RkkrShnxYAtwmyaN8:-L-RkkrShnxYAtwmyaN9:b-hodfy4) ([raw file](https://github.com/kaltura/kmc-ng/blob/b5c81866cf1e48d86da678d31d5f97e2e7d2d5f0/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L10)):*
> ```XML
> import { KalturaUploadFile } from 'app-shared/kmc-shared';
> 
> type MonitoredUploadFile = NewEntryUploadFile | NewEntryFlavourFile;
> ```

+@diamond-darrell I added a new type which is used to declare those that we interest with.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 121 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RkuEayrS1zGWMfZcg:-L-RkuEayrS1zGWMfZch:b-lp6lyu) ([raw file](https://github.com/kaltura/kmc-ng/blob/b5c81866cf1e48d86da678d31d5f97e2e7d2d5f0/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L121)):*
> ```XML
>   private _addFile(trackedFile: TrackedFileData): void {
> 
>     if (isMonitoredUploadFile(trackedFile.data)) {
> ```

+@diamond-darrell I think this is needed, wdyt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/app.module.ts, line 167 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-R8h-7hWHHKV20I6Eg:-L-VX0W-PSuf8vNCqzYY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/app/app.module.ts#L167)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you should provide services only from the module that own them (using the `forRoot()`) and call that module for root from here. you shouldn't provide them from this module.
</blockquote></details>

OK

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 10 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RkkrShnxYAtwmyaN8:-L-VX_YkyzgfPn8QJaeo:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/b5c81866cf1e48d86da678d31d5f97e2e7d2d5f0/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L10)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@diamond-darrell I added a new type which is used to declare those that we interest with.
</blockquote></details>

OK

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 121 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RkuEayrS1zGWMfZcg:-L-VX7IN3H6Fy00pMAJN:b-v7v5go) ([raw file](https://github.com/kaltura/kmc-ng/blob/b5c81866cf1e48d86da678d31d5f97e2e7d2d5f0/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L121)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@diamond-darrell I think this is needed, wdyt?
</blockquote></details>

I'm not sure, we are already filtering this types, why do we need to check them twice?

---

*[src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts, line 1 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RFHC9A444e3yFPLgB:-L-VXXrAlxKWbnjumKof:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm not reviewing this file changes here. Will review them in [here](https://reviewable.io/reviews/kaltura/kmc-ng/269#-L-BgVmk9Av42oA4oVQY) once we will merge them
</blockquote></details>

OK

---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 24 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RFy0jnW2Q1koVCP2z:-L-VVY9Q9NL-8QJfF-mC:bmn8ehd) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L24)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

since the service name is already long, let's try to make it shorter. consider `add` instead of `enablePageExitVerification`
</blockquote></details>

okay, I thought about it too, but a user of this service can inject this service using not so self-explanatory name, so I've decided to keep a long name

---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 25 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RGAJB0d3UTA5utj_F:-L-VWF0hu7gJ25t0O69D:b-iyu304) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L25)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I think we decided not to manage verification messages per token? 
If you need to get them from the application (I assume you didn't want to add here dependency to `en.json`. then add another public api method 
```
setVerificationMessage(message: string): void
{
}
```
the default value should be hardcoded in english, you can take the text you added to the i18n .
</blockquote></details>

okay, but it seems that providing this name is not relevant anymore, have you seen my comment?


---

*[src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts, line 32 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-ReHCaCJQVwl_zyL_2:-L-VWP9l7Q4yt7SlSW0T:b9zf3zk) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/page-exit-verification.service.ts#L32)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

since the service name is already long, let's try to make it shorter. consider `remove` instead of `disablePageExitVerification`
</blockquote></details>

same as for enabling

---

*[src/shared/kmc-shell/page-exit-verification/upload-page-exit-verification.service.ts, line 25 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RdxKGUrrM8vFkAlF8:-L-VWoNf7OLwUwBqz-Th:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e2477a63f0b524fbe8eea3d473a75f46b19785ab/src/shared/kmc-shell/page-exit-verification/upload-page-exit-verification.service.ts#L25)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

upload management manages many file types, not only those that interest you so you cannot rely on the length.

I think you can simplify the logic by managing inner list of files that interest you by id. when added update the array and here check the length of that inner list.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 19 files at r1, 6 of 13 files at r2, 1 of 1 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 121 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-L-RkuEayrS1zGWMfZcg:-L-VtVRqlyQVrVl99768:bsyhj1i) ([raw file](https://github.com/kaltura/kmc-ng/blob/b5c81866cf1e48d86da678d31d5f97e2e7d2d5f0/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L121)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I'm not sure, we are already filtering this types, why do we need to check them twice?
</blockquote></details>

discussed during the call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279)*

**Comment by esakal** [comment]
Reviewed 8 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/279#-:-L-aSRN9WvgOv9rcG1tX:bnfp4nl)*

**Pull request merged**
