### PR TITLE
KMCNG-37

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Login screen can only login user to the system.

**What is the new behavior?**
Implement a new design according to invision templates. Implement missing screens such as forget password, reset password and error in login hash screens with all theirs functional requirements.

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/181)

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @diamond-darrell,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by esakal** [comment]
Reviewed 2 of 8 files at r2.
Review status: 2 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/components/login/index.ts, line 1 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-QKd6otnfpKAK9Hi1:-Kr-QKd7Z13O8rorkSkC:buoxsvb) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae1cceb38e703a25add6363b3e3c01207511bd42/src/app/components/login/index.ts#L1)):*
> ```XML
> export * from './login.component';
> ```

**Convention**

Creating index.ts file is very useful. We use it mostly for infrastructure modules. For applicative modules we usually avoid creating index file because we tend to import component directly. 

We do so mainly since the intellisense of the IDE execute automatic import directly from the file (and not from the index file) and also because applicative modules usually don't expose many components to other modules where the index files are used alot.

If you think otherwise let's discuss and find the best approach :)

Just to be clear we always use it for shared/infrastructure modules when you import from other modules like the following examples: [kmc-shell](https://github.com/kaltura/kmc-ng/blob/master/src/shared/kmc-shell/index.ts), [@kaltura-ng/kaltura-ui](https://github.com/kaltura/kaltura-ng/blob/master/kaltura-ui/src/index.ts)

---

*[src/app/components/login/login.component.ts, line 8 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-gMF3z4UodRNbJshj:-Kr-gMF4-k2pO1d_EjwA:bw40olb) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/app/components/login/login.component.ts#L8)):*
> ```XML
> import { TranslateService } from 'ng2-translate';
> 
> export enum LoginScreen {
> ```

**Convention**

use plural naming for enum `LoginScreens`

---

*[src/app/components/login/login.component.ts, line 31 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-giglcncgcWs6k6xc:-Kr-giglcncgcWs6k6xd:b-bggee4) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/app/components/login/login.component.ts#L31)):*
> ```XML
>   signUpLink = environment.core.externalLinks.SIGNUP;
> 
>   constructor(private appAuthentication: AppAuthentication,
> ```

**Convention**
1. prefix private properties/functions with '_'. for example: `_appNavigator`, `_browserService`
2. always opt to use the `private` scope where possible
3. for properties/functions used by the component template, we wished it could be private but it is currently not possible. so we are folllowing the convention of public properties/functions with the prefix '_' indicating it should have been private. for example all your properties above should be `_username`,`_errorMessage`, `_showLogin` etc...
4. use public properties/functions only for components/services public api.



Regarding issue 3 - the private scope accessibility from the component template. If you want to read more about this issue see the [following issue](https://github.com/angular/angular/issues/11422) in Angular repository. 

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 57 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-nUpoBTWMx4tNE7fg:-Kr-nUpoBTWMx4tNE7fh:b-48wsik) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/shared/kmc-shell/auth/app-authentication.service.ts#L57)):*
> ```XML
>   }
> 
>   resetPassword(email: string) {
> ```

**Convention**
please add return value to the declaration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by esakal** [comment]
Reviewed 13 of 18 files at r1, 5 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by esakal** [comment]
Hi,

We are almost there. few things:

1. Reviewable track our conversations and try to figure out if we have unresolved issues. It will not allow me to complete the review unless you reply to my comments with the word **OK** .
2.  Did you complete the implementation of the [login PRD](https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/223157868/Login) or do you have open/pending implementations? 

---

Reviewed 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/components/login/login.component.ts, line 8 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-gMF3z4UodRNbJshj:-Kr0qT0B1PPJRvrUjxIr:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/app/components/login/login.component.ts#L8)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

**Convention**

use plural naming for enum `LoginScreens`
</blockquote></details>

OK

---

*[src/app/components/login/login.component.ts, line 31 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-giglcncgcWs6k6xc:-Kr0qsGTs9PgHrp9wX1Z:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/app/components/login/login.component.ts#L31)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

**Convention**
1. prefix private properties/functions with '_'. for example: `_appNavigator`, `_browserService`
2. always opt to use the `private` scope where possible
3. for properties/functions used by the component template, we wished it could be private but it is currently not possible. so we are folllowing the convention of public properties/functions with the prefix '_' indicating it should have been private. for example all your properties above should be `_username`,`_errorMessage`, `_showLogin` etc...
4. use public properties/functions only for components/services public api.



Regarding issue 3 - the private scope accessibility from the component template. If you want to read more about this issue see the [following issue](https://github.com/angular/angular/issues/11422) in Angular repository. 

</blockquote></details>

OK

---

*[src/app/components/login/login-form/login-form.component.ts, line 11 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr0ti0FrgyAMeyP1FQn:-Kr0ti0FrgyAMeyP1FQo:b8pyjh0) ([raw file](https://github.com/kaltura/kmc-ng/blob/7d98ca7e084034ae0789efcd7a5713fcffed7e91/src/app/components/login/login-form/login-form.component.ts#L11)):*
> ```XML
> })
> export class LoginFormComponent {
>   @Input() _inProgress = false;
> ```

The @input properties are part of the public api so they don't need the prefix of '_'

this is the only place that should be refactored because you did it correctly in other places :)

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 57 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-nUpoBTWMx4tNE7fg:-Kr0sNEkf1k8iq28zdcS:b-kam088) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/shared/kmc-shell/auth/app-authentication.service.ts#L57)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

**Convention**
please add return value to the declaration
</blockquote></details>

we prefer not using any if possible. you can get the actual response type from the `UserResetPasswordAction`. I think it returns `void`

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 117 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr0skpidI9T5T0frXtL:-Kr0skpidI9T5T0frXtM:b-j9k3yn) ([raw file](https://github.com/kaltura/kmc-ng/blob/7d98ca7e084034ae0789efcd7a5713fcffed7e91/src/shared/kmc-shell/auth/app-authentication.service.ts#L117)):*
> ```XML
>   }
> 
>   updatePassword(payload: IUpdatePasswordPayload): Observable<{ email: string, password: string }> {
> ```

FYI

Actually we don't mind using anonymous declaration. We use interface only one of the following apply:
- the same declaration is used in multiple places.
- the declaration contains a lot of properties
- we want to define an interface to be implemented by classes

So you can leave it with interfaces but for future implementation know that you can choose between interfacing and anonymous declaration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-:-Kr0u54yYNj_q0Q3_4Oh:b-nzgy00)*

**Comment by diamond-darrell** [comment]
1) Oh, ok, I thought that acknowledge button is enough
2) I have one thing left - it's errors in tooltip, I'll push them with my next fixes

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-:-Kr0y6InQiQ7GcUKWNnd:bve8qnn)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/components/login/login-form/login-form.component.ts, line 11 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr0ti0FrgyAMeyP1FQn:-Kr0yRpqyPYvTJ9KnS_e:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/7d98ca7e084034ae0789efcd7a5713fcffed7e91/src/app/components/login/login-form/login-form.component.ts#L11)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The @input properties are part of the public api so they don't need the prefix of '_'

this is the only place that should be refactored because you did it correctly in other places :)
</blockquote></details>

OK

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 57 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-nUpoBTWMx4tNE7fg:-Kr0yXu2pRQsXR9L3ktu:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/a4cf48aeb65a0a19362ea51eb240e260ef4118be/src/shared/kmc-shell/auth/app-authentication.service.ts#L57)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we prefer not using any if possible. you can get the actual response type from the `UserResetPasswordAction`. I think it returns `void`
</blockquote></details>

OK

---

*[src/shared/kmc-shell/auth/app-authentication.service.ts, line 117 at r4](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr0skpidI9T5T0frXtL:-Kr0yib2S4N9NezeLQ31:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/7d98ca7e084034ae0789efcd7a5713fcffed7e91/src/shared/kmc-shell/auth/app-authentication.service.ts#L117)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

FYI

Actually we don't mind using anonymous declaration. We use interface only one of the following apply:
- the same declaration is used in multiple places.
- the declaration contains a lot of properties
- we want to define an interface to be implemented by classes

So you can leave it with interfaces but for future implementation know that you can choose between interfacing and anonymous declaration
</blockquote></details>

OK

---

*[src/app/components/login/index.ts, line 1 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr-QKd6otnfpKAK9Hi1:-Kr0yhHofHlXQvabGlFo:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ae1cceb38e703a25add6363b3e3c01207511bd42/src/app/components/login/index.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

**Convention**

Creating index.ts file is very useful. We use it mostly for infrastructure modules. For applicative modules we usually avoid creating index file because we tend to import component directly. 

We do so mainly since the intellisense of the IDE execute automatic import directly from the file (and not from the index file) and also because applicative modules usually don't expose many components to other modules where the index files are used alot.

If you think otherwise let's discuss and find the best approach :)

Just to be clear we always use it for shared/infrastructure modules when you import from other modules like the following examples: [kmc-shell](https://github.com/kaltura/kmc-ng/blob/master/src/shared/kmc-shell/index.ts), [@kaltura-ng/kaltura-ui](https://github.com/kaltura/kaltura-ng/blob/master/kaltura-ui/src/index.ts)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by amirch1** [comment]
Review status: 6 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-Kr9vBZGuoilsH91i0VO:-Kr9vBZGuoilsH91i0VP:b-85sewb) (no related file):*
Seems that the login fields still get the yellow background

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by amirch1** [comment]
Reviewed 1 of 18 files at r1, 5 of 16 files at r4, 14 of 14 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by esakal** [comment]
:lgtm:  I don't have any comments. Once +@amirch1 will complete the review we can merge it to our master.

---

Reviewed 8 of 14 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-:-KrB20V_3Osp6ty1c-zz:b8ku6kb)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r6.
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181#-:-KrB3ByFDN1mq3ShEKht:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/181)*

**Pull request merged**
