### PR TITLE
KMCNG-1074

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/292)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
+@amirch1 +@esakal 


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-:-L-Ga3KCxoaJtfRFelQt:bxm0pui)*

**Comment by esakal** [comment]
I liked your design. I don't want us to start and recover from that edge case. but we should always be friendly to the user and explain why thinks happens. see my comment below

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 169 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-L-R7oPQBSBuH_CBQTg0:-L-R7oPQBSBuH_CBQTg1:bng48c9) ([raw file](https://github.com/kaltura/kmc-ng/blob/98e73c06454e86614a2dc01ea68fe0ab1747017e/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L169)):*
> ```XML
>     if (file.entryId) {
>       this._uploadManagement.resumeUpload(file.id);
>     }
> ```

if we don't have an entry, we cannot ignore the user but we can show him explanation why. Let's show the user here a message that: 'Cannot resume upload for the requested file. Please upload the file again.'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-:-L-R83pyl6rdVDdcReQE:b-pu7h6)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 169 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-L-R7oPQBSBuH_CBQTg0:-L-VUtV8LpyUbmegofD_:b-f9wadn) ([raw file](https://github.com/kaltura/kmc-ng/blob/98e73c06454e86614a2dc01ea68fe0ab1747017e/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L169)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

if we don't have an entry, we cannot ignore the user but we can show him explanation why. Let's show the user here a message that: 'Cannot resume upload for the requested file. Please upload the file again.'
</blockquote></details>

You mean to show it in a popup or tooltip? For the second case where should I put it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-upload-control-app/upload-list/upload-list.component.ts, line 169 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-L-R7oPQBSBuH_CBQTg0:-L-W-NwZMk2RvznojYcQ:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/98e73c06454e86614a2dc01ea68fe0ab1747017e/src/applications/content-upload-control-app/upload-list/upload-list.component.ts#L169)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

You mean to show it in a popup or tooltip? For the second case where should I put it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/292#-:-L-_wXUgGUTIUfFWs0R6:bnfp4nl)*

**Pull request merged**
