### PR TITLE
Feat: add reset password view/flow (KMCNG-1182)

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LE3cBLD-k9xoNXfc0hs:b-l3i0qd) (no related file):*
providing an invalid key has a dedicated view as shown below.
To reproduce it navigate to:
1. https://kmc.kaltura.com/index.php/kmc/kmc/setpasshashkey/eransakal
2. localhost:4200/actions/restore-password/eransakal



---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3eULPCp1XtZ9inT9h:-LE3eULPCp1XtZ9inT9i:b4krnnk) (no related file):*
The error from the server should be removed automatically once the user start typing a new password.

+@amirch1 maybe we should consider clearing previous values in the fields as well? wdyt?



---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3f-GWBgejM0n6B7Io:-LE3f-GX4xsmE6vjDiPE:bqzf3yb) (no related file):*
pressing the ok button should redirect to login (currently does nothing)


---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3g4C080ypWKj5eYnr:-LE3g4C1EkOzXsRlqTii:b3hwdbh) (no related file):*
separate into two lines. Capitalize the 'Please'


---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3gyzZ0qi3zfEOm8CE:-LE3gyzZ0qi3zfEOm8CF:b-h3804u) (no related file):*
please read [kmcng-1789](https://kaltura.atlassian.net/browse/KMCNG-1789) and make sure our flow works as expected

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LE8PrfH-xISKEk9vYlz:b-jc9oho) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

providing an invalid key has a dedicated view as shown below.
To reproduce it navigate to:
1. https://kmc.kaltura.com/index.php/kmc/kmc/setpasshashkey/eransakal
2. localhost:4200/actions/restore-password/eransakal



</blockquote></details>

Which action should I use to determine the validity of the provided hash? The legacy receives this data in the template


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3eULPCp1XtZ9inT9h:-LE8Xt6p8KdMgNC6c_RG:bdd92lg) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The error from the server should be removed automatically once the user start typing a new password.

+@amirch1 maybe we should consider clearing previous values in the fields as well? wdyt?



</blockquote></details>

it was a bug, I've forgotten to pass errorCode to the component, it should be like this


---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3f-GWBgejM0n6B7Io:-LE8Y3yG5TsUdqDQ-R04:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

pressing the ok button should redirect to login (currently does nothing)


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3g4C080ypWKj5eYnr:-LE8Y54p1IN9IJm8Qj_Q:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

separate into two lines. Capitalize the 'Please'


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3gyzZ0qi3zfEOm8CE:-LE8Y5jN-fdBQcVyB7O-:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please read [kmcng-1789](https://kaltura.atlassian.net/browse/KMCNG-1789) and make sure our flow works as expected
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3eULPCp1XtZ9inT9h:-LEE-4GeDDZ4tjgf6m-b:bq75hcy) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

it was a bug, I've forgotten to pass errorCode to the component, it should be like this


</blockquote></details>

did you take this from the configuration? how are you showing general errors?

---

*[src/kmc-app/app.routes.ts, line 21 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE-Gy14RV86kOwf9-x:-LEE-Gy14RV86kOwf9-y:b-jqod4e) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/app.routes.ts#L21)):*
> ```XML
>             { path: 'login-by-ks/:ks', component: LoginByKSComponent, pathMatch: 'full' },
>             { path: 'restore-password/:hash', component: RestorePasswordComponent, pathMatch: 'full'  },
>             { path: '**', redirectTo: '../login' }
> ```

why did you provide a fallback route? We are going to remove all implicit redirects soon 

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEE0R5a3lDxDrnl0O5K:baju198) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
> ```XML
>       const restorePasswordArgs = this._restorePasswordView.popOpenArgs();
>       if (restorePasswordArgs && restorePasswordArgs.hash) {
>           this._validateHash(restorePasswordArgs.hash)
> ```

since this operation will be async (a request to the server). the use will see the login component for a short time and then it will be replaced with once of the new screens......

you should handle it by either: 
1.  add a new screen with a text that we are checking the hash key
2. use the block shell and add an handling in case of request failure

I think the second is easier

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LEE1bg0AH6K7L-gbZ64:bppkwnf) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

Which action should I use to determine the validity of the provided hash? The legacy receives this data in the template


</blockquote></details>

I'm still waiting to a response from the backend

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3eULPCp1XtZ9inT9h:-LEE399a1wA3gJxJbPol:bs7e3zb) (no related file):*
> did you take this from the configuration?
not sure what do you mean

> how are you showing general errors?
like it was before - the text below fields in red color

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LEE41gB27Sa67R4ZVb-:b32wtd) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm still waiting to a response from the backend
</blockquote></details>

ok

---

*[src/kmc-app/app.routes.ts, line 21 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE-Gy14RV86kOwf9-x:-LEE3MznD81XhTZxiBKv:b-r0t8fu) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/app.routes.ts#L21)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

why did you provide a fallback route? We are going to remove all implicit redirects soon 
</blockquote></details>

I thought to provide a 404 page, but those pages accessible only from email (means it's we are generating the link, not user) or for tech stuff (means they know what they doing 🙂), so I've decided to put a redirect to login

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEE3wv5807XjCtZJGMQ:bxe6krr) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

since this operation will be async (a request to the server). the use will see the login component for a short time and then it will be replaced with once of the new screens......

you should handle it by either: 
1.  add a new screen with a text that we are checking the hash key
2. use the block shell and add an handling in case of request failure

I think the second is easier
</blockquote></details>

yep, I was thinking to do the second option too

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by diamond-darrell** [comment]
Review status: 19 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/kmc-app/app.routes.ts, line 21 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE-Gy14RV86kOwf9-x:-LEEAe67BlsE0k1lSraf:b-hfpv0l) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/app.routes.ts#L21)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I thought to provide a 404 page, but those pages accessible only from email (means it's we are generating the link, not user) or for tech stuff (means they know what they doing 🙂), so I've decided to put a redirect to login
</blockquote></details>

removed

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEEAfMEA9zWmFKhI-bn:b-wrcjap) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

yep, I was thinking to do the second option too
</blockquote></details>

will add once we have the action to send

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by esakal** [comment]
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LEJKhTa7NPzbI5KQBMv:b-uuj6ed) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

ok
</blockquote></details>

OK I have the uri for you:
1. add a server configuration value `kalturaServer.resetPasswordUri` (optional value)
2 when trying to reset the password, in the function you added:
2.1 if configuration not provided - write to log and navigate to error page `this._browserService.navigateToError();`
2.2 otherwise, replace `{hash}` token with actual token in provided uri and transmit a request
2.3 expect the following response structure:
`{ errorCode: "" }`
2.4 if error code is empty -> assume valid hash, otherwise show the relevant view (no need to handle different error codes)
2.5 if failed to execute the request -> show confirmation suggesting to either retry or navigate to login page.

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEJIIhECUvJjxDgsvRS:bjtz59x) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

will add once we have the action to send
</blockquote></details>

see general comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by esakal** [comment]
Review status: 13 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEJMqJv5_HZybf9VDDO:b-nk0hcn) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see general comment
</blockquote></details>

Not sure why the general comments was resolved by me, coping the content to here:

1. add a server configuration value kalturaServer.resetPasswordUri (optional value)
2 when trying to reset the password, in the function you added:
2.1 if configuration not provided - write to log and navigate to error page this._browserService.navigateToError();
2.2 otherwise, replace {hash} token with actual token in provided uri and transmit a request
2.3 expect the following response structure:
{ errorCode: "" }
2.4 if error code is empty -> assume valid hash, otherwise show the relevant view (no need to handle different error codes)
2.5 if failed to execute the request -> show confirmation suggesting to either retry or navigate to login page.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by diamond-darrell** [comment]
Review status: 17 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LE3cBLC563wvBU_Y5NH:-LEJS4TABomCmt0foGa5:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

OK I have the uri for you:
1. add a server configuration value `kalturaServer.resetPasswordUri` (optional value)
2 when trying to reset the password, in the function you added:
2.1 if configuration not provided - write to log and navigate to error page `this._browserService.navigateToError();`
2.2 otherwise, replace `{hash}` token with actual token in provided uri and transmit a request
2.3 expect the following response structure:
`{ errorCode: "" }`
2.4 if error code is empty -> assume valid hash, otherwise show the relevant view (no need to handle different error codes)
2.5 if failed to execute the request -> show confirmation suggesting to either retry or navigate to login page.
</blockquote></details>

OK

---

*[src/kmc-app/components/login/login.component.ts, line 68 at r4](https://reviewable.io/reviews/kaltura/kmc-ng/331#-LEE0R5_6BrjYKC7Wppf:-LEJMFvZ-vNnSJrj4xGA:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/21ade9fb475b539d7b8b59407d0d8dd50a4b8a53/src/kmc-app/components/login/login.component.ts#L68)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Not sure why the general comments was resolved by me, coping the content to here:

1. add a server configuration value kalturaServer.resetPasswordUri (optional value)
2 when trying to reset the password, in the function you added:
2.1 if configuration not provided - write to log and navigate to error page this._browserService.navigateToError();
2.2 otherwise, replace {hash} token with actual token in provided uri and transmit a request
2.3 expect the following response structure:
{ errorCode: "" }
2.4 if error code is empty -> assume valid hash, otherwise show the relevant view (no need to handle different error codes)
2.5 if failed to execute the request -> show confirmation suggesting to either retry or navigate to login page.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/331#-:-LEK0sxt3jMAnIuFfh61:bnfp4nl)*

**Pull request merged**
