### PR TITLE
Check and remove if possible all occurrences of `getElementsByClassName`

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/264)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/administration-roles-app/roles/roles-table.component.ts, line 102 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylppOgxD21CPUj3VUi:-KylppOgxD21CPUj3VUj:b9nmts4) ([raw file](https://github.com/kaltura/kmc-ng/blob/231da7038fa11815b9f63b9f73f313301e59ada6/src/applications/administration-roles-app/roles/roles-table.component.ts#L102)):*
> ```XML
> 
>   ngAfterViewInit() {
>     const scrollBody = this._dataTable.el.nativeElement.getElementsByClassName('ui-datatable-scrollable-body');
> ```

do we need to replace it with directive on the actions menu bar instead? You should use [kMenuCloseOnScroll](https://github.com/kaltura/kmc-ng/blob/3fdea43973cabcb80b44d39cc67872f4d8c3cf4b/src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.html#L56)

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts, line 63 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylpwVldQW7nZtqC1oF:-KylpwVldQW7nZtqC1oG:b-fy52ru) ([raw file](https://github.com/kaltura/kmc-ng/blob/231da7038fa11815b9f63b9f73f313301e59ada6/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts#L63)):*
> ```XML
>         this._filter.pageSize = query.data.pageSize;
>         this._filter.pageIndex = query.data.pageIndex - 1;
>         this.dataTable.scrollToTop();
> ```

do we need to manually scroll the page using `browserService` once we query a table?
You should call `browserService.scrollToTop()` instead. also consider moving those calls to the services 

---

*[src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.html, line 3 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylqMyGb7hwgxF_ePRr:-KylqMyGb7hwgxF_ePRs:b3kre) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.html#L3)):*
> ```HTML
> <k-area-blocker [showLoader]="_showLoader" [message]="_blockerMessage">
>   <div class="kOverrideFAIcons kRefineFilters">
>     <kScrollToTopContainer #refine class="kTreeContainer">
> ```

?

---

*[src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.ts, line 78 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylqW15ABdaPlrES0l3:-KylqW15ABdaPlrES0l4:b-g9it2o) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.ts#L78)):*
> ```XML
>   // keep for cancelOnDestroy operator
>   ngOnDestroy() {
>     if (this._parentPopupStateChangeSubscribe) {
> ```

this is not needed since the code has `cancelOnDestory` operator.

---

*[src/applications/content-playlists-app/playlist/playlist-sections-list/playlist-sections-list.component.ts, line 50 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylqicWaYkH68ga-zuR:-KylqicWaYkH68ga-zuS:b-7m74ox) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/applications/content-playlists-app/playlist/playlist-sections-list/playlist-sections-list.component.ts#L50)):*
> ```XML
> 
>             // TODO [kmcng] will be removed after merge of the playlists-adjustments branch
>             const relevantSection = this.sections.find(({ id }) => response.section === name);
> ```

nice!

---

*[src/shared/content-shared/scroll-to-top-container/scroll-to-top-container.component.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KyoJxsybwFeVwvw4xa6:-KyoJxsybwFeVwvw4xa7:b-9bn8b8) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/shared/content-shared/scroll-to-top-container/scroll-to-top-container.component.ts#L1)):*
> ```XML
> import { Component, ElementRef } from '@angular/core';
> ```

move this please to `kaltura-ui`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Comment by amirch1** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Comment by diamond-darrell** [comment]
Review status: 11 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/applications/administration-roles-app/roles/roles-table.component.ts, line 102 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylppOgxD21CPUj3VUi:-KyolW54csTytf4fqoVU:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/231da7038fa11815b9f63b9f73f313301e59ada6/src/applications/administration-roles-app/roles/roles-table.component.ts#L102)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

do we need to replace it with directive on the actions menu bar instead? You should use [kMenuCloseOnScroll](https://github.com/kaltura/kmc-ng/blob/3fdea43973cabcb80b44d39cc67872f4d8c3cf4b/src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.html#L56)
</blockquote></details>

OK

---

*[src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts, line 63 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylpwVldQW7nZtqC1oF:-KyolX1VA6ZckEueXTCA:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/231da7038fa11815b9f63b9f73f313301e59ada6/src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts#L63)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

do we need to manually scroll the page using `browserService` once we query a table?
You should call `browserService.scrollToTop()` instead. also consider moving those calls to the services 
</blockquote></details>

OK

---

*[src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.ts, line 78 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KylqW15ABdaPlrES0l3:-KyolkRKZqPdBjF09se_:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.ts#L78)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not needed since the code has `cancelOnDestory` operator.
</blockquote></details>

OK

---

*[src/shared/content-shared/scroll-to-top-container/scroll-to-top-container.component.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-KyoJxsybwFeVwvw4xa6:-KyolmKkouD5hm4chDHT:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ba89e8024ecb10db26d1cd29e3c6b3e8585d3db8/src/shared/content-shared/scroll-to-top-container/scroll-to-top-container.component.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move this please to `kaltura-ui`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Comment by diamond-darrell** [comment]
Review status: 11 of 28 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/264#-Kyom1eusWFhTtCg9DEV:-Kyom1eusWFhTtCg9DEW:b-yikp1o) (no related file):*
+@esakal ScrollToTopContainer component in the kaltura-ng repo - https://reviewable.io/reviews/kaltura/kaltura-ng/30

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Comment by esakal** [comment]
Reviewed 18 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/264)*

**Pull request merged**
