### PR TITLE
Entry uploads refactoring

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/214)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 322 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv226uV7HBGSe16Gmb2:-Kv226uV7HBGSe16Gmb3:b-7yl8g3) ([raw file](https://github.com/kaltura/kmc-ng/blob/22b8d8b4ead43a9c8743898e5389e88f41925c2c/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L322)):*
> ```XML
>               const resource = new KalturaUploadedFileTokenResource({ token });
>               if (relevantFlavor) {
>                 if (relevantFlavor.id.length) {
> ```

consider checking that `relevantFlavor.id` is not null (or just remove the `length` part if we can assume id will never equal 0;

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts, line 274 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv2BfdN2bPdSnXYqjvI:-Kv2BfdN2bPdSnXYqjvJ:b3scau8) ([raw file](https://github.com/kaltura/kmc-ng/blob/22b8d8b4ead43a9c8743898e5389e88f41925c2c/src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts#L274)):*
> ```XML
> 	public _onFileSelected(selectedFiles: FileList) {
>         if (selectedFiles && selectedFiles.length) {
>             const entryCaptionFiles = Array.from(selectedFiles).map(file => new NewEntryRelatedFile(file));
> ```

minor - name should be `entryRelatedFiles`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 322 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv226uV7HBGSe16Gmb2:-Kv2CiEpsNUNip7aYt7u:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/22b8d8b4ead43a9c8743898e5389e88f41925c2c/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L322)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider checking that `relevantFlavor.id` is not null (or just remove the `length` part if we can assume id will never equal 0;
</blockquote></details>

OK

---

*[src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts, line 274 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv2BfdN2bPdSnXYqjvI:-Kv2ChU5jAhl_wky-Nn0:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/22b8d8b4ead43a9c8743898e5389e88f41925c2c/src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts#L274)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

minor - name should be `entryRelatedFiles`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by esakal** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 318 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv2PD6qt_4_blx6J5Vz:-Kv2PD6qt_4_blx6J5W-:bd1eqsi) ([raw file](https://github.com/kaltura/kmc-ng/blob/1483330e1114b9a4587a063541d4bbce96fb6f59/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L318)):*
> ```XML
> 
>           switch (uploadedFile.status) {
>             case TrackedFileStatuses.uploadCompleted:
> ```

we just understood that this logic is wrong. We should perform the update/add flavor once we have server token (as in entry upload where we are creating the entry immediately).

If the update/add fails we should cancel the upload (as I saw you did somewhere). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 318 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv2PD6qt_4_blx6J5Vz:-Kv2XcFm6ZZ_d_Yiip54:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/1483330e1114b9a4587a063541d4bbce96fb6f59/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L318)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we just understood that this logic is wrong. We should perform the update/add flavor once we have server token (as in entry upload where we are creating the entry immediately).

If the update/add fails we should cancel the upload (as I saw you did somewhere). 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 305 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv5zTu9jV-BWMMkxbKl:-Kv5zTu9jV-BWMMkxbKm:b-wb00y0) ([raw file](https://github.com/kaltura/kmc-ng/blob/8c08508fe8babb0d470d13e4367974de5ac8fa84/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L305)):*
> ```XML
>     this._uploadManagement.onFileStatusChanged$
>       .cancelOnDestroy(this)
>       .filter(uploadedFile => uploadedFile.data instanceof NewEntryFlavourFile)
> ```

consider using `.map()` instead and return `matching flavor of current entry` if found or `null` otherwise.

This way you don't need to handle in multiple places scenario when the user navigated to new entry before the upload of flavor was completed:
- in `waitingUpload` you don't need to refresh if not flavor of current entry
- in `uploadCompleted` you also don't need to refresh if not flavor of current entry
- in `uploadFailed` you should not show error if it happen to a previous entry.
- (there might be others - please check) 

if you can implement this approach in captions/related as well.

:)

---

*[src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts, line 368 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-Kv60GPi2p4ys-U1seLR:-Kv60GPi2p4ys-U1seLS:b-83sjoh) ([raw file](https://github.com/kaltura/kmc-ng/blob/8c08508fe8babb0d470d13e4367974de5ac8fa84/src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts#L368)):*
> ```XML
>       .monitor('set flavor resource')
>       .catch((err, caught) => {
>         this._uploadManagement.cancelUploadWithError(flavor.uploadFileId, 'Cannot update flavor, cancel related file');
> ```

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214#-:-KvS-N-k-toI-5bD8gjl:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/214)*

**Pull request merged**
