### PR TITLE
 Content > Categories > Filters 

### PR DESCRIPTION
**Pull request by benstov**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [X] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/312)

### CODE REVIEW

**Comment by benstov** [comment]
Categories tree still hasn't implemented (waiting for Eran notification when it is ready to integrate)

**Comment by esakal** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 106 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E2mvdRpKMVTyyTFNj:-L1E2mvdRpKMVTyyTFNk:b8ubzcm) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L106)):*
> ```XML
>   private _state = new BehaviorSubject<UpdateStatus>({loading: false, errorMessage: null});
>   private _categoriesExecuteSubscription: ISubscription;
>   readonly _fields = 'id,name, createdAt, directSubCategoriesCount, entriesCount, fullName,tags';
> ```

you are missing the `private` scope

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 107 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E2r2m3p0Ts0UeGyTH:-L1E2r2m3p0Ts0UeGyTI:b8ubzcm) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L107)):*
> ```XML
>   private _categoriesExecuteSubscription: ISubscription;
>   readonly _fields = 'id,name, createdAt, directSubCategoriesCount, entriesCount, fullName,tags';
>   readonly _pageSizeCacheKey = 'categories.list.pageSize';
> ```

you are missing the `private` scope

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 247 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E3dbAQwOyGvPASESo:-L1E3dbAQwOyGvPASESp:buoyvza) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L247)):*
> ```XML
> 
>           this._categories.data.next({
>             items: <any[]>response.objects,
> ```

why do you need the explicit `any` casting. this is extremely discourage unless you have a good reason. Currently we have it only in one place in our complete code base and this  due to extremely advance typescript implementation.  

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 327 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4U9cIjYKlJdSu3xH:-L1E4U9cIjYKlJdSu3xI:b9yp873) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L327)):*
> ```XML
> 
>       // remove advanced search arg if it is empty
>       if (advancedSearch.items && advancedSearch.items.length === 0) {
> ```

move this part to the end of the request. this is a cleanup that removed `advancedSearch` once all the filters are set if advancedSearch was not in use (in very rare situations)

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 337 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4FIQYHodufWkg0dA:-L1E4FIQYHodufWkg0dB:bfyljs3) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L337)):*
> ```XML
> 
>       // update desired fields of entries
>       if (this._fields) {
> ```

consider using constant instead of a property or just put the value directly because this is an essential part of the query.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 363 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E5A0Lpt2otpqNBrhN:-L1E5A0Lpt2otpqNBrhO:bacwkp9) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L363)):*
> ```XML
>       if (data.categoryListing) {
>         if (data.categoryListing.length === 1) {
>           data.categoryListing.forEach(item => {
> ```

this is a bit confusing loop using `forEach` when you know the length is exactly 1

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 376 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4toErWt1ingWkXQw:-L1E4toErWt1ingWkXQx:b-ujn3fb) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L376)):*
> ```XML
>           });
>         } else  if (data.categoryListing.length > 1) {
>           filter.appearInListEqual = undefined;
> ```

is this needed? this is the default value of any property if you don't assign anything.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 396 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4mjuJbCXcT99HMET:-L1E4mjuJbCXcT99HMEU:bw445cd) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L396)):*
> ```XML
>           });
>         } else if (data.contributionPolicy.length > 1) {
>           filter.contributionPolicyEqual = undefined;
> ```

is this needed? this is the default value of any property if yo udon't assign anything. 

---

*[src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.html, line 9 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E6MJKWdLe71_cO3P7:-L1E6MJKWdLe71_cO3P8:b-uhx0tr) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.html#L9)):*
> ```HTML
>        (onTagsChange)="onTagsChange.emit($event)">
>     <ng-template let-item="item">
>         <div class="kTagContent" [kTooltip]="item.tooltip?.token | translate : item.tooltip?.args">
> ```

we removed the tooltip token implementation last week to favor direct tooltip (to support situations when the tooltip is not taken from translation file like freetext, date range and some others.

[html](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.html#L9)
[item](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.ts#L10)
[example](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.ts#L131)

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.ts, line 359 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E8TJA3wJ31K6uP7Wa:-L1E8TJB-2GCwZPjgRJp:b-1dze4n) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.ts#L359)):*
> ```XML
>    * Not part of the API, don't use it from outside this component
>    */
>   public _blockScheduleToggle(event) {
> ```

I don't think this function is in use in categories

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 26 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E8bOuDidH-sUNvlzx:-L1E8bOuDidH-sUNvlzy:b-ygkw84) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L26)):*
> ```XML
> import {DefaultFiltersList} from './default-filters-list';
> 
> import * as R from 'ramda';
> ```

I don't think we use it anymore. If I'm right please remove this import from entries refine service as well

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 64 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E9HmwYz4bXv6vvIR5:-L1E9HmwYz4bXv6vvIR6:b-ndd3he) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L64)):*
> ```XML
>         ignoredCreateMode: MetadataProfileCreateModes.App
>       });
>       const otherData$ = this.buildQueryRequest();
> ```

I think you copied a lot of code here that is not relevant to categories. It seems that categories only have static lists and custom metadata. you don't need `getFlavours` and `otherData` meaning you don't need fork and your code should be much smaller. 




---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 153 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1EAFfTJuhurxUja7B7:-L1EAFfTJuhurxUja7B8:b-lxwe1y) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L153)):*
> ```XML
> 
>     try {
>       const accessControlFilter = new KalturaAccessControlFilter({});
> ```

see my comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1GScZFhGf5u0UgfN6x:-L1GScZFhGf5u0UgfN6y:by3lmau) (no related file):*
> categories-filters
missing number of categories and categories filter:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1GT1dGYxV3lnN3T9SV:-L1GT1dGYxV3lnN3T9SW:b-egepk0) (no related file):*
minor UI issue:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1GScZFhGf5u0UgfN6x:-L1IZOxA3c2AR-yG7PHG:b-oqivpo) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

> categories-filters
missing number of categories and categories filter:


</blockquote></details>

+@amirch1 the 'filter categories' should work for now, I will need to add it once we will merge categories into master

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by benstov** [comment]
Review status: 12 of 18 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1GScZFhGf5u0UgfN6x:-L1MLG4REosDYjsjX4Rv:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 the 'filter categories' should work for now, I will need to add it once we will merge categories into master
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1GT1dGYxV3lnN3T9SV:-L1MLd2yQ8vSXMfDS-vs:bcsoxs9) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

minor UI issue:


</blockquote></details>

There is only one. Ill check again after the merge if it still exists

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 106 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E2mvdRpKMVTyyTFNj:-L1MfUKjJTpWc7ZLXu-L:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L106)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you are missing the `private` scope
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 107 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E2r2m3p0Ts0UeGyTH:-L1MfUdSy2zOf8FOryYq:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L107)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you are missing the `private` scope
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 247 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E3dbAQwOyGvPASESo:-L1Mg0nPTON9YSvKxT5V:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L247)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

why do you need the explicit `any` casting. this is extremely discourage unless you have a good reason. Currently we have it only in one place in our complete code base and this  due to extremely advance typescript implementation.  
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 327 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4U9cIjYKlJdSu3xH:-L1MgUXJli4fgjBc1Btw:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L327)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

move this part to the end of the request. this is a cleanup that removed `advancedSearch` once all the filters are set if advancedSearch was not in use (in very rare situations)
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 337 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4FIQYHodufWkg0dA:-L1MmCwwFflBGL1wxBMh:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L337)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider using constant instead of a property or just put the value directly because this is an essential part of the query.
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 363 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E5A0Lpt2otpqNBrhN:-L1LvQfpKad-IzA3-FwO:b-ouht3c) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L363)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is a bit confusing loop using `forEach` when you know the length is exactly 1
</blockquote></details>

you are correct

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 376 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4toErWt1ingWkXQw:-L1MiN1gMsjv40nomAo0:b-o3cm12) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L376)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is this needed? this is the default value of any property if you don't assign anything.
</blockquote></details>

No need, i got confused and thought that i need to clean the object for unecessary properties (

---

*[src/applications/content-categories-app/categories/categories.service.ts, line 396 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E4mjuJbCXcT99HMET:-L1MjTzCxSh8Qer5f0iV:bwsggbj) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories.service.ts#L396)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is this needed? this is the default value of any property if yo udon't assign anything. 
</blockquote></details>

No need, i got confused between the data and the filter object, therefore i thought i should clean the filter object. 

---

*[src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.html, line 9 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E6MJKWdLe71_cO3P7:-L1MuDvl17xbQpLscpaK:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.html#L9)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

we removed the tooltip token implementation last week to favor direct tooltip (to support situations when the tooltip is not taken from translation file like freetext, date range and some others.

[html](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.html#L9)
[item](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.ts#L10)
[example](https://github.com/kaltura/kmc-ng/blob/master/src/shared/content-shared/entries-list/entries-list-tags.component.ts#L131)
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.ts, line 359 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E8TJA3wJ31K6uP7Wa:-L1Mk-6vEjssy7uAL0z1:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.ts#L359)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I don't think this function is in use in categories
</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 26 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E8bOuDidH-sUNvlzx:-L1MkFPAX5ZYcZ0oonz5:b-g55sms) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L26)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I don't think we use it anymore. If I'm right please remove this import from entries refine service as well
</blockquote></details>

we use it here:

      // get only fields that are list, searchable and has values
      const profileLists = R.filter(field => {
        return (field.type === MetadataItemTypes.List && field.isSearchable && field.optionalValues.length > 0);
      }, metadataProfile.items);


but i can refactor it to use metadataProfile.items.filter instead, what do u say?

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 64 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1E9HmwYz4bXv6vvIR5:-L1MuDAj1Ovk67FC556U:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L64)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I think you copied a lot of code here that is not relevant to categories. It seems that categories only have static lists and custom metadata. you don't need `getFlavours` and `otherData` meaning you don't need fork and your code should be much smaller. 




</blockquote></details>

Done.

---

*[src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts, line 153 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-L1EAFfTJuhurxUja7B7:-L1MmAvFvNagu1kjTBCA:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/6e40dc7fed91f13de61b660f61341650ea118930/src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.service.ts#L153)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see my comment above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312#-:-L1R4lzWgGNbsY6Jp8z7:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Comment by esakal** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/312)*

**Pull request merged**
