### PR TITLE
KMCNG-1392

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1392

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/451)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts, line 81 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/451#-L7JK1Zs4ohNzz6fIyJ9:-L7JK1Zs4ohNzz6fIyJA:b-fsbnov) ([raw file](https://github.com/kaltura/kmc-ng/blob/09b5ee8f0922e9035f843dc5eb1a3b7464664114/src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts#L81)):*
> ```XML
>     super._showLoader();
> 
>     if (this.isNewData) {
> ```

the bug deals with rule based playlist, this change affect content of manual playlist

---

*[src/applications/content-playlists-app/playlist/playlist-content/rule-based/rule-based-content-widget.service.ts, line 67 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/451#-L7JK7Pc4_pwY9HAVMYs:-L7JK7Pc4_pwY9HAVMYt:bpwo5qb) ([raw file](https://github.com/kaltura/kmc-ng/blob/09b5ee8f0922e9035f843dc5eb1a3b7464664114/src/applications/content-playlists-app/playlist/playlist-content/rule-based/rule-based-content-widget.service.ts#L67)):*
> ```XML
>     this.entriesTotalCount = 0;
> 
>     if (this.isNewData) {
> ```

the bug talks about a state of the playlist when just added, I think it is the responsibility of playlist service and not part of the section logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/451)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-content/rule-based/rule-based-content-widget.service.ts, line 67 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/451#-L7JK7Pc4_pwY9HAVMYs:-L7O81S3qtjgzKZpAlXq:b-18i9jw) ([raw file](https://github.com/kaltura/kmc-ng/blob/09b5ee8f0922e9035f843dc5eb1a3b7464664114/src/applications/content-playlists-app/playlist/playlist-content/rule-based/rule-based-content-widget.service.ts#L67)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the bug talks about a state of the playlist when just added, I think it is the responsibility of playlist service and not part of the section logic.
</blockquote></details>

not sure if I got it, how can we set the dirty status to sections from the service, it's responsibility of the section-service

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/451)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts, line 81 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/451#-L7JK1Zs4ohNzz6fIyJ9:-L7O8He26m7phTgp8R_a:b-c1wwjc) ([raw file](https://github.com/kaltura/kmc-ng/blob/09b5ee8f0922e9035f843dc5eb1a3b7464664114/src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts#L81)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the bug deals with rule based playlist, this change affect content of manual playlist
</blockquote></details>

I know, but I this both of them should be consistent and behave in the same way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/451)*

**Comment by esakal** [comment]
already implemented

**Pull request closed without merging**
