### PR TITLE
fix: ability to compile in the prod mode

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/249)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
The build is completed fine for now, but we have issues with the app itself.

  

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/249#-Kxi3jI5LeP399Jb987Y:-Kxi3jI5LeP399Jb987Z:b6i59e7) ([raw file](https://github.com/kaltura/kmc-ng/blob/153e01e6d21ab302510310795e85b97727510a14/package.json#L80)):*
> ```JSON
>   },
>   "devDependencies": {
>     "@angular/cli": "~1.4.9",
> ```

+@esakal Except other issues, this one was the main one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/249#-:-Kxi3sT_CHtqYab-HgC8:b-ok9knj)*

**Comment by esakal** [comment]
Reviewed 14 of 16 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-details/entry-details.component.html, line 7 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/249#-KxmutI5SVtmaRw5fw6S:-KxmutI5SVtmaRw5fw6T:bpufdru) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7379f0f52c5691415f01072ce82a4ece6e8cf80/src/applications/content-entries-app/entry/entry-details/entry-details.component.html#L7)):*
> ```HTML
>     <kDetailInfo [label]="'applications.content.entryDetails.preview.updateDate' | translate" [value]="_currentEntry?.updatedAt | date:'MM/dd/y HH:MM'"></kDetailInfo>
>     <kDetailInfo *ngIf="_widgetService._landingPage" [label]="'applications.content.entryDetails.preview.landingPage' | translate" [link]="_widgetService._landingPage" [tooltip]="_widgetService._landingPage"></kDetailInfo>
>     
> ```

stas is this something that you removed temporary or you want me to check what happens here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/249)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-details/entry-details.component.html, line 7 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/249#-KxmutI5SVtmaRw5fw6S:-KxmvdbkWiJ6OAbDVD5p:b-48qmwr) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7379f0f52c5691415f01072ce82a4ece6e8cf80/src/applications/content-entries-app/entry/entry-details/entry-details.component.html#L7)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

stas is this something that you removed temporary or you want me to check what happens here?
</blockquote></details>

_currentEntry is instanceof KalturaMediaEntry and compiler says that  there's no recordedEntryId, better check if currentEntry has this property

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/249)*

**Comment by diamond-darrell** [comment]
Review status: 16 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-entries-app/entry/entry-details/entry-details.component.html, line 7 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/249#-KxmutI5SVtmaRw5fw6S:-KxqMre7G0gKabxOUnIx:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/c7379f0f52c5691415f01072ce82a4ece6e8cf80/src/applications/content-entries-app/entry/entry-details/entry-details.component.html#L7)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

_currentEntry is instanceof KalturaMediaEntry and compiler says that  there's no recordedEntryId, better check if currentEntry has this property
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/249)*

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/249)*

**Pull request merged**
