### PR TITLE
KMCNG-1274

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/358)

### CODE REVIEW

**Comment by esakal** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/358#-L4UfNXwFc6pU0nf6WRi:-L4UfNXwFc6pU0nf6WRj:bvwo3td) (no related file):*
+@amirch1 can you please verify this fix in the application?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/358#-:-L4UfNBHaJX03yGRMTX3:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/358)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/358#-:-L4oJKjrnyTzL5i2ilSV:bnfp4nl)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/358#-L4UfNXwFc6pU0nf6WRi:-L4oJP4v97DgaRdlMNFQ:bddkgsz) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@amirch1 can you please verify this fix in the application?
</blockquote></details>

working fine!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/358)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/358)*

**Pull request merged**
