### PR TITLE
Playlist fixes

### PR DESCRIPTION
**Pull request by konstantin-stepanets**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/kaltura/kmc-ng/pull/177?approve=1'></a>&nbsp;<a href='https://github.com/kaltura/kmc-ng/pull/177'></a>
<a href='#crh-end'></a>

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/177)

### CODE REVIEW

**Comment by esakal** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/kaltura/kmc-ng/pull/177'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html, line 10 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpU1-0I_jAe8-9t7s7K:-KpU1-0I_jAe8-9t7s7L:bk7foz1) ([raw file](https://github.com/kaltura/kmc-ng/blob/1e8676b0c383104db770154356b90869bdbf46ba/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html#L10)):*
> ```HTML
>         <div class="kControl">
>           <input formControlName="name" type="text" pInputText #metadataNameInput />
>           <div [ngClass]="{'invalid': metadataForm.invalid, 'hidden': metadataForm.valid}">You must enter a playlist name</div>
> ```

please use the translation for that message

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts, line 105 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpU1MNgHiGXSw3Fg37U:-KpU1MNgHiGXSw3Fg37V:b-8fx2u7) ([raw file](https://github.com/kaltura/kmc-ng/blob/1e8676b0c383104db770154356b90869bdbf46ba/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts#L105)):*
> ```XML
> 
>   ngAfterViewInit() {
>     this.metadataNameInput.nativeElement.focus();
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177)*

**Comment by konstantin-stepanets** [comment]
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html, line 10 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpU1-0I_jAe8-9t7s7K:-Kpsb9ND98d7f3eN23K-:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/1e8676b0c383104db770154356b90869bdbf46ba/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html#L10)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please use the translation for that message
</blockquote></details>

Done.

---

*[src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts, line 105 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpU1MNgHiGXSw3Fg37U:-KpsbBNTSN7o7_Zx8oBL:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/1e8676b0c383104db770154356b90869bdbf46ba/src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts#L105)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177)*

**Comment by esakal** [comment]
Please see my comments

---

Reviewed 1 of 7 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-playlists-app/content-playlists-app.module.ts, line 70 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsa7mPdknzGoF4OsnQ:-Kpsa7mPdknzGoF4OsnR:bwd2xqx) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/content-playlists-app.module.ts#L70)):*
> ```XML
>       PlaylistsStore,
>       PlaylistStore,
>       EntryCanDeactivate
> ```

should be named `PlaylistCanDeactivate` (you left the original name from the entry application)

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 121 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsaz8ws6nHuIvxCR2U:-Kpsaz8xCZllkAFhbnuJ:bgtc411) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L121)):*
> ```XML
> 						this._playlist.next({playlist: response});
> 						this._state.next({isBusy: false});
>             this._sectionsState.next({
> ```

I don't think you should handle it here.

---

See the below scenario and let me know where I'm wrong:
When you reload playlist you update the `_playlist`observable. 
->
this in turn updates `playlist-metadata.component.ts` component in the `OnInit()` method.
-> 
the metadata component is responsible on the metadata form and it reset its' content.
->
the reset should trigger the form `statusChanges` and `valueChanges` which update the service section state -> so you don't need to handle it in the service.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 249 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsdeqlu7HfyXCi80IZ:-Kpsdeqlu7HfyXCi80I_:b-qzkjua) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L249)):*
> ```XML
> 
>   private _onSectionsStateChanges() {
>     this.sectionsState$
> ```

as the owner of the `BehaviorSubject` you never need to subscribe to it since you are the one that update it.

this is consider anti-pattern. just update those properties where you perform the `next` on the `BehaviorSubject`

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 253 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpse6NMl6p6BtwItwJF:-Kpse6NMl6p6BtwItwJG:b-jq6qyc) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L253)):*
> ```XML
>       .subscribe(
>         sectionState => {
>           if(sectionState.metadata.isDirty || sectionState.content.isDirty) {
> ```

FYI since you are removing this code it is not relevant but I do want to remind you that you must always handle `else` part of expressions.

The else part was a perfect place to disable page exit verification... again you shouldn't fix this because you are going to remove this part anyhow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-:-KpsevHZUbg9dhNHrwOv:blap1ai)*

**Comment by konstantin-stepanets** [comment]
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/applications/content-playlists-app/content-playlists-app.module.ts, line 70 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsa7mPdknzGoF4OsnQ:-KptQqZRn1FP8MOCXidN:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/content-playlists-app.module.ts#L70)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

should be named `PlaylistCanDeactivate` (you left the original name from the entry application)
</blockquote></details>

Done.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 121 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsaz8ws6nHuIvxCR2U:-KptQkSBy_MyEenf7eQS:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L121)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I don't think you should handle it here.

---

See the below scenario and let me know where I'm wrong:
When you reload playlist you update the `_playlist`observable. 
->
this in turn updates `playlist-metadata.component.ts` component in the `OnInit()` method.
-> 
the metadata component is responsible on the metadata form and it reset its' content.
->
the reset should trigger the form `statusChanges` and `valueChanges` which update the service section state -> so you don't need to handle it in the service.



</blockquote></details>

Done.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 249 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpsdeqlu7HfyXCi80IZ:-KptQlpfsaFkfo0--yhn:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L249)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

as the owner of the `BehaviorSubject` you never need to subscribe to it since you are the one that update it.

this is consider anti-pattern. just update those properties where you perform the `next` on the `BehaviorSubject`
</blockquote></details>

Done.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 253 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-Kpse6NMl6p6BtwItwJF:-KptQo8QrV8BDOosm3gX:b-896fix) ([raw file](https://github.com/kaltura/kmc-ng/blob/d6b3be8916de94f7c515832829f27b5967e3f3df/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L253)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

FYI since you are removing this code it is not relevant but I do want to remind you that you must always handle `else` part of expressions.

The else part was a perfect place to disable page exit verification... again you shouldn't fix this because you are going to remove this part anyhow.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177)*

**Comment by esakal** [comment]
almost there... let's discuss about the last comment when we touch base later today

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 169 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpxZRzgYycNCx1zy5nZ:-KpxZRzhbuwrwb2Wkdru:bxsxzgv) ([raw file](https://github.com/kaltura/kmc-ng/blob/278a8aa1f6b7803a417c668732677495403d4e09/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L169)):*
> ```XML
>     if(hasChanges) {
>       this._sectionsState.next(sections);
>       this._entryIsDirty = true;
> ```

let's discuss about this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-:-Kpx_NP9ZHEEbLEliwIb:bq7sxw2)*

**Comment by konstantin-stepanets** [comment]
OK

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-playlists-app/playlist/playlist-store.service.ts, line 169 at r3](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-KpxZRzgYycNCx1zy5nZ:-Kpy2gowq7IeQQkhqtLu:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/278a8aa1f6b7803a417c668732677495403d4e09/src/applications/content-playlists-app/playlist/playlist-store.service.ts#L169)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

let's discuss about this
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-:-Kpy2iOfZf9D_4iCo1jp:b32w0x)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/177#-:-KpyaRVOx5wOEJw7mo8Q:bnfp4nl)*

**Pull request merged**
