### PR TITLE
KMCNG-890

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-890

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/432)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 67 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/432#-L6zmsu9NLsYf4JYKTGa:-L6zmsuASz6fEsCQk2az:b-d8pzzm) ([raw file](https://github.com/kaltura/kmc-ng/blob/eb1a544829f8d92d23ddb6adb825a99774d3649b/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L67)):*
> ```XML
>     this._uploadManagement.onTrackedFileChanged$
>       .cancelOnDestroy(this)
>       .filter(trackedFile => trackedFile.data instanceof NewEntryUploadFile && trackedFile.status === TrackedFileStatuses.prepared)
> ```

shouldn't this code look for status `added`? I think it is one-time status that is the default one.

also, I'm not sure but I think we have an app event that might be relevant for this use case.... but I don't mind using the suggested design  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/432)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 67 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/432#-L6zmsu9NLsYf4JYKTGa:-L6znf-YkJldonGLZuQ_:b-j7jsza) ([raw file](https://github.com/kaltura/kmc-ng/blob/eb1a544829f8d92d23ddb6adb825a99774d3649b/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L67)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

shouldn't this code look for status `added`? I think it is one-time status that is the default one.

also, I'm not sure but I think we have an app event that might be relevant for this use case.... but I don't mind using the suggested design  
</blockquote></details>

I think `prepared` status is better because we know that entry was created and if we reload page on added status there's a chance that user won't see changes after reload

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/432)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/content-entries-app/entries/entries-list-holder.component.ts, line 67 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/432#-L6zmsu9NLsYf4JYKTGa:-L6zpCR4GCPj4uIQWyqe:b88f133) ([raw file](https://github.com/kaltura/kmc-ng/blob/eb1a544829f8d92d23ddb6adb825a99774d3649b/src/applications/content-entries-app/entries/entries-list-holder.component.ts#L67)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I think `prepared` status is better because we know that entry was created and if we reload page on added status there's a chance that user won't see changes after reload
</blockquote></details>

OK agreed nice thought

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/432)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/432#-:-L6zpGFsZoRYrcSJ84h6:bnfp4nl)*

**Pull request merged**
