### PR TITLE
Users

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/299)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 9 of 30 files at r4, 1 of 3 files at r7, 1 of 9 files at r8, 21 of 34 files at r9.
Review status: 26 of 39 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zY26-EkJ2NMti6UX3:-L-zY26-EkJ2NMti6UX4:b-t4wuv6) (no related file):*
the publisher user id style is wrong, it seems as if it is disabled....



---

*[src/applications/administration-users-app/users/users.service.ts, line 43 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zIhWJsZ2m6tgO6dSi:-L-zIhWJsZ2m6tgO6dSj:b-3lm4f6) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L43)):*
> ```XML
> @Injectable()
> export class UsersStore implements OnDestroy {
>   private _users = {
> ```

nice :) do you like this technique of joined object for both data and state? or do you prefer the old approach?

---

*[src/applications/administration-users-app/users/users.service.ts, line 147 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zKNUoGytC2wUUSYhp:-L-zKNUoGytC2wUUSYhq:b-ssr0nh) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L147)):*
> ```XML
>     const isAdminUser = this._usersDataValue && this._usersDataValue.partnerInfo.adminUserId === user.id;
> 
>     if (isCurrentUser && isAdminUser) {
> ```

**comment 1:**
It should be **or** condition not **and** condition

also, it seems like those conditions are missing in the PRD, can you please update the PRD accordingly, for example requierments:
- User actions - Block / Unblock
- User actions - Delete
- 



---

*[src/applications/administration-users-app/users/users.service.ts, line 169 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zKYoLBB54ZERmRtx0:-L-zKYoLBB54ZERmRtx1:bqtamg6) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L169)):*
> ```XML
>     const isAdminUser = this._usersDataValue && this._usersDataValue.partnerInfo.adminUserId === user.id;
> 
>     if (isCurrentUser && isAdminUser) {
> ```

search for **comment 1**

---

*[src/applications/administration-users-app/users/users.service.ts, line 188 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zQkIVT9ZFrD6te-34:-L-zQkIVT9ZFrD6te-35:blddbuk) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L188)):*
> ```XML
>           ? IsUserExistsStatuses.otherSystemUser :
>           (error.code === 'USER_NOT_FOUND' ? IsUserExistsStatuses.unknownUser : '');
>         return Observable.throw(status);
> ```

for valid statuses, return `Observable.of()` because we must assume observable error callback gets `Error` type. use `Observable.throw only if both code are not relevant.

---

*[src/applications/administration-users-app/users/users.service.ts, line 197 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zXIG94rFl939N_-Zx:-L-zXIG94rFl939N_-Zy:b-utzcw) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L197)):*
> ```XML
> 
>   public addUser(userForm: FormGroup): Observable<void> {
>     const { roleIds, id, email, firstName, lastName } = userForm.value;
> ```

please make sure that mandatory fields are provided

---

*[src/applications/administration-users-app/users/users.service.ts, line 224 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zXDW38WhxKHLBBN0_:-L-zXDW38WhxKHLBBN0a:bz74spq) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L224)):*
> ```XML
> 
>   public updateUser(userForm: FormGroup): Observable<void> {
>     const { roleIds, id, email, firstName, lastName } = userForm.value;
> ```

please validate that either id or email is provided 

---

*[src/applications/administration-users-app/users/users.service.ts, line 226 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zYcrTb_3lestkbnzD:-L-zYcrTb_3lestkbnzE:bb9d5rv) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L226)):*
> ```XML
>     const { roleIds, id, email, firstName, lastName } = userForm.value;
>     const user = new KalturaUser({
>       email,
> ```

update user shouldn't allow updates of `email`, `firstName`, `lastName`



---

*[src/applications/administration-users-app/users/edit-user/edit-user.component.ts, line 28 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zdBuOQAs29UBCvRHT:-L-zdBuOQAs29UBCvRHU:b-q3miod) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/edit-user/edit-user.component.ts#L28)):*
> ```XML
>   @Input() user: KalturaUser;
> 
>   private _partnerInfo: PartnerInfo = { adminLoginUsersQuota: 0, adminUserId: null };
> ```

check if you consume it in the html, if so it should be public to pass `prod` build

---

*[src/applications/administration-users-app/users/edit-user/edit-user.component.ts, line 55 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zdtvAj_BSMSk-7Yxo:-L-zdtvAj_BSMSk-7Yxp:b-jc3bkj) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/edit-user/edit-user.component.ts#L55)):*
> ```XML
> 
>   ngOnInit() {
>     this._usersStore.users.data$
> ```

- consider using `first()` operator since I assume you need this data only once
- aren't you missing `isBusy` usage?x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by diamond-darrell** [comment]
Review status: 14 of 39 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zY26-EkJ2NMti6UX3:-L03pf0b2LzLN1lhhfWC:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the publisher user id style is wrong, it seems as if it is disabled....



</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 43 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zIhWJsZ2m6tgO6dSi:-L03boffaYT_adBnBp__:bay7yyf) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L43)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

nice :) do you like this technique of joined object for both data and state? or do you prefer the old approach?
</blockquote></details>

yeah, I think in this way the developer has more self-explanatory API

---

*[src/applications/administration-users-app/users/users.service.ts, line 147 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zKNUoGytC2wUUSYhp:-L03jZcdhLurmpwH0vbD:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L147)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

**comment 1:**
It should be **or** condition not **and** condition

also, it seems like those conditions are missing in the PRD, can you please update the PRD accordingly, for example requierments:
- User actions - Block / Unblock
- User actions - Delete
- 



</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 169 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zKYoLBB54ZERmRtx0:-L03jPCxRO3YUs4lNxtm:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L169)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

search for **comment 1**
</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 188 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zQkIVT9ZFrD6te-34:-L03lb2R7bsYA7KW1eAi:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L188)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

for valid statuses, return `Observable.of()` because we must assume observable error callback gets `Error` type. use `Observable.throw only if both code are not relevant.
</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 197 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zXIG94rFl939N_-Zx:-L03qIKuzLz1jwjXv9N4:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L197)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please make sure that mandatory fields are provided
</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 224 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zXDW38WhxKHLBBN0_:-L03qJG6I3Z2g5gNJyAv:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L224)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

please validate that either id or email is provided 
</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/users.service.ts, line 226 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zYcrTb_3lestkbnzD:-L03ia-Am7tND8WCjtM7:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/users.service.ts#L226)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

update user shouldn't allow updates of `email`, `firstName`, `lastName`



</blockquote></details>

OK

---

*[src/applications/administration-users-app/users/edit-user/edit-user.component.ts, line 28 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zdBuOQAs29UBCvRHT:-L03dALhUWIehklliUMp:b-9ua9bu) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/edit-user/edit-user.component.ts#L28)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

check if you consume it in the html, if so it should be public to pass `prod` build
</blockquote></details>

OK, I've tried to build app in the prod mode, it builds without errors during the build and at the runtime

---

*[src/applications/administration-users-app/users/edit-user/edit-user.component.ts, line 55 at r9](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L-zdtvAj_BSMSk-7Yxo:-L03dJZFGdF3uc3kLSKp:b-kf8jwg) ([raw file](https://github.com/kaltura/kmc-ng/blob/391aa762b563b123221f1969ca9bd0d227b72030/src/applications/administration-users-app/users/edit-user/edit-user.component.ts#L55)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- consider using `first()` operator since I assume you need this data only once
- aren't you missing `isBusy` usage?x

</blockquote></details>

I'm not sure why do I need `isBusy` here. I assume that there are already loaded users when I open this screen and if there's no relevant user I consider it as the new one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
Reviewed 3 of 30 files at r4, 11 of 34 files at r9, 13 of 14 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/administration-users-app/users/users-table.component.ts, line 147 at r10](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L0sTaXtOMSGB6IdXlks:-L0sTaXtOMSGB6IdXlkt:bhf4roe) ([raw file](https://github.com/kaltura/kmc-ng/blob/e73faf0887a5e0598eb5132540af0bac0bd7ffb5/src/applications/administration-users-app/users/users-table.component.ts#L147)):*
> ```XML
>   }
> 
>   public _getAccountOwner(user: KalturaUser): string {
> ```

change this to a pipe to improve performance (pipes are pure and thus their response is cacheable)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/applications/administration-users-app/users/users-table.component.ts, line 147 at r10](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L0sTaXtOMSGB6IdXlks:-L0sYSufx1GMiEMtdiRO:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/e73faf0887a5e0598eb5132540af0bac0bd7ffb5/src/applications/administration-users-app/users/users-table.component.ts#L147)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

change this to a pipe to improve performance (pipes are pure and thus their response is cacheable)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
Reviewed 1 of 30 files at r4, 6 of 6 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-:-L0th1g9HqJvip_p4F7c:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 7 of 30 files at r4, 1 of 3 files at r7, 1 of 9 files at r8, 20 of 34 files at r9, 9 of 14 files at r10, 6 of 6 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L16JIK6_SLe8eLH2FbK:-L16JIK7cgLBD_2Q9bue:b8atta6) (no related file):*
Seems that validation is not implemented correctly in the "New User" form - all required fields are marked as invalid even when values are entered. See attached capture.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by diamond-darrell** [comment]
Review status: 33 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L16JIK6_SLe8eLH2FbK:-L1Byu1NnN8OaMtloPtz:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

Seems that validation is not implemented correctly in the "New User" form - all required fields are marked as invalid even when values are entered. See attached capture.


</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
Reviewed 5 of 6 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L16JIK6_SLe8eLH2FbK:-L1Eb9KT5wuidKMddTHe:bx3gzhk) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

+@amirch1 please check and LGTM if relevant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GVVfImpR9MFre36Oy:-L1GVVfImpR9MFre36Oz:b-4f5obk) (no related file):*
invalid fields styles is incorrect. Definitions can be found here: https://projects.invisionapp.com/d/main#/console/11292789/241793732/preview


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GXnjwsC_IkTVd7HRe:-L1GXnjxWBYicSCsreQm:bwfre48) (no related file):*
> https://projects.invisionapp.com/d/main#/console/11292789/241793732/preview
When updating the Publisher User ID and trying to save - I'm getting an "Invalid User ID" error while in legacy KMC it is saved without errors - please check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GVVfImpR9MFre36Oy:-L1GfEiOqJCOivuC9uBz:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

invalid fields styles is incorrect. Definitions can be found here: https://projects.invisionapp.com/d/main#/console/11292789/241793732/preview


</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GXnjwsC_IkTVd7HRe:-L1GfJPq1tg9uKyOnKbg:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

> https://projects.invisionapp.com/d/main#/console/11292789/241793732/preview
When updating the Publisher User ID and trying to save - I'm getting an "Invalid User ID" error while in legacy KMC it is saved without errors - please check.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by diamond-darrell** [comment]
Review status: 36 of 38 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GVVfImpR9MFre36Oy:-L1H3t7SBY78yCu-9b9M:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GXnjwsC_IkTVd7HRe:-L1H3urix9TC-dawQNX6:b-896fix) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by esakal** [comment]
Reviewed 1 of 30 files at r4, 5 of 5 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GXnjwsC_IkTVd7HRe:-L1H8nl1vkD73xgF7Asx:b-ems8b7) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still getting the error when changing the ID of an existing user

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by diamond-darrell** [comment]
Review status: 35 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-L1GXnjwsC_IkTVd7HRe:-L1HG676zS136cZOmaef:b-896fix) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

still getting the error when changing the ID of an existing user
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 30 files at r4, 2 of 6 files at r12, 5 of 5 files at r13.
Review status: 35 of 38 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299#-:-L1HJuuBKIXTBR3mItOZ:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 1 of 30 files at r4, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/299)*

**Pull request merged**
