### PR TITLE
feat(upload-menu): add upload menu component

### PR DESCRIPTION
**Pull request by diamond-darrell**
Implement component's template and integrate in the system

### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Upload button does nothing

**What is the new behavior?**
Upload button opens upload menu

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/183)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/components/app-menu/app-menu.component.html, line 56 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-KrAy69HgrPLzxXGFkQD:-KrAy69HgrPLzxXGFkQE:b-fdui1t) ([raw file](https://github.com/kaltura/kmc-ng/blob/601e5bdb043847d4cf18d1f341161a1d13516a4f/src/app/components/app-menu/app-menu.component.html#L56)):*
> ```HTML
> 
> <kPopupWidget #uploadmenu [popupWidth]="315" [popupHeight]="385" [closeBtn]="true" [modal]="true" [transparent]="true">
>   <kKMCUploadMenu></kKMCUploadMenu>
> ```

It is better to wrap the inner content with `<ng-template>` 

when using <ng-template> the component will not be created until the user shows the popup. It will also be destroyed once the popup is closed.

Setting content without `<ng-template>` will create the popup content once `app-menu component` is created and will just hide/show the same instance.

I know most of our code is not using the <ng-template> so let's add +@amirch1 to the conversation... Amir what do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183)*

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/upload/upload-menu/upload-menu.component.html, line 3 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-KrPFL2KLVTLi3-fDbAi:-KrPFL2KLVTLi3-fDbAj:b-aavf96) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab693e0b6a470f61552bf0487714f827f003a936/src/app/components/upload/upload-menu/upload-menu.component.html#L3)):*
> ```HTML
> <div class="kUploadMenu">
>   <div class="item">
>     <i class="kIconUpload blue"></i>
> ```

does the `blue` part of our code? if so I think you should use a name that explain the application instead of the layout. if blue represent uploading then `kUploading`, if title then `kUploadTitle` etc... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183)*

**Comment by diamond-darrell** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/components/upload/upload-menu/upload-menu.component.html, line 3 at r2](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-KrPFL2KLVTLi3-fDbAi:-KrUP4lFzHbQ-u32f5D-:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/ab693e0b6a470f61552bf0487714f827f003a936/src/app/components/upload/upload-menu/upload-menu.component.html#L3)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

does the `blue` part of our code? if so I think you should use a name that explain the application instead of the layout. if blue represent uploading then `kUploading`, if title then `kUploadTitle` etc... 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183)*

**Comment by diamond-darrell** [comment]
*[src/app/components/app-menu/app-menu.component.html, line 56 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-KrAy69HgrPLzxXGFkQD:-KrW2q2R0Mw2L0XMvjsl:b9hymwq) ([raw file](https://github.com/kaltura/kmc-ng/blob/601e5bdb043847d4cf18d1f341161a1d13516a4f/src/app/components/app-menu/app-menu.component.html#L56)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

It is better to wrap the inner content with `<ng-template>` 

when using <ng-template> the component will not be created until the user shows the popup. It will also be destroyed once the popup is closed.

Setting content without `<ng-template>` will create the popup content once `app-menu component` is created and will just hide/show the same instance.

I know most of our code is not using the <ng-template> so let's add +@amirch1 to the conversation... Amir what do you think? 
</blockquote></details>

I added ng-template in upload-settings branch, should I add it here as well or it will wait until that branch will be merged?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/components/app-menu/app-menu.component.html, line 56 at r1](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-KrAy69HgrPLzxXGFkQD:-Kr_g-5kksT6R1qIgmRp:b-9vlhd4) ([raw file](https://github.com/kaltura/kmc-ng/blob/601e5bdb043847d4cf18d1f341161a1d13516a4f/src/app/components/app-menu/app-menu.component.html#L56)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I added ng-template in upload-settings branch, should I add it here as well or it will wait until that branch will be merged?
</blockquote></details>

OK no needed to add it here as well 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-:-Kr_mSff8W4d4BwMGiIg:bnfp4nl)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kmc-ng/183#-:-Kr_n1p8jWy8qLw8uYYT:bnfp4nl)*

**Pull request merged**
