### PR TITLE
Implement METADATA_PLUGIN_PERMISSION permission

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information

**What is the current behavior?**

**What is the new behavior?**
https://kaltura.atlassian.net/browse/KMCNG-1701

**Does this PR introduce a breaking change?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 94 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv0eQn6j7k177hsvdJ:-LBv0eQn6j7k177hsvdK:b4j02qu) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L94)):*
> ```XML
> 
>     protected onActivate(firstTimeActivating: boolean): Observable<{ failed: boolean }> {
>         if (!this._permissionsService.hasPermission(KMCPermissions.METADATA_PLUGIN_PERMISSION)) {
> ```

this change will ignore required logic like disabling the form due to permissions or setting reference id.

- Just to be sure the requirement is clear, you do need to show the user metadata section just without custom sections. see the following 2 comments.
- check if this comment apply to entries as well (i didn't read the code there yet)
- make sure you block relevant parts of the save operations as well.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 102 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv2BhZ6YezCtxR3pTT:-LBv2BhZ6YezCtxR3pTU:bq8wvci) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L102)):*
> ```XML
> 
>         const actions: Observable<{ failed: boolean, error?: Error }>[] = [
>             this._loadCategoryMetadata(this.data)
> ```

consider instead using the same logic and only change the initialization of `actions`. Instead of always setting `_loadCategoryMetadata(this.data)` - add it only if has the relevant permissions. 

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 106 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv2CNmAUcbFeXAKzJl:-LBv2CNmAUcbFeXAKzJm:br53a09) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L106)):*
> ```XML
> 
>         if (firstTimeActivating) {
>             actions.push(this._loadProfileMetadata());
> ```

consider adding to this condition the check if has the right permission.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 94 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv0eQn6j7k177hsvdJ:-LBv7i597Lhf3FsLdSvm:bw518l4) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L94)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this change will ignore required logic like disabling the form due to permissions or setting reference id.

- Just to be sure the requirement is clear, you do need to show the user metadata section just without custom sections. see the following 2 comments.
- check if this comment apply to entries as well (i didn't read the code there yet)
- make sure you block relevant parts of the save operations as well.


</blockquote></details>

OK, I hope I've gotten an idea...

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 102 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv2BhZ6YezCtxR3pTT:-LBv7fb_8dbBFrdmQDfY:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L102)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider instead using the same logic and only change the initialization of `actions`. Instead of always setting `_loadCategoryMetadata(this.data)` - add it only if has the relevant permissions. 
</blockquote></details>

OK

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 106 at r1](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LBv2CNmAUcbFeXAKzJl:-LBv7gD5DCCP-W6SwNvE:b32w0x) ([raw file](https://github.com/kaltura/kmc-ng/blob/c5cff3bab2fbbc0403005eea28397d91aeddf57c/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L106)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider adding to this condition the check if has the right permission.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630)*

**Comment by esakal** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts, line 110 at r2](https://reviewable.io/reviews/kaltura/kmc-ng/630#-LByMvo6-VE0R3ZuLvn9:-LByMvo6-VE0R3ZuLvnA:b-jjrs9l) ([raw file](https://github.com/kaltura/kmc-ng/blob/c660a974576a5eeaf1993165bc371625805010ab/src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts#L110)):*
> ```XML
>         }
> 
>         if (!actions.length) {
> ```

otherwise, `forJoin` won't be called

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630)*

**Comment by esakal** [comment]
Waiting for +@diamond-darrell to approve my adjustments

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630#-:-LByWSvl6MCUrw-eyyIo:bwec3kl)*

**Comment by diamond-darrell** [comment]
LGTM

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kmc-ng/630#-:-LByWh8d3x-6YS-AEysX:bb6ywmx)*

**Pull request merged**
